### PR TITLE
[Docs] Implemented a quick installation quiz in the "Installation" landing page

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs: Implemented a quick installation quiz in the "Installation" landing page.

---

### Additional information

TODOs:

*   [x] The rest of the quiz flow (currently 6 questions and 6 resolutions - predefined, OB, from source, DLLs, Frameworks, migrate from CKE4),
*   [ ] Proofreading

### CODE REVIEW

**Comment by godai78** [comment]
We also need to include Online Builder in the docs. And I believe we at least need a guide that mentions the OB (I even have had written an OB step-by-step quick start last year, but it does not need to be that long). Right now it's basically mentioned in "download options" which is not exactly the best way to showcase it.

**Comment by oleq** [comment]
> Right now it's basically mentioned in "download options" which is not exactly the best way to showcase it.

The decision panel could link directly to https://ckeditor.com/ckeditor-5/online-builder/.

**Comment by godai78** [comment]
I allowed myself to align this with the current work.

**Comment by godai78** [comment]
Webpack drama unleashed.

**Pull request merged**
