### PR TITLE
Added description for new `--dll` flag for manual tests

### PR DESCRIPTION
**Pull request by psmyrek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs: Added description for the new `--dll` and `--no-dll` flags, that are available for manual tests.

---

### Additional information

This is part of ckeditor/ckeditor5-dev#787.

### CODE REVIEW

**Comment by psmyrek** [comment]
@godai78 May I ask you for a review?

**Review by godai78 — APPROVED** [review]
LGTM

**Comment by pomek** [comment]
Changes described in this PR are merged (https://github.com/ckeditor/ckeditor5-dev/pull/787). However, we would like to resolve https://github.com/ckeditor/ckeditor5/issues/12469 before releasing a new version. Hence, let's wait to merge this PR.

**Comment by pomek** [comment]
:tada: https://github.com/ckeditor/ckeditor5-dev/releases/tag/v31.1.0

**Pull request merged**
