### PR TITLE
#7633: Resizer#redraw() should not change the editing view unless a different size should be set

### LINKED ISSUE #7633: Blue border glitch when undoing image resize
## 📝 Provide detailed reproduction steps (if any)

1. Resize some image
2. To see it clearly keep pressing `undo` and `redo`

### ❌ Actual result

The blue border stays as its place for a split second and then jumps to fit the size of the image.  
16_image_4

## 📃 Other details

* Browser: any
* CKEditor version: since 17

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix: `Resizer#redraw()` should not change the editing view unless a different size should be set. Closes #7633.

### CODE REVIEW

**Comment by oleq** [comment]
The glitch should be gone now.

**Comment by oleq** [comment]
FYI: #7548 is a different problem.

**Comment by Reinmar** [comment]
The PR looks good to me and I'd be completely fine to merge it but what I described in https://github.com/ckeditor/ckeditor5/issues/7548#issuecomment-662265194 worries me. Why two similar issues appeared so close one another? What's causing the paste/upload glitch? I have a feeling that there's something wrong elsewhere and that a fix for that thing may fix both issues.

Still, I'll be ok with merging this PR, but after we check whether a fix for the other bug will not resolve this too (if we merge this PR it won't be that easy to check).

**Comment by oleq** [comment]
I couldn't reproduce the upload/paste glitch and I [asked the issue author for more details](https://github.com/ckeditor/ckeditor5/issues/7548#issuecomment-662265194). 

In the meantime, this PR addresses not only the resizer glitch issue but also fixes the nasty `View#render()` loop when an image is selected, which could have other unidentified consequences in the editor.

**Pull request merged**
