### PR TITLE
Docs: fixing the snippet.

### LINKED ISSUE #15733: Docs issue report from "installation/getting-started/getting-and-setting-data.html"
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/getting-and-setting-data.html

### Project version

41.0.0

### Is the information outdated? How?

_No response_

### Is there something missing in the guide? What is it?

The PHP example is wrong. It seems the encoding charactes which should be shown in the documentation got encoded wrong. Now it shows exactly what should not happen.

### Is there anything else you would like to add?

_No response_

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0

### PR DESCRIPTION
**Pull request by godai78**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: fixing the snippet. Closes #15733

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Comment by gorzelinski** [comment]
I tried different methods of getting this worked, like this:

```html
<info-box>
  ```html
    // HTML entities
  \```
</info-box>
```
or

```html
<info-box>
  <pre><code> // HTML entities </code></pre>
</info-box>
```

etc.

No matter what, HTML entities are just rendered when they are inside of an info-box. Rendered snippets look the same.

Screenshot 2024-02-23 at 12 12 17

Because of that, I would advise to **avoid using code snippets inside info-boxes.** It can mess up the markup, and it adds unnecessary nesting.

In general, displaying HTML entities instead of rendering them in a markdown is [tricky](https://stackoverflow.com/questions/47982386/html-entities-in-markdown-block-code).

I've also just noticed that the info box messes up the PHP snippet. Replacing '&' with '&' doesn't make sense. 

Screenshot 2024-02-23 at 12 41 46

**Comment by godai78** [comment]
It actually works my way.  
  
 



But I think we may drop this infobox anyway and just have it as text.

**Comment by gorzelinski** [comment]
That's interesting... Hmm...
Still, as far as I see, the PHP snippet doesn't work as expected.

**Comment by gorzelinski** [comment]
The problem is a little tricky. I'll try to suggest a solution. Stay tuned.

**Comment by godai78** [comment]
This is after the infobox was dropped:

**Comment by godai78** [comment]
I'll push it and you can tak up from here.

**Comment by gorzelinski** [comment]
Now, it looks as it should. Probably.

**Review by gorzelinski — COMMENTED** [review]
Now, it looks as it should. Probably.

**Pull request merged**
