### PR TITLE
Improved performance of Differ#getChanges().

### LINKED ISSUE #8188: Formatting large content freezes the editor
## 📝 Provide detailed reproduction steps (if any)

1. Add some large content to editor ( I'm using the one from [pagination demo](https://ckeditor.com/docs/ckeditor5/latest/features/pagination.html#demo) )
2. Select all
3. Change font size/ apply bold / apply some other formatting

### ✔️ Expected result

Formatting happens immediately.

### ❌ Actual result

Editor freezes, sometimes for more than ~30 seconds:  
  
0_freeze1

## 📃 Other details

* Browser: Chrome, Firefox
* On Safari the freeze is almost unnoticeable
* CKEditor version: old issue, happens even on v15

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by niegowski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Other (engine): Improved performance of `Differ#getChanges()`. Closes #8188.

---

### Additional information

### CODE REVIEW

**Comment by niegowski** [comment]
Before this change `getChanges()` for a test content lasted for ~600ms but after this change, it lasts ~150ms.

@ckeditor/qa-team could you test it if you see performance improvement? Also, it never took more than 900ms for me so the case of 30s freeze is a mystery, could you try to find a case when it takes so long if it still happens?

**Comment by Reinmar** [comment]
@niegowski, could you provide more information about the change? What did you identify as slow and what did you do with it. It's hard to review without the context.

**Comment by niegowski** [comment]
> @niegowski, could you provide more information about the change? What did you identify as slow and what did you do with it. It's hard to review without the context.

I found out that in the case of the pagination demo content there is no need for post-fixing because the content is proper from the beginning (all post-fixers return `false` - they made no changes). While checking why it's taking so long (the one round of post-fixing) I noticed that the very first post-fixer is spending most of its time in `Differ#getChanges()` which took most of the time by itself so the long task was right inside `getChanges`. After putting performance tags between the biggest parts of that method I found that "gluing" changes were taking the biggest part of the method call time. It was iterating over a 26k diff entries and for every one of them that was glued with the previous one the merged entry was removed from the array (this was causing shifting elements in an array).

**Comment by FilipTokarski** [comment]
In manual test I got max ~500ms, on local docs max ~530ms.  In comparison, on `master` in manual test I got ~1.18s, the same on local docs. So there's definitely an noticeable improvement here 👍 
The only thing that bothers me, is that this very long freeze I reported, happens for me only on live docs.

**Comment by scofalik** [comment]
In my opinion the change is okay.  
  
@FilipTokarski

> The only thing that bothers me, is that this very long freeze I reported, happens for me only on live docs.

Considering this, do you see this issue as resolved or not? If yes, the PR can be merged.

**Comment by FilipTokarski** [comment]
The originally reported case is tricky, because it can only be reproduced on live docs. So I cannot state now with 100% certainty, whether it will fix the issue once it goes live.
OTOH, changes proposed by @niegowski improve the performance of this particular case quite substantially, when tested locally, so I think we can go with this.

**Comment by niegowski** [comment]
> The originally reported case is tricky, because it can only be reproduced on live docs. So I cannot state now with 100% certainty, whether it will fix the issue once it goes live.  
> OTOH, changes proposed by @niegowski improve the performance of this particular case quite substantially, when tested locally, so I think we can go with this.

I just tested it in live docs by replacing snippet (with Chrome Dev tools overrides) with the one built locally and it seems that some other performance improvement also helped there - it takes same time as in local docs.

**Pull request merged**
