### PR TITLE
Docs: nightly master fixes.

### PR DESCRIPTION
**Pull request by godai78**
Multiple fixes to `master` nightly docs, as listed in closing tickets below:

Closes: #9907 

Closes: #9908 

Closes: #9910 

Closes: #9912

Closes: #9913 

Closes: #9919

### CODE REVIEW

**Comment by FilipTokarski** [comment]
In Easy Image there are still some links that are broken

**Comment by FilipTokarski** [comment]
And if I'm allowed to be picky - shouldn't this css snippet be between `Check out the difference in the live demo below:` and `The demo below uses CSS to set up the fixed image aspect ratio...` ( and not after those two paragraphs ) ?
  
0_nightly8

**Comment by godai78** [comment]
Fixed links and rearranged the paragraphs / demos.

**Comment by FilipTokarski** [comment]
Just one last link in easy image:
0_nightly9

**Comment by FilipTokarski** [comment]
OK, bugs are fixed. No more comments from me, looks fine 👍

**Pull request merged**
