### PR TITLE
t/1520: Got rid of the symbol used to recognise view elements

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

CI constellation–only PR for #1520.

PRs:
* https://github.com/ckeditor/ckeditor5-link/pull/213
* https://github.com/ckeditor/ckeditor5-image/pull/275
* https://github.com/ckeditor/ckeditor5-media-embed/pull/76
* https://github.com/ckeditor/ckeditor5-table/pull/171
* https://github.com/ckeditor/ckeditor5-widget/pull/71

### CODE REVIEW

**Comment by Reinmar** [comment]
The changes look good. But I wonder if we should be more precise in checking whether something is some element. Like checking also that `<figure class=image>` not only has `image` class but also is a `figure`. WDYT?

**Comment by Reinmar** [comment]
Actually... I wonder if we can make it bulletproof in one case – when someone changes the output format of e.g. the image feature. That it's not a `figure` but something else. In fact, if someone does it – what else might break? If this is the only thing which might break, then it'd be worth considering doing this in a smarter way. We can't use symbols, but perhaps we could use something else.

**Comment by oleq** [comment]
Or

> * Fix the conversion so the custom props are preserved in this case. We may use them in the future for something else (not related to tag–symbols) and they will be broken anyway.

**Comment by Reinmar** [comment]
> Custom props are pruned when processed by the custom converter so links with `target` were no longer recognized as links. And if a link isn't a link... it does not trigger the balloon UI.

I'm sorry, but it seems I didn't get this. Can you elaborate?

**Comment by Reinmar** [comment]
Oh... I think I get it. The problem isn't "pruning" (like – literally removing things)... the problem is more complex.

When you have two converters which create two attribute elements and these attribute get merged (`<a href="x"><a target="y">foo</a></a>`), that merging logic does not care about custom props. It forgets about them. We could indeed fix that.

Still, using symbols was rather unnecessary. Plus, we weren't doing this consistently – we were doing this for a small percentage of identifiers. So the change to remove symbols, in general, would be good. But I'm not sure if we shouldn't just replace them with normal strings.

**Comment by Reinmar** [comment]
Or another option – expose symbols (e.g. on plugin instances) + fix the custom properties handling.

The goal, in all those cases, is to allow tinkering with features. So, to e.g. write a custom converters which define different view representation of a feature but still works with the UI.

**Comment by Reinmar** [comment]
Let's talk about this tomorrow. @pjasiun and @scofalik are for fixing custom props handling and not using symbols (but strings instead). I'm 👍 with that, but we need to talk about the details. Plus... explain somewhere why we made such a decision because, in general, it's not optimal but we don't have time now to make bigger changes here.

**Comment by oleq** [comment]
Replaced by the https://github.com/ckeditor/ckeditor5/pull/1532 constellation with a string approach.

**Pull request closed without merging**
