### PR TITLE
UI animations do not respect user's preferences on reduced motion

### PR DESCRIPTION
**Pull request by Mati365**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Internal: UI animations respect user's preferences on reduced motion.

---

### Tickets to close

Closes https://github.com/cksource/ckeditor5-commercial/issues/6030.
Related to https://github.com/cksource/ckeditor5-commercial/pull/6121

## Summary by CodeRabbit

- **Style**
	- Enhanced accessibility across various components by introducing media queries for reduced motion preferences, ensuring a comfortable viewing experience. Adjustments include disabling animations and transitions in image captions, to-do lists, minimaps, and UI elements.

### CODE REVIEW

**Comment by charlttsie** [comment]
## Animations are present when hovering over the "Insert paragraph before/after block" buttons
### Steps
1. Enable the "reduce motion" setting
2. Open e.g. [all-features.html](http://localhost:8125/ckeditor5/tests/manual/all-features.html)
3. Hover over an "Insert paragraph before/after block" button

### Result
The button animates:

https://github.com/ckeditor/ckeditor5/assets/132071257/1d8539cb-6873-44d7-b757-332cacb9f4ce

**Comment by charlttsie** [comment]
## Animation is present on when navigating back and forth between pages using pagination on Chrome and Safari
### Steps
1. Open e.g. [pagination.html](http://localhost:8125/ckeditor5/external/ckeditor5-commercial/packages/ckeditor5-pagination/tests/manual/pagination.html)
2. Use "Go to next page" and "Go to previous page" toolbar buttons to switch between pages

### Result
Animation is visible:

https://github.com/ckeditor/ckeditor5/assets/132071257/eaa78620-4e6b-437f-bc6e-5d6cc2264dca

### Additional info
On Firefox, the preference was respected before the changes and is still respected now

**Comment by charlttsie** [comment]
## Animations are present when switching between revisions in revision viewer
### Steps
1. Open e.g. [revision-history-classic.html](http://localhost:8125/ckeditor5/external/ckeditor5-commercial/packages/ckeditor5-revision-history/tests/manual/revision-history-classic.html)
2. Save a revision
3. Open RH viewer
4. Switch between revisions

### Steps
Tiles with revisions animate when clicking on them:

https://github.com/ckeditor/ckeditor5/assets/132071257/b1e0fb17-78d3-478c-92da-d37a698b70f3

**Comment by charlttsie** [comment]
## Animation is present when toggling image caption on
### Steps
1. Enable the "reduce motion" setting
2. Open e.g. [all-features.html](http://localhost:8125/ckeditor5/tests/manual/all-features.html)
3. Toggle image caption on 

### Result
There's a color transition animation inside the image caption textbox:

https://github.com/ckeditor/ckeditor5/assets/132071257/58605519-fca6-4600-ba6b-54346b7cd3b3

**Comment by charlttsie** [comment]
@Mati365 We've completed the testing of the PR with @kubaklatt and @mabryl and have identified a few areas where animations are still present, even when the 'reduced motion' setting is activated. All of these have been reported above. Please let us know if a retest is needed 🙂

**Comment by charlttsie** [comment]
@Mati365 
It looks like this animation: https://github.com/ckeditor/ckeditor5/pull/16099#issuecomment-2068690840 is still visible after the fixes.

**Comment by Mati365** [comment]
@charlttsie Hm, weird. I was checking it on my Chrome instant and it was working as expected. Anyway, please ignore it for now, we will discuss if this particular place needs to be changed at all.

**Comment by mabryl** [comment]
## Animation visible when hovering over colors in the color grid

### Steps to repro
1. Use a feature that utilizes the color grid (e.g. Font Color)
2. Hover over a couple different colors

### Result
Notice the blue border that appears around the colors:

https://github.com/ckeditor/ckeditor5/assets/72079603/d8b81e54-5e93-4823-ae06-e32e77519e68

**Comment by charlttsie** [comment]
We've re-tested the PR with @mabryl and @kubaklatt. Besides the case when switching pages, all the previously indicated animations are no longer visible when the preference for reduced motion is enabled. However, there's also one new case reported above by @mabryl, with animation present when hovering over colors. Other than that, the PR looks good 👍

**Comment by Mati365** [comment]
@mabryl Fixed, can you test again? Please pull both branches (commercial and public)

**Comment by mabryl** [comment]
@Mati365 just did a quick retest and I can confirm that the specific issue with the color grid is now fixed.

**Pull request merged**
