### PR TITLE
Changed the default position of the powered by logo to over-the-border.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Internal (ui): Changed the default position of the powered by logo to over-the-border. Closes https://github.com/cksource/ckeditor5-internal/issues/3284.

### CODE REVIEW

**Comment by mlewand** [comment]
Pushed a branch with latest `release` branch merged (to include #14148).

**Review by mlewand — APPROVED** [review]
Looks good 👍

Things I missed:

*   reflecting the default value change in API docs (fixed in bd3b61b).
*   using faked timers in unit tests - but that's an issue for entire test suite so let's deal with it in a separate PR because we're running short on time here.

**Comment by oleq** [comment]
> The tag is slightly misaligned on crappy non-hidpi screens (disclaimer, text looks very blurry on images - it doesn't look that blurry on real device - don't know why):

Addressed in [38dd2fb](https://github.com/ckeditor/ckeditor5/pull/14152/commits/38dd2fbf009f991ad0d7defb99eb0ba26d421504).

**Comment by mlewand** [comment]
Awesome, looks good in device pixel ratio 2.5x:



and dpr = 1x

**Pull request merged**
