### PR TITLE
Ck/12125 dropdown focus

### LINKED ISSUE #12121: Editor loses focus when selecting from the special-characters dropdown.
## 📝 Provide detailed reproduction steps (if any)

1.  Start the docs server.
2. Open special characters feature guide: http://127.0.0.1:8080/ckeditor5/latest/features/special-characters.html#demo.
3. Focus something inside the editor and focus toolbar (option/alt+f10).
4. Go to the special-characters button. Press arrow_down, select anything from the dropdown.

### ✔️ Expected result

Focus is back on the dropdown.

### ❌ Actual result

https://user-images.githubusercontent.com/11699569/180229022-6d69c740-f04f-4a86-8f0d-a25059afaade.mp4

## 📃 Other details

This cannot be replicated in https://ckeditor.com/docs/ckeditor5/latest/features/special-characters.html#demo.
The document.activeElement after the provided steps is `<body>`.
Same outcome can be achieved when using mouse.

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #12125: Editor loses focus after using styles dropdown
## 📝 Provide detailed reproduction steps (if any)

1.  Open a sample with styles dropdown feature.
2.  Focus somewhere in the editor.
3.  Use the styles dropdown to set a style.

### ✔️ Expected result

After the style is set, the focus should be back in the editor.

### ❌ Actual result

The focus is not back, I cannot type.

## 📃 Other details

This is a regression. Possibly connected with recent a11y changes?

### PR DESCRIPTION
**Pull request by Dumluregn**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Internal: Dropdown will move focus to the button after an option is picked from the list. Closes #12125. Closes #12121.

---

### Additional information

See the details in https://github.com/ckeditor/ckeditor5/issues/12125#issuecomment-1197865322.

### CODE REVIEW

**Comment by Dumluregn** [comment]
@ckeditor/qa-team Hi, please take a look at this PR and ensure it doesn't introduce some regressions.

**Comment by Mgsy** [comment]
I've tested it in all browsers with different editor types and haven't found any issue.

**Comment by mlewand** [comment]
Seems that unit tests are failing for:

```
🔥 Errors were detected by the CI.
The following packages did not pass unit tests: style, ui
```

Per https://app.travis-ci.com/github/ckeditor/ckeditor5/jobs/577951169

**Comment by mlewand** [comment]
Let's do a final QA testing, that includes:

*   CF features
*   iOS
*   Strong focus on split buttons.

The CKE5 itself has been already well covered by @Mgsy so he don't need to do this particular part that much (contrary to @FilipTokarski 😈).

Let's test `focus-release-hot-fixes` branch that contains both fixes (#12134, #12162).

**Comment by Mgsy** [comment]
## Steps to reproduce

1.  Open the editor with the grouped toolbar.
2.  Open the grouped toolbar and click on some icon to trigger `execute` event.

## Current result

*   The focus moves on the grouped toolbar icon.
*   The focus moves to the editable.
*   There are two visible focuses.
*   It's possible to type on desktop, but it breaks mobiles.

**Review by FilipTokarski — APPROVED** [review]

**Review by Mgsy — APPROVED** [review]

**Comment by Dumluregn** [comment]
Extracted [https://github.com/ckeditor/ckeditor5/pull/12162#issuecomment-1198063996](https://github.com/ckeditor/ckeditor5/pull/12162#issuecomment-1198063996) to #12178.

**Pull request merged**
