### PR TITLE
Provide more context to block formatting function. Update tests.

### LINKED ISSUE #8633: Autoformat creates code block when typing in bulleted/numbered lists
## 📝 Provide detailed reproduction steps (if any)

1.  Create a bulleted/numbered list (from the toolbar or using `1.` / `*` ).
2.  Type ` ``` `.

### ✔️ Expected result

The list has an item with three grave accents.

### ❌ Actual result

The item gets removed and a code block is inserted below.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by maxbarnas**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (autoformat): Code block characters inside a list will not trigger autoformatting. Closes #8633.

### CODE REVIEW

**Review by niegowski — COMMENTED** [review]
I’m not sure if this issue is valid, it seems that the behavior described in the issue is an expected one - I checked how this works in Notion and in Slack and it’s the same as current implementation - while typing ``` inside the list item - it’s converted to the code block. Maybe we should only update tests to reflect the real behavior?

**Comment by Reinmar** [comment]
I agree with Kuba.

**Comment by maxbarnas** [comment]
Issue is not valid anymore.

**Comment by maxbarnas** [comment]
Currently, the autoformatting feature works as expected after all.

**Pull request closed without merging**
