### PR TITLE
Fix code style & CKEditorError messages

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Internal: Fix various issues with `CKEditor` error messages JSDoc comments. See #7822.

---

### Additional information

*   I've found many missing `@error` annotations and/or invalid ones.

### CODE REVIEW

**Comment by jodator** [comment]
Since we've agreed to disable rule for specific cases (mostly when error is defined in other file) this must be re-check after release of CKEditor ESLint plugin from dev.

**Comment by jodator** [comment]
And once it is released I must fix the tests as some expects old format.

**Comment by pomek** [comment]
> And once it is released I must fix the tests as some expects old format.

@jodator, done.

- https://github.com/ckeditor/eslint-config-ckeditor5/releases/tag/v3.1.0
- https://github.com/ckeditor/eslint-plugin-ckeditor5-rules/releases/tag/v1.1.0

**Comment by jodator** [comment]
@pomek I think that I've caught and fixed everything here.

**Review by pomek — APPROVED** [review]
LGTM.

**Pull request merged**
