### PR TITLE
Upgrade dependencies

### LINKED ISSUE #1203: Update dependencies
Cause dev deps are red: https://david-dm.org/ckeditor/ckeditor5?type=dev

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Internal: Upgraded dev-dependencies. Closes #1203.

---

### Additional information

* branch `#t/ckeditor5/1203` in all packages should be merged too:
  * Changes in packages: https://github.com/ckeditor/ckeditor5-engine/compare/master...t/ckeditor5/1203
  * Changes in builds: https://github.com/ckeditor/ckeditor5-build-classic/compare/master...t/ckeditor5/1203

```bash
mgit fetch && mgit co t/ckeditor5/1203 && mgit co master && mgit merge t/ckeditor5/1203 -- -m 'Internal: Upgraded dependencies. See ckeditor/ckeditor5#1203.' && mgit push
```

* ~2a80aca and 38cec00 need to be reverted before merging~

### CODE REVIEW

**Comment by pomek** [comment]
[CKEditor 5](https://travis-ci.org/ckeditor/ckeditor5/builds/425159943) and [CKEditor 5-dev](https://travis-ci.org/ckeditor/ckeditor5-dev/builds/425164956) are fine.

**Comment by pomek** [comment]
Almost everything:

image

So I'm reverting lerna's changes.

**Comment by Reinmar** [comment]
I actually tried to upgrade to lerna@3 myself and I knew it caused some issues (although, I stumbled upon something else than you).

**Comment by pomek** [comment]
`lerna@^2` produces the same directories.

Lerna 3 changes some things in configuration (`lerna init` resolves problems) and on CI I needed to add `--no-ci` option because of the missing `package-lock.json` file that caused other problems.

Docs worked, samples in the docs as well. I didn't check the builds.

**Comment by pomek** [comment]
After reverting lerna's changes, ckeditor5-dev does not require any changes.

**Comment by Reinmar** [comment]
> After reverting lerna's changes, ckeditor5-dev does not require any changes.

There are packages in ckeditor5-dev that we should upgrade now. For instance:

image

And there are more in ckeditor5-dev that require updates. We should keep them in sync with what we use in ckeditor5 to avoid problems like – `postcss-loader` works when you run tests, but fails when you try to rebuild the editor (because a different version is used).

**Pull request merged**
