### PR TITLE
#8591: Inline images guide

### LINKED ISSUE #8591: Inline images - Feature guide
Create a feature guide for inline images.
Add a mention in the image guide.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs: Inline images guide. Closes #8591.

---

### Additional information

TODOs as of a0f4e00:

*   [x] Obvious TODOs in the content and broken links :P
*   [x] Links to builds in docs in the table `features/images/images-overview.html#image-features` are missing. Maybe the plugins should also be linked?
    *   [x] This sort of comes down to changes in the list that precedes the table: plugin names should not be used here at all but natural language links to sub-feature guides.
*   [x] Better images in the demo `features/images/images-text-alternative.html`
*   [ ] The resizing images guide is block image-centric. Both contents in demos and code snippets should include inline images `features/images/images-resizing.html`
*   [ ] Magda knows what to do with the image style guide `features/images/images-styles.html`
*   [x] The linking images guide is block image-centric. Missing inline images in demo content and in code snippets `features/images/images-linking.html`
*   [x] A cross-links to the migration guide is necessary in the "inline vs. block" section `/features/images/images-installation.html#inline-and-block-images`
*   [x] Image upload overview should backlink to images overview somewhere at the beginning `features/images/image-upload/image-upload.html`
*   [ ] An entry in `builds/guides/whats-new.html` :P (just kidding)

### CODE REVIEW

**Comment by godai78** [comment]
What's wrong with the text alternative images? Both block and inline are present and all of them have text alts.

**Comment by godai78** [comment]
W should have image URL pasting in the image upload demo.

**Comment by godai78** [comment]
By the way, we should replace the "What's new?" section with something like "Main features" or so, as this is very much "new compared to what" now and every day more so.

**Comment by oleq** [comment]
> What's wrong with the text alternative images? Both block and inline are present and all of them have text alts.

They should be aesthetically pleasing but the shot of the river falls short (composition & quality).

**Comment by godai78** [comment]
If we use caption on an inline image it basically breaks the whole layout.

**Pull request merged**
