### PR TITLE
i/5696: Enabled style linter

### LINKED ISSUE #5696: Enable style linter
## Provide a description of the task

The more we develop our CSS the more often I stumble upon obvious bugs like typos, formatting or specificity issues. It's annoying and makes it hard to maintain the code base. Like @dkonopka mentioned years ago, we need https://github.com/stylelint/stylelint and I'm about to enable it.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Internal: Enabled style linter in the project. Closes #5696.

---

### Additional information

Requires https://github.com/ckeditor/ckeditor5-dev/issues/575.

**This PR requires changes in all editor packages. They are in the `i/5696` branch of each respective package.** 

I figured creating 49 PRs is madness and I simply pushed the branches to the remote. 

**Note that these branches also contain the changes to the CSS files to let the linter pass.** They should be thoroughly reviewed. You can find them:

```
mrgit exec 'git diff --stat master' | grep css
```

### CODE REVIEW

**Comment by pomek** [comment]
Could we execute `yarn run stylelint` on our CI? (https://github.com/ckeditor/ckeditor5-dev/blob/586d2720496dfa8cbb25fe0488cd76901a7c3360/packages/ckeditor5-dev-tests/bin/test-travis.sh#L18)

**Comment by Reinmar** [comment]
@dkonopka, any chance that you take a look at this?

**Comment by dkonopka** [comment]
@Reinmar on my to-do list thu/fri 👍

**Comment by dkonopka** [comment]
@oleq 

Missing conf file, I guess?

```
yarn run stylelint 
yarn run v1.12.3
$ stylelint --quiet 'packages/**/*.css' 'docs/**/*.css'
Error: No configuration provided for /Users/damiankonopka/dev/ckeditor5/docs/assets/snippet-styles.css
    at module.exports (/Users/damiankonopka/dev/ckeditor5/node_modules/stylelint/lib/utils/configurationError.js:8:27)
```

**Comment by oleq** [comment]
I figured it will be for the best if we have the shared configuration in a dedicated package (like with ESLint). So first we need to merge and release https://github.com/ckeditor/ckeditor5-dev/issues/575.

**Comment by pomek** [comment]
I've just published the package – https://www.npmjs.com/package/stylelint-config-ckeditor5.

**Comment by mlewand** [comment]
> * [ckeditor/ckeditor5-theme-lark@bf4aa58](https://github.com/ckeditor/ckeditor5-theme-lark/commit/bf4aa58ddc46d05230a39ac7dddba3c116aff2a3) - I removed some redundant stylelint disable directives

After [merging latest master](https://github.com/ckeditor/ckeditor5-theme-lark/commit/6d2b47243520700349bba22b1de324d22e0bc1d0) branch into `i/5696`, errors with order are back:

```
packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/button/button.css
 120:3  ×  Expected selector ".ck.ck-button.ck-button_with-keystroke .ck-button__label" to come before selector "a.ck.ck-button.ck-disabled .ck-button__label"   no-descending-specificity
 125:2  ×  Expected selector ".ck.ck-button .ck-button__keystroke" to come before selector ".ck.ck-button.ck-disabled .ck-button__keystroke"                     no-descending-specificity
 125:2  ×  Expected selector ".ck.ck-button .ck-button__keystroke" to come before selector "a.ck.ck-button.ck-disabled .ck-button__keystroke"                    no-descending-specificity
 125:2  ×  Expected selector "a.ck.ck-button .ck-button__keystroke" to come before selector ".ck.ck-button.ck-disabled .ck-button__keystroke"                    no-descending-specificity
 125:2  ×  Expected selector "a.ck.ck-button .ck-button__keystroke" to come before selector "a.ck.ck-button.ck-disabled .ck-button__keystroke"                   no-descending-specificity
```
I'll try to quickly handle these and push fix into the branch.

**Comment by mlewand** [comment]
Solved the above in https://github.com/ckeditor/ckeditor5-theme-lark/commit/20ffb4b109583c440737103d0689c33bc7cfa677 and https://github.com/ckeditor/ckeditor5-theme-lark/commit/80eea1b74327bd1695ae8757cd8446dda134e361.

**Comment by mlewand** [comment]
All right I have merged branches with CSS changes in all our branches.

The only thing remaining here is to resolve yarnlock conflicts and we're good to go.

**Comment by pomek** [comment]
> All right I have merged branches with CSS changes in all our branches.

It's enough for me. Thanks.

**Pull request merged**
