### PR TITLE
Provided the changelog in CKEditor 5 docs.

### PR DESCRIPTION
**Pull request by przemyslaw-zan**
Docs: Provided dynamic changelog in CKEditor 5 docs updating section.

Closes: cksource/ckeditor5-internal#1611

### CODE REVIEW

**Comment by pomek** [comment]
Saving for the future:

```js
module.exports = function insertChangelog( version ) {
	const changes = getChangesForVersion( version );

	if ( !changes ) {
		return null;
	}

	return (
		'<details>' +
			`<summary>Changelog for ${ version }</summary>` +
			`\n\n${ changes }\n\n` +
		'</details>'
	);
};
```

**Comment by godai78** [comment]
Can we strip the icons?

**Comment by przemyslaw-zan** [comment]
We can. The [ℹ️](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/versioning-policy.html#major-and-minor-breaking-changes) emoji currently serves as a link to [versioning policy guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/versioning-policy.html#major-and-minor-breaking-changes) - do we want to keep that link somewhere, or do we remove it entirely?

**Comment by godai78** [comment]
I don't think we need to as much in this guide. But we may consider adding a link in the lead paragraph.

**Review by pomek — APPROVED** [review]
LGTM.

**Pull request merged**
