### PR TITLE
[Bookmark] Update mobile look of balloon views in bookmarks.

### PR DESCRIPTION
**Pull request by pszczesniak**
Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Internal: Should bookmark balloons looks good on mobile devices.

---

### Additional information

_We've got a green light 🟢  from @dwandeljanicka _

### CODE REVIEW

**Review by mmotyczynska — COMMENTED** [review]
I'd think about removing the tooltip from the button (or position it differently if it's possible) because it:
- covers two other buttons
- If you click on it (and it's quite easy to do so by accident), the balloon closes and you have to open it again.

But I don't know about the a11y in this case 🤔 
image

**Comment by pszczesniak** [comment]
@mmotyczynska very same case is with link:



But not in 100% the same.

:thinking: 

Yes, will style it exactly like in link.

**Comment by pszczesniak** [comment]
@mmotyczynska done.

**Review by mmotyczynska — APPROVED** [review]
Looks a bit better. At least we keep consistency in `link` and `bookmark` 👍

**Comment by pszczesniak** [comment]
I've updated also the look of the submit button on mobiles, to make it align with look for example of "Find and replace" (especially the margins and paddings).

Find and replace (mobile):



Bookmark (mobile):

**Pull request merged**
