### PR TITLE
Updated favicons for documentation pages.

### PR DESCRIPTION
**Pull request by pszczesniak**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: Unify favicons between websites.

---

### Additional information

See: https://github.com/cksource/nova-ckeditor.com/issues/2914

### CODE REVIEW

**Review by godai78 — APPROVED** [review]
Well these work as they should.  
  
A notice, tho - we have a backdropless icon on the main docs landing site. Is this difference intended?  
  
On a side note, we should also update the top bar left-hand image, probably.

**Comment by pszczesniak** [comment]
> Well these work as they should.

:+1: (it was just a small request from website team)

> A notice, tho - we have a backdropless icon on the main docs landing site. Is this difference intended?

Dunno where to change it :shrug: 

> On a side note, we should also update the top bar left-hand image, probably.

follow-up?

**Comment by godai78** [comment]
I can update the main landing site icon if this is the proper one. Shouldn't we merge it into `stable`?  
  
As for follow up, I believe there's a plan to remove the top-left icon in bar in the redesign, so we need to decide on ROI.

**Comment by pszczesniak** [comment]
Changed target branch to `stable` - moved here :point\_right: #16270

**Pull request closed without merging**
