### PR TITLE
Docs: Create a reconversion guide

### LINKED ISSUE #8174: Create reconversion guide
## 📝 Provide a description of requested docs changes

We need a guide for the new reconversion concepts by covering cases from https://github.com/ckeditor/ckeditor5/issues/7956#issuecomment-694241558.

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs (engine): Create a reconversion guide. Closes #8174.

---

### Additional information

*   I've rewritten the sample several times and I think that the current content example is useful.
*   The general idea is to have two parts of the guide:
    1.  introduction to reconversion and reconversion concepts
    2.  an example with _the most_ relevant code is explained (the rest is in the full source code)

### TODO:

*   [x] The initial section about the reconversion needs expanding.
*   [x] The example implementation needs closure with a full code.

### CODE REVIEW

**Review by godai78 — APPROVED** [review]
I hereby approve this deep-dive guide to be worthy enough to join the great documents family. Providing the code is provided at the end.

**Comment by jodator** [comment]
OK, I've pimped-out the demo slightly (UI button to insert a card).  
The code was added at the end and code examples were updated accordingly.

**Comment by AnnaTomanek** [comment]
I fixed a few things here and there, including a [leftover `ComplexInfoBox`](https://github.com/ckeditor/ckeditor5/pull/8380/commits/073e50ff185e5b385b4ab9c282e963d3dee5bdf2#diff-7205af0430a9b5d0bc745ff87a7cf2937ad90e28b525cc838908b2d7f768ba2fR202) model element and some `paragrahp`s :wink:  Good job overall!

Things that we could still consider adding (although they can also be added as a later update):

*   Replacing the yummy lorem ipsum with some real text (@godai78, any ideas?)
*   Adding some "Next steps" section (or another form) with links to some other conversion guides (if it still makes sense) - our users do not always read the docs like a book, one after another, they will land here e.g. directly from the blog post.
*   Adding the "select all" or whatever it is called UI element to the card that would allow you to select it and delete - now it's a bit counter-intuitive that you can add it and it's not really clear what you need to click to select it.

**Review by AnnaTomanek — APPROVED** [review]
Looks great - thanks for the tutorial, @jodator, and kudos for the demo content, @godai78 👏

**Pull request merged**
