### PR TITLE
Fix sticky cursor resulting in reverse typing if the editable is not the activeElement in the document.

### LINKED ISSUE #15182: "Reverse typing" effect in some instances where selection may have been lost
## 📝 Provide detailed reproduction steps (if any)

Hi, I'm building off of these bugs here, as the problem still persists:
1. https://github.com/ckeditor/ckeditor5/issues/13926#issuecomment-1761548452
2. https://github.com/ckeditor/ckeditor5/issues/14702#issuecomment-1660318476

For some background information, the original issue was first presented and solved in this bug: 
* https://github.com/ckeditor/ckeditor5/issues/14569

This "reverse typing" effect unfortunately has many causes and manifestations which eventually lead to the same effect. The original bug #14569 had intended to solve the issue where selection was not updated in time due to heavy CPU usage while user was typing. This caused some reverse typing as the cursor would "stick" at the current selection, and not update. 

This had been fixed with the PR: #14648 - https://github.com/ckeditor/ckeditor5/pull/14648 

This fix has worked quite well.

Now, we run into issues where if the editor is somehow taken out of focus in a "forceful" manner, typing will result in a reverse order due to the cursor never updating its position.

For example, one can synthetically reproduce this by running this piece of JavaScript code while the cursor is within the editor:

```js
// In 5 seconds, this will cause reverse typing
setTimeout(() => {
  const editable = document.querySelector("div.ck-editor__editable");
  editable.dispatchEvent(new FocusEvent("blur"));

  console.log("Now, try to type!");
}, 5000);
```
backwards

### ✔️ Expected result

Typing should never result in characters being visually placed in reverse order when the editor is not truly in focus.

### ❌ Actual result

Typing results in characters being injected in reversed order.

### ❓ Possible solution

To get around this, what we can do as integrators is actually listen in on the `beforeinput` event on the `ViewDocument`, at the `low` event priority. There's an interesting behavior that happens in this event, upon typing, if we _manually dispatch_ a new `FocusEvent` with `focus` to the editable, the selection is restored. 

For example:

```js
editor.editing.view.document.on('beforeinput', () => {
  const editable = getEditableHelper(editor);
  editable.dispatchEvent(new FocusEvent("focus"));
});
```

Or building off our synthetic repro example as a demonstration:

```js
setTimeout(() => {
  const editable = document.querySelector("div.ck-editor__editable");
  editable.dispatchEvent(new FocusEvent("blur"));

  console.log("Now, try to type!");
  
  // In 3 seconds, there will be normal typing
  setTimeout(() => {
      editable.dispatchEvent(new FocusEvent("focus"));
      console.log("Now, we are typing normally again.");
  }, 3000);
}, 5000);
```

Though this is a known workaround, for this specific scenario, I wonder what happens if some _focus stealing_ of some other DOM element occurs, while the cursor is active in the inline editor will result in? For sure it's going to be reverse typing, but there are times where a specific JS library plays bad and maintains/traps focus no matter what. 

The fact is that there is a cursor in the editable indicating that it is "focused" while it is not which is the tricky aspect to this all. I think if the editor truly does not have focus, it should not have a cursor. That's one scenario solved... maybe???? 🤔

## 📃 Other details
This happens in Chromium based browsers, Safari, etc. 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by urbanspr1nter**
This PR attempts to fix an issue with cases where "reverse typing" effect still occurs. This is caused by a selection not being updated when an input event occurs. The selection seems to not be updated because the `document.activeElement` in DOM is not the correct element. 

There are cases where the editable visually looks focused, but in reality the active element is some other element as it may have stole focus while the editable was active at some point. This can be caused by a manual dispatch of a `blur` event for example. 

We can actually simulate it like this:
```js
setTimeout(() => { 
	const editable = document.querySelector("div[contenteditable=true]");
	editable.dispatchEvent(new FocusEvent("blur"));

	console.log("BLUR!")
}, 5000);
```

If the editable is currently in focus, but the `blur` happens later, the active element in the `document` is not updated properly, and can end up having a selection which is out of sync with the characters being rendered into the editable. (It just sticks and never moves forward).

An example: 
274956696-3bd80cd7-cf19-4776-ab76-d1a026b4dd5f

Something like this can also be seen in the Safari web browser where a a `button` click can cause the issue to occur:
257527157-b3218162-a52b-453b-b0e5-9263952871ec
[Source](https://github.com/ckeditor/ckeditor5/issues/14702#issuecomment-1660318476)

After fix:
fix

Browsers tested on web (manual):
* Google Chrome
* Safari
* Firefox

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Type: (engine): Force the editable to be focused if the active element is not the editable when an input event occurs. Closes #15182, #14702 .

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Comment by urbanspr1nter** [comment]
Thoughts on this?

**Comment by Witoso** [comment]
@urbanspr1nter thanks for the PR, and sorry for the late reply. A bit hectic down here :blush:  @niegowski will soon take a look at a couple of problems regarding typing. We will take a look at this as well!

**Comment by Witoso** [comment]
Hey @urbanspr1nter, we prepared a separate PR, as we are merging all typing improvements PRs to one branch. Thanks for the contribution, we used your solution but placed it in a slightly different place. Check #16267 for details. :)

**Comment by urbanspr1nter** [comment]
Thanks! Of course, I'll always leave it to the experts. :)

**Pull request closed without merging**
