### PR TITLE
Docs: styles dropdown guide

### LINKED ISSUE #11331: [Styles dropdown] Create the feature guide
- We can take some inspiration from a CKE4’s guide for the Styles combo.
- Let’s have the minimum content for now:
    - E.g. “This feature allows you apply classes to existing elements in the content”
    - “This is how you configure it”
    - “This is how it looks”
- Meaningful example content
- Reasonable style examples
    - Block
        - Colored headings
        - Something for paragraphs too (e.g. callout?)
    - Object
        - Some table styles?
    - Inline
        - kbd, del, ins?
        - some “pill-like” style
- Inspiration:
    - Wikipedia
    - Blogs
    - Large documentation systems

### PR DESCRIPTION
**Pull request by godai78**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs: Styles dropdown guide. Closes #11331.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Comment by oleq** [comment]
I pushed some fancy content to the guide

**Comment by oleq** [comment]
I guess we're good to go.

**Comment by Reinmar** [comment]
I'm ok with merging this to the `release` branch and officially covering this feature in the upcoming release.

However, we'd need to add it to Online builder in this release. @pomek, can you handle it now, taken the last minute nature of this decision?

PS. I removed the "experimental" note in the feature guide. We polished it in the meantime.

**Comment by Reinmar** [comment]
@godai78, you merged it to `master`. It was supposed to be merged to `release`. I'll try cherry-pick it there.

**Comment by Reinmar** [comment]
This entire PR needs to be reverted: #12135.

**Comment by Reinmar** [comment]
Merged to the correct branch in #12136.

It took me a while to figure out what happened here. It turned out that I merged `release` to this branch but I didn't change the target branch here in this PR. @godai78, tip for the future: check the contents of the branch just before the merge – the 400+ touched files would probably hint you that I screwed something.

**Comment by godai78** [comment]
I'll double-check next time. The number of files didn't seem off after such a long wait and so many merges, sorry.

**Pull request merged**
