### PR TITLE
Resolve symlinks before passing paths to the watcher.

### LINKED ISSUE #53: Workaround the issue with watcher
In #45 I faced a bug in chokidar – it ignores changes in symlinked directories.

### PR DESCRIPTION
**Pull request by Reinmar**
Fixes #53.

### CODE REVIEW

**Comment by pjasiun** [comment]
Watcher stop working with the first error in the watching file.

**Comment by Reinmar** [comment]
Not a part of this ticket, but without it this watcher will not be functional... so OK :P.

**Comment by Reinmar** [comment]
Back on review.

**Comment by pjasiun** [comment]
Works file. Watcher even react on new files, so R+.

**Pull request merged**
