### PR TITLE
Fix unexpected behavior in splitting cells in certain tables

### PR DESCRIPTION
**Pull request by Mati365**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (table): Horizontal split button no longer splits larger table cell spans into more than two parts. Closes https://github.com/ckeditor/ckeditor5/issues/14658.

---

### Additional information

**Before fix**

https://github.com/user-attachments/assets/01df2845-3cae-48ae-81d7-d0120f39e11f

**After fix**

https://github.com/user-attachments/assets/3b1072d5-73a6-4fe4-9600-3b119eab081f

### CODE REVIEW

**Comment by Mati365** [comment]
Tested by QA, [no regressions](https://cksource.slack.com/archives/C079QQ1ASRJ/p1721222770916779?thread_ts=1721122430.107649&cid=C079QQ1ASRJ).

**Review by niegowski — CHANGES_REQUESTED** [review]
I'd suggest adding additional test for the original issue as it states about additional columns:
> The cell splits into multiple ones. The structure of the table is further altered and an additional column gets inserted on the right

**Comment by Mati365** [comment]
@niegowski Ok 👍🏻

**Comment by Mati365** [comment]
@niegowski I added missing test https://github.com/ckeditor/ckeditor5/pull/16733/files#diff-2740fa3a0238a03b01f07a7e4f30276468e98fc43d368424925a69dbd3df9dddR1069 . It should reflect table from issue.

**Review by niegowski — APPROVED** [review]

**Pull request merged**
