### PR TITLE
Docs: links to QS from examples; source code.

### PR DESCRIPTION
**Pull request by godai78**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs: Adding Quick Start guide links to Examples. 

Docs: Adding HTML source to Examples.

---

### Additional information

This addresses in part (but not necessarily closes) the following issue: #625

### CODE REVIEW

**Comment by Reinmar** [comment]
As I mentioned f2f, I don't feel like the right person to review this PR. I'd rather check it within the CCX team.

My 2 cents though on what could be checked/improved:

*   Ideally, the code of examples should be well separated from the demo itself, to avoid visual clutter. Not everyone is interested in the code itself too (all less technical people checking the docs). Alternatively, the entire source code section could be in something like `<details>`.
*   All examples should look identical in the :point\_up: aspect.
*   All examples should have the Source code section. Therefore the PR requires additional thought and work to cover more complex examples. E.g. the Source code in the inline editor example is incorrect.
    *   In fact, for the above reason, I have some doubts regarding copy-pasting the examples source code to the guide. The source code will not be tested and if we change something in an example itself, we need to update the source code too. And test.
*   We have some new examples today that require to be covered now.
*   Please remember about correct indentation in code examples. [https://github.com/ckeditor/ckeditor5/pull/10385/files#diff-6c17c8417baae8a66cd75ad31cd3a4f16b03d55abe8f040b558b76a8bb6d3c69](https://github.com/ckeditor/ckeditor5/pull/10385/files#diff-6c17c8417baae8a66cd75ad31cd3a4f16b03d55abe8f040b558b76a8bb6d3c69) has the \<div> and \<script> indented differently.
*   If we'll keep the source code in the MD files like it was proposed... someone has to test these examples.

**Review by Reinmar — CHANGES_REQUESTED** [review]
As commented.

**Comment by Reinmar** [comment]
I'd seriously consider giving this problem more thought and involving the Devops team to think how to create these examples in a safer way to resolve the issues that I mentioned.

**Comment by godai78** [comment]
Deprecated and closed in favor of: #11860

**Pull request closed without merging**
