### PR TITLE
Insert Image (via URL) toolbar dropdown tooltip updated

### LINKED ISSUE #11896: JAWS: Insert Image (via URL) toolbar dropdown button is not labelled
## 📝 Provide detailed reproduction steps (if any)

1.  Go to https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/images-inserting.html.
2.  Start JAWS, use CTRL+Insert+C to get the available list of dropdowns.

### ✔️ Expected result

The image toolbar dropdown is labelled properly.

### ❌ Actual result

The image toolbar dropdown is labelled as "Unlabeled 1".

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by mateuszzagorski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (ui): Updated the label for the insert image split button's down arrow. Closes #11896.

---

### Additional information

Following the suggestion from the [comment](https://github.com/ckeditor/ckeditor5/issues/11896#issuecomment-1156518322) updated the label to: _"Insert image via URL"._

### CODE REVIEW

**Comment by oleq** [comment]
Looks like this issue has already been addressed in https://github.com/ckeditor/ckeditor5/pull/11859/files.

I checked in JAWS and it looks correct to me on master:

Screenshot 2022-07-05 at 15 12 03

Can you confirm this @mateuszzagorski and close the PR+issue?

**Review by oleq — COMMENTED** [review]
Looks like this issue has already been addressed in https://github.com/ckeditor/ckeditor5/pull/11859/files.

I checked in JAWS and it looks correct to me on master:

Screenshot 2022-07-05 at 15 12 03

Can you confirm this @mateuszzagorski and close the PR+issue?

**Comment by mateuszzagorski** [comment]
@oleq yes this was partially covered by the https://github.com/ckeditor/ckeditor5/pull/11859/files change. However Marek's comment https://github.com/ckeditor/ckeditor5/issues/11896#issuecomment-1156518322 suggested to customize this particular dropdown label, changing it from the current "_Insert image_" to: "_Insert image via URL_".

I'm happy to close it if you would confirm that it's not a necessary change.

**Comment by mateuszzagorski** [comment]
@oleq  as discussed, I've reverted previous changes, leaving only the added test.

**Pull request merged**
