### PR TITLE
Enabled toolbar focusing and cycling across all editors and features

### LINKED ISSUE #9906: View/edit source is not global focus tracker friendly
## 📝 Provide detailed reproduction steps (if any)

1. Add view source editing to toolbar
2. Switch to editing source
3. editor.ui.focusTracker change:isFocused is called with isFocused false.

### ✔️ Expected result

editor.ui.focusTracker is a global focus tracker, as far as its concern, editor is still focused when it's in source edit mode.

Also, focus and blur of the editor UI in this mode should also emit change:isFocused on focusTracker

### ❌ Actual result

focusTracker change:isFocused should not be called. and isFocused should be true.

## 📃 Other details

* Browser: Edge Chromium Version 91.0.864.41 (Official build) (x86_64)
* OS: macOS Big Sur 11.4
* First affected CKEditor version: 28.0.0
* Installed CKEditor plugins: @ckeditor/ckeditor5-source-editing

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #10025: The toolbar is not floating above the editor in the source editing mode
## 📝 Provide detailed reproduction steps (if any)

1.  http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/features/source-editing.html
2.  scroll the page until the toolbar is floating
3.  switch to source editing mode

### ✔️ Expected result

The toolbar is still floating above the textarea

### ❌ Actual result

The toolbar is not floating and is static above the textarea. 

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #10368: It's impossible to focus the toolbar with the keyboard in the source editing mode
## 📝 Provide a description of the improvement

1.  Use the keyboard to enter the source editing mode.
2.  Focus on the editable and type something.
3.  Try to move back to the toolbar with the keyboard.

Related - #9906.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Feature (core): Enabled toolbar focusing (and cycling) across all editor implementations and features. Closes #10368. Closes [#5146](https://github.com/ckeditor/ckeditor5/issues/5146)**.** Closes #9906. Closes #10025.

BREAKING CHANGE (ui): The `enableToolbarKeyboardFocus()` helper has been removed. Please use the [`EditorUI#addToolbar()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorui-EditorUI.html#function-addToolbar) method instead to enable accessible toolbar navigation (and focusing) using `Alt+F10` and `Esc` keystrokes (see #10368).

---

### Additional information

*   This is a successor to #11876 (here's [why](https://github.com/ckeditor/ckeditor5/pull/11876#pullrequestreview-1005711792)) that handles the problem of source editing and the general navigation across different toolbars (classic, inline, block, balloon, and widget toolbars using Alt+F10).
*   [Manual test](http://fake.ckeditor.com:8125/ckeditor5/tests/manual/all-types.html).
*   ⚠️ **Requires** cksource/collaboration-features#4710

### TODOs

*   [x] Tests:
    *   [x] At least two tests for every editor type:
        *   [x] one to make sure Alt+F10 works for simple navigation (root->main toolbar->back to root),
        *   [x] another to make sure this works when the selection was on an image and the image toolbar was visible (e.g. image->image toolbar->main toolbar->image toolbar->back to the image).
    *   [x] Tests for changes in `EditorUI`
        *   [x] Tests for toolbars with different priorities (selected widget's toolbar > global toolbar, balloon toolbar > block toolbar, etc.)
    *   [x] Tests for the Alt+F10 in source editing textarea.
    *   [x] Tests for `WidgetToolbarRepository` to make sure it registers things in `EditorUI`
    *   [x] Same for `BalloonToolbar`.
*   [ ] Code refactoring (I left lots of comments in the code):
    *   [x] There's a risk of infinite loop in `EditorUI#focusNextFocusableToolbarDefinition` (see the code to learn more)
    *   [x] Helper functions in `EditorUI#_initFocusTracking` should probably become private methods of `EditorUI`.
    *   [x] Remove unnecessary comments.
    *   [x] `EditorUI#registerFocusableEditingArea()` has an obsolete support of UI views that we probably don't need at this stage.
    *   [ ] Remove console.logs in `EditorUI`
*   [ ] QA
    *   [ ] I didn't do anything to the multi root guide (example). I didn't check how it works but this is the right time to figure it out.
*   [ ] Docs:
    *   [x] API docs for the new code.
    *   [x] I suppose we should update some guides (which guides?) about developing new editors with the new `EditorUI` API.
    *   [ ] There's a [focus tracking guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/focus-tracking.html). Maybe we should mention some (which?) of the changes there?
    *   [x] Migration guide (removal of `enableToolbarKeyboardFocus()` and new API).
*   [x] TBD warning in `enableToolbarKeyboardFocus()` pointing to the new `EditorUI` API.
    *   [x] Decision: The helper is removed.

### Follow-ups

*   I don't think this is the right place to do this but I think we should definitely put "Press Alt+F10 to focus the toolbar"/"Press Alt+F10 to focus the next toolbar" in aria-labels here and there. Alt+F10 does not look like an industry standard to me. Right now, the user does not get any information about a toolbar being displayed and how to access it. This should be confirmed but:
    *   All root editables should have these labels.
    *   All widgets that have toolbars registered in `WidgetToolbarRepository` should have these labels (image, table, etc.).
        *   All widgets with nested editables that keep the widget toolbar visible should have labels (e.g. image caption).
    *   Source editing textarea should have the label.
    *   All toolbars should have a label explaining how to move to another toolbar.
*   My gut tells me we should use `FocusCycler` to move around the UI (cycling the toolbars) but I didn't do this in this PR.  I suppose `FocusCycler#_getFocusableItem()` is too simple to make decisions I implemented in this PR (toolbars have priorities and deciding which to focus is a lot harder). But I suppose we could unify everything down the road.
    *   This could overlap with the issue that @mmotyczynska is working on (#11851). In this issue we're considering `FocusCycler` navigating 2-dimensional focus planes (toolbars are focus vectors, grids are focus matrices). Maybe this is the right time to give `FocusCycler` a boost and some Swiss knife vibes and handle all of this?
*   There's an [optional follow-up](https://github.com/ckeditor/ckeditor5/issues/12062) about re-writing some pieces of the `SourceEditing` that I first decided to handle here but then I figured things were already getting complex so I extracted the code to a separate PR. Long story short, this is about `SourceEditing` using ckeditor5-ui to bring its UI (textarea) and reduce internal redundancy.

### CODE REVIEW

**Comment by mateuszzagorski** [comment]
2 problems found while working on tests:

1.  Balloon editor
Place selection in caption. Press alt+f10 2 times, to cycle between two of the available toolbars. After that, as of now, you shouldn't be able to cycle back to image toolbar.

https://user-images.githubusercontent.com/11699569/182621662-0b468b36-cd49-4c36-b70c-38b47ce399a2.mov

2. Balloon block
Place selection in caption. Keep pressing alt+f10 and observe where the focus goes.

https://user-images.githubusercontent.com/11699569/182621801-c31b4abf-9961-4052-94c8-82c0af03a60b.mov

**Comment by oleq** [comment]
There's one problem left that I identified but this is beyond the scope of this issue. It is related to the balloon logic and there's no easy workaround other than refactoring of the balloon system (to prevent position inheritance in certain cases)

**Comment by oleq** [comment]
TBD: Backwards compat.

**Comment by oleq** [comment]
@ckeditor/qa-team Could you please check this out?

## Requirements

*   Check out `ck/10368-source-editing-focus-toolbar-v2` branches in ckeditor5 and collaboration-features.
*   Start with the all-types manual test [http://fake.ckeditor.com:8125/ckeditor5/tests/manual/all-types.html.](http://fake.ckeditor.com:8125/ckeditor5/tests/manual/all-types.html.) Then get creative 😛

## Scope

The whole idea of this PR is to make sure that 

*   Alt+F10 always moves the focus from editing root or source editing to the toolbar
*   Successive Alt+F10 presses move focus to the next available toolbar
    *   Depending on the selection in the editor, there could be none others (e.g. in the classic editor, when the selection is in text).
    *   Depending on the selection in the editor, there could be many (e.g. in a balloon block editor).
*   Pressing Esc when any toolbar is focused should move the focus back to where it came from (an editing, source editing area or a nested editable like image caption).
*   This also applies to all sorts of collaborative editors (e.g. revision history).
*   There should be no crash in the console.



## Known issues

*   There's one https://github.com/ckeditor/ckeditor5/pull/12064#issuecomment-1206484768.

**Comment by oleq** [comment]
Use-case to fix: when pressing Alt+F10 in a toolbar when there's no other toolbar to focus:

*   nothing should change (expected)
*   focus moves to the first item in the dropdown (actual)

**Comment by oleq** [comment]
Use-case to fix (low priority): when pressing Alt+F10 in a toolbar when some dropdown is open and the focus moves to another toolbar, the dropdown should close.

**Comment by Acrophost** [comment]
Use-case to fix: when pressing ALT+F10 more than once in Balloon Editor when only one toolbar is available to focus:

*   focus moves to balloon toolbar and stays there for next ALT+F10 presses (expected)
*   focus moves to balloon toolbar and on next ALT+F10 goes missing (actual)

https://user-images.githubusercontent.com/66953380/184882105-a584f7df-b31a-4405-a25f-c49fc205db61.mov

**Comment by Acrophost** [comment]
Use-case extending [https://github.com/ckeditor/ckeditor5/pull/12064#issuecomment-1216633694](https://github.com/ckeditor/ckeditor5/pull/12064#issuecomment-1216633694) - bugs out also without balloon toolbar, steps below:

1.  add table
2.  add image inside one of the table cells
3.  select the whole table
4.  select image
5.  ALT+F10 few times

https://user-images.githubusercontent.com/66953380/184893506-5bd8b80f-d628-474c-a476-d760bfa65f7a.mov

**Comment by oleq** [comment]
*   I fixed the balloon toolbar issue [https://github.com/ckeditor/ckeditor5/pull/12064#issuecomment-1216584257.](https://github.com/ckeditor/ckeditor5/pull/12064#issuecomment-1216584257.) 
*   I somehow made [https://github.com/ckeditor/ckeditor5/pull/12064#issuecomment-1216633694](https://github.com/ckeditor/ckeditor5/pull/12064#issuecomment-1216633694) less visible but I couldn't get rid of the issue in some scenarios. This is a problem with the `ContextualBalloon` API and comes down to #5439 which is way beyond the scope of this PR. 
    *   For instance, it works fine when the image was selected first:



but it will fail when the table cell content was focused first before an image:



@Acrophost Could test the toolbars again to verify if my recent fixes do not introduce new regressions? Thanks.

**Comment by Acrophost** [comment]
@oleq everything works much better and I don't see any more issues besides the one you have already mentioned :)

**Pull request merged**
