### PR TITLE
jsdoc for currentGroupName in specialcharactersnavigationview

### PR DESCRIPTION
**Pull request by fedemp**

### CODE REVIEW

**Comment by Reinmar** [comment]
Thanks again :)

**Comment by Reinmar** [comment]
Out of curiosity – how do you find these issues? :O

**Comment by fedemp** [comment]
> Out of curiosity – how do you find these issues? :O

I'm creating Typescript type definitions: https://github.com/DefinitelyTyped/DefinitelyTyped/pulls?q=is%3Apr+author%3Afedemp+ :smile:

**Comment by Reinmar** [comment]
Wow, that's cool to hear. And... wow, that's a lot of work that you've done so far. I'll let the team know – they'll love it :)

**Pull request merged**
