### PR TITLE
Docs title demo

### LINKED ISSUE #5625: Part of the Title plugin docs is written in the snippet and it produces errors
## 📝 Provide a description of requested docs changes

I was searching the "You can check the content of the title and body elements below." text in the `title.md` document and I couldn't find it. I don't think we should put part of the documentation in snippets since it is hard to find.

Also, the code highlight plugin outputs warnings about this (I was checking why this was logged):

> Language "title-console" in codeblock section is not supported. Autohighlight was used instead!
onmessage @ highlight.worker.js:14

### PR DESCRIPTION
**Pull request by godai78**
Closes #5625

Part of feature description was removed from the demo snippet and moved to the document itself.

### CODE REVIEW

**Review by jodator — APPROVED** [review]
I don't know why I didn't just fix that back then :D Cool!

**Comment by AnnaTomanek** [comment]
Guuuuyyyyys, you have just put this to `master` which means it's gonna wait for another month :disappointed:  The release will be generated out of the `release` branch, which will then be merged into `stable`. And your change will be left in `master` to wither there :wilted\_flower: . Why the hurry?

**Comment by godai78** [comment]
Why nobody ever mentioned committing things to `release`?

**Comment by jodator** [comment]
Fortunately, this is not a big rewrite. Good that you pointed out this as I missed that. I will think of it next time more.

If such things happen in the future let's push the reviewer/merger to cherry-pick :cherries: the change to a proper branch _if_ the change needs to be there ASAP.

For the rush - despite the error of merge target - it is OK to have to merge things fast if they are OK. Especially if the change is a handful of lines. Keep the process light and efficient. Yet, the point of merging to a wrong branch is valid.

**Comment by godai78** [comment]
I'll port it to release in a five.

**Comment by godai78** [comment]
31a607c

**Pull request merged**
