### PR TITLE
Improve source editing textarea field size and scrolling behaviour

### LINKED ISSUE #10422: Source editing view loses borders on scroll
## 📝 Provide detailed reproduction steps (if any)

1.  http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/features/source-editing.html
2.  Open source editing mode
3.  Scroll content (both horizontally and vertically)

### ✔️ Expected result

The border is still visible.

### ❌ Actual result

Borders scroll out of the visible area.

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by dawidurbanski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (source-editing): Improve source editing textarea field size and scrolling behaviour. Closes #10422.

---

### Additional information

Testing should be done with at least these steps:

1. Run `yarn manual --files=source-editing` and test source editing with default content.
2. Copy all the content from https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html to the manual test and check source editing again.
3. Build docs locally (`yarn docs && yarn docs:serve`) and check http://127.0.0.1:8080/ckeditor5/29.2.0/features/source-editing.html

In all cases there should be:
- No horizontal scroll.
- All the content in text area should be reachable by scrolling down.
- In manual test: textarea should be long and the body should be scrollable.
- In docs: textarea should have max height of 700px and the textarea itself should be scrollable.

### CODE REVIEW

**Comment by Reinmar** [comment]
For some reason, this breaks the manual test.

If you open it on master, you can see the bottom of the editor:



On your branch, you cannot scroll further than this:



And I even tried adding padding to `body`. It didn't help.

The problem is probably related to some unnecessary padding in the textarea:

**Comment by dawidurbanski** [comment]
@Reinmar I fixed what you have raised, and by the way simplified this ugly width calc thing. Turned out that after getting rid of css grid it was enough to apply `box-sizing: border-box;` onto textarea and it works just fine.

**Comment by Reinmar** [comment]
Out of curiosity, is this bug that these areas are not 100% width/height of available space resolved on your PR:

image

**Comment by dawidurbanski** [comment]
Yes:

Screenshot 2021-09-30 at 14 29 48

**Pull request merged**
