### PR TITLE
Docs: Hard-code editor version in CDN links to legacy builds

### PR DESCRIPTION
**Pull request by filipsobol**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: Hard-code editor version in CDN links to legacy builds.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Review by godai78 — APPROVED** [review]

**Comment by godai78** [comment]
While 41.0.0 is fine, don't we want to have it on 41.3.0? Or do we want to avoid BC in list plugins?

**Comment by Witoso** [comment]
It should be the last version before 42.

**Review by godai78 — DISMISSED** [review]

**Review by godai78 — APPROVED** [review]
Yeah.

**Review by gorzelinski — APPROVED** [review]
Good idea and `41.4.2` is indeed the last version before `42`.

**Pull request merged**
