### PR TITLE
Updated changelog and migration guide

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Internal: Updated changelog and migration guide.

### CODE REVIEW

**Comment by godai78** [comment]
Why is it targeted at `master`?

**Comment by scofalik** [comment]
I got confused by it being a changelog, but since there's also migration guide, I believe it should be `stable`, sorry for that.

**Comment by godai78** [comment]
I'm working on it now, so please hold on a moment.

**Review by godai78 — APPROVED** [review]
I say we merge it, bro.

**Pull request merged**
