### PR TITLE
#2052: Support for inline images

### LINKED ISSUE #8871: Integrate inline images with the link feature

### LINKED ISSUE #8907: Get rid of the block image caption that currently shows up on image focus
We agreed we're going with a "toggle caption" button in the image toolbar instead because it radically simplifies the UX in terms of switching between image types.

By doing this, we're also avoiding "jumping content" when navigating across the document and the overall confusion of the users as to why things change despite them doing no editing (also: will this "empty" caption remain or not? is it actually empty?).

The implementation of `ImageCaption` should also simplify.

Note: This is a major change for the CF team. Let's keep them informed.

### LINKED ISSUE #9017: Update inline image to use AttributeElement for links
## Provide a description of the task

Links should not break while spanning over text and inline images. This depends on #8998 - there will be an option to mark a `ContainerElement` as an inline so it will accept wrapping with an `AttributeElement` `<a>`.

### LINKED ISSUE #9102: Unify the image insertion behavior in different scenarios (also widgets)
ATM there are numerous helpers scattered across the ckeditor5-image package + the `findOptimalPosition()` helper from ckeditor5-widget. This results in (depending on the context):

* images sometimes being inserted over existing selected objects,
* images sometimes being inserted next to existing selected objects,
* the cases above but with multiple image upload/insertion (basic upload, CKFinder, etc.),
* (some) widgets, in general, being inserted over or next to existing widgets.

This is all related to the fact that when the project didn't have the widget type around feature implemented, we were forced to insert widgets into the next or previous available position if another widget was selected because there would be no easy way to insert a couple of images next to each other in an empty editor. Long story short, this debt must be paid and the inline image integration is the best moment for it.

### LINKED ISSUE #9136: Re-think the UX for image caption toggling
# ATM

https://github.com/ckeditor/ckeditor5/pull/9090 implements the following UX:

* 👍 click&type, which is likely the common use-case,
* 👎 the toolbar disappears so to revert adding the caption, you need to re-select the image,
* 👎 there's a lot happening at the same time (toolbar disappears, the caption appears and gets highlighted, the selection moves)

## Reverting an existing caption 

# Other UXs

## Don't move the selection to the caption

* 👍 the toolbar stays in place, click again without moving the mouse to get rid of the caption,
* 👍 the selection does not change and the toolbar stays in place, less distractions,
* 👎 typing in a caption requires another click,

## Move the selection to the caption but keep the toolbar

* 👍 click&type, which is likely the common use-case,
* 👍 the toolbar stays in place, click again without moving the mouse to get rid of the caption,
* 👍 the toolbar stays in place, less distractions,
* 👎 possible collision with the balloon toolbar, although we already do that for the table toolbar
* 👎 requires changes in other features (note the grayed out buttons in the toolbar when the selection is in the caption)

### LINKED ISSUE #9162: Image caption placeholder wraps for small images

### LINKED ISSUE #9166: The UX of resizing small images looks broken
It already looks bad for block images (which have 50px `min-height` for `` BTW)

and I can imagine it will look even worse for small inline images (e.g. 16x16px) that will also get resizing after #8777. The resize UI might cover the entire inline image and we should do something about it. For instance, we could display only a single resize handle for very small images. This will require some additional research.

Related to #9165.

### LINKED ISSUE #9167: The linked image indicator does not work well with small (inline) images
ATM we use the anchor icon as the only indicator for linked image. This works OK (also debatable) for large images but there's simply not enough space to do the same for a 32x32px inline image, which will be common in certain cases.

### LINKED ISSUE #9183: Managing multiple block images
## 📝 Provide detailed reproduction steps (if any)

After adding the new image styles (https://github.com/ckeditor/ckeditor5/tree/i/8909-inline-images-styles) and inline images, there is an inconsistency in displaying multiple block and inline images side by side.

❌ Actual result

All images below have the same `image-style-align-left` class, but the first two are the block images and the next inline images. The reason for this behavior is that the block images have the `clear: both` rule for the `img` element.

### ✔️ Expected result

* It should be possible to display multiple block images side by side.
* The behavior of the inline and block images set by the same button should be consistent.
 
It can be fixed easily by overriding the `clear: both` rule for the `image-style-align-left` class.

**The problem is that this particular class is one of the default classes provided in the editor. Changing its appearance can lead to unexpected (and expected) results in clients' content.**

### LINKED ISSUE #9340: Implement declarative image style drop-downs
## 📝 Provide a description of the improvement

`config.image.style.groups` makes little sense because it has no impact on the model/data/upcast and general logic of the feature. It exists only to create dropdowns in the component factory. 

Instead of using this configuration, we can configure dropdowns declaratively, thus separating the model and view layers.

Related to https://github.com/ckeditor/ckeditor5/issues/1472#issuecomment-456149372.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

### LINKED ISSUE #9342: Add sensible max-width to left/right block styles
## 📝 Provide a description of the improvement

ATM if an image is larger than the editing root, applying one of "left/right aligned image" styles does not change anything visually. With `max-width: 90%` there would be at least some feedback to the user confirming the successful application of the style.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

### LINKED ISSUE #9399: EasyImage should not depend on Image (after introducing ImageBlock and ImageInline)
## 📝 Provide detailed reproduction steps (if any)

When you use `EasyImage` and load either `ImageBlock` or `ImageInline` (but not `Image`) there is a soft requirement error in the console because `Image` is missing.

The code of the `EasyImage` plugin does not use anything from `@ckeditor/ckeditor5-image` so this is a virtual requirement. Most likely we made `Image` the requirement of `EasyImage` to improve DX so developers don't have to include both if they want to use our service. The intention was good but it backfired when the API has changed.

The solution is getting rid of the requirement (breaking change) and mentioning in the migration guide that `EasyImage` must be used together with `Image`.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #9507: Builds' demos and configurations have inconsistent `ImageResize` plugin configurations.
## 📝 Provide detailed reproduction steps (if any)

1. The `inline` editor has the `ImageResize` plugin in the demo, but not in the default Online Builder configuration or the build itself. Besides that, the image styles configuration in the demo is the `document` type and `semantic` in the build.
2. The `document` editor has the `ImageResize` plugin in the demo and the Online Builder, but not in the build itself.

IMO it makes it difficult for the user to pick his desirable build. He looks at the demo and expects to get the same output from the build/Online Builder.

Besides, we have made some decisions about the builds' configurations, why change them in the demos? The above cases concern the display of the images in various styles (https://github.com/ckeditor/ckeditor5/issues/7715) - the fact that the style has changed is invisible because the image is so big that it always takes the whole width of the editor. 
**It can be easily fixed by setting the original size of the example images to something less than the usual width of the editable area.**

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #9521: Linked image resize handlers do not refresh when converting block image to inline
## 📝 Provide detailed reproduction steps (if any)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #9524: Selected inline widgets wrapped in an attribute in the view should create fake selection
A generalization of https://github.com/ckeditor/ckeditor5/issues/9521.

ATM when a linked inline image gets selected, the selection is `[<a><span class="ck-widget"></span></a>]`. This is how engine works, selecting a linked text also results in `[<a>text</a>]`. 

This causes numerous issues with the logic depending on view selection `getSelectedElement()` (where `<a>` is returned instead of the widget). The main issue is that the selection is not fake, which affects accessibility and who-know-what-else – the widget plugin does not recognize as `[<a><span class="ck-widget"></span></a>]` a selected widget.

### LINKED ISSUE #9566: Image toolbar overlapping drop cursor
Image toolbar being visible all the time can become a bit problematic with inline images, especially when you for example want to drag an image into the line above the current one. Screencast contains dragging a table as a comparison:

https://user-images.githubusercontent.com/34380544/115722931-c0750280-a37f-11eb-8c1a-20deaf43aa4f.mp4

### LINKED ISSUE #9567: It's possible to create a code block with an image inside
## Steps to reproduce:
1. Add some text with inline image inside
2. Select everything
3. Click `Insert code block`

## Result:
A code block with image inside is created

## Expected:
Code block cannot contain images

## Screencast:

https://user-images.githubusercontent.com/34380544/115726501-113a2a80-a383-11eb-9e85-c56ec4ca5354.mp4

### LINKED ISSUE #9580: Safeguard the way widget plugin sets the fake selection (inline images/CF)
ATM we detect it based on the view selection (selected element) and there's already a piece of logic there that detects attribute elements surrounding inline widgets and fixes the selection to ensure it is fake when an inline widget is selected. 

While working on the CF integration, we discovered there are more cases like this, for instance when markers come into play. They may not surround the widget but they will precede it. The view will then render the selection before it `foo[<span class="marker"></span><span class="inline-"widget></span>]bar` and, again, the selection will not be fake and `getSelectedElement` will also fail.

Although this scenario ☝️ will be addressed on the CF side by not rendering the marker in this case at all (which is necessary for other reasons BTW cksource/collaboration-features#4006), better safe than sorry so let's make this whole logic depend on the model selection, not on the view selection.

### LINKED ISSUE #9607: Link toolbar does not show for inline widgets with no defined toolbar
A follow-up to #2052. Branch `i/2052-inline-images` 

I've been testing inline widgets (https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html) on the current branch of inline images (0b674a4) and when a link is added on an inline widget, the balloon can not be later opened by clicking on the widget.

cc @oleq.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Feature (image): Introduced support for inline images in editor content. Available out–of–the–box in all ready–to–use editor builds inline images can be uploaded, styled, resized, and linked and complement the already supported block images. See the [image feature overview guide](https://ckeditor.com/docs/ckeditor5/latest/features/images/images-overview.html) to see inline images in action. For more information about breaking changes, migration path, and tips, check out the [migration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migration/migration-to-28.html).

Feature (image): It should be possible to define the dropdown menu as an object in the `config.image.toolbar` configuration. Closes #9340.

Other (image): Turned the image utils module into an editor plugin to allow sharing utils outside the package. See #8871.

Fix (image): The side-aligned images should always have some `min-width` property to not take the whole editor width. Closes #9342.

Fix (image): The floating block images, except the `side` image, should be displayed side by side by default. Closes #9183.

Fix (image): An image should never overflow the widget boundaries while changing its size. Closes #9166.

Fix (image): The size label should be displayed above the image if it doesn't fit inside. See #9166.

Fix (image): An Image caption placeholder text should not wrap or overflow. Closes #9162.

Other (image): The image toolbar should be visible if the selection is placed inside an image caption. Closes #9136.

Other (image): The image caption should be controlled using the toolbar button and a command for better integration with image styles. Closes #8907.

Other (build-decoupled-document): The editor document build should include the `ImageResize` plugin. Closes #9507.

Feature (link): Integrated the link feature with inline images. Closes #8871. Closes #9017. Closes #9167.

Fix (link): The link UI should be shown when clicking a linked inline widget. Closes #9607.

Other (widget): Safeguarded the way the `Widget` plugin sets the fake selection. Closes #9580.

Fix (widget): Selected inline widgets wrapped in an attribute in the view should create a fake selection. Closes #9524. Closes #9521.

Other (widget): Replaced the `findOptimalInsertionPosition()` helper with `findOptimalInsertionRange()` that will now attempt to replace selected blocks when inserting new widgets. Closes #9102.

Fix (clipboard): Hide all toolbars when the user starts dragging the widget and show them when the drag ends. Closes #9566.

Fix (code-block): The code block feature should not allow for inserting inline widgets as its content. Closes #9567.

Other (easy-image): Removed the `Image` plugin dependency from the `EasyImage` plugin. Closes #9399.

Other (table): Added the `.ck-table-bogus-paragraph` CSS class to the in-cell pseudo-paragraph used for data tables for easier and safer styling.

Other (core): Added several icons for new image styles (see #8909).

Other (ui): Added the `class` property to the `SplitButtonView` UI component. See #8909.

Other (image, table, html-embed, media-embed, page-break, horizontal-line): New widgets will replace the selected block instead of being added next to it while being inserted (see #9102).

BREAKING CHANGE (image): The `Image` plugin works as a glue for both `ImageBlock` and `ImageInline` features now (previously only block images). If you do not want inline images to be allowed, consider replacing the `Image` plugin with `ImageBlock` in your editor configuration. Otherwise, all images without the `<figure>` wrapper will be loaded into the editor content as inline images, which in some cases may affect content semantics and styling.

BREAKING CHANGE (image): The `ImageEditing` plugin is no longer standalone as the majority of its logic was extracted to `ImageBlockEditing` and `ImageInlineEditing` plugins. The logic remaining in the `ImageEditing` is common for both `ImageBlockEditing` and `ImageInlineEditing` plugins.

BREAKING CHANGE (image): The image caption is no longer displayed automatically the user selects a block image. Instead, its presence is controlled using the `'toggleImageCaption'` toolbar button and a [`ToggleImageCaptionCommand`](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagecaption_toggleimagecaptioncommand-ToggleImageCaptionCommand.html) for better integration with [revamped image styles system](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migration/migration-to-28.html#image-styles). [Learn more](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migration/migration-to-28.html#image-caption).

BREAKING CHANGE (image): Some helpers from the image utils module (`@ckeditor/ckeditor5-image/src/image/utils.js`) have moved to the [`ImageUtils` plugin](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageutils-ImageUtils.html). The helpers are still accessible via `editor.plugins.get( 'ImageUtils' )` namespace, for instance, `editor.plugins.get( 'ImageUtils' ).insertImage( ... )`.

BREAKING CHANGE (image): The API of the [`insertImage()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageutils-ImageUtils.html#function-insertImage) helper has changed, please make sure to update your integrations.

BREAKING CHANGE (image): The `getSelectedImageWidget()` helper is no longer part of the public API.

BREAKING CHANGE (image): The `getViewImgFromWidget()` helper is no longer part of the public API.

BREAKING CHANGE (image): The `isImageAllowed()` helper is no longer part of the public API.

BREAKING CHANGE (image): The `isImage()` helper is no longer part of the public API.

BREAKING CHANGE (image): The `isImageWidget()` helper is no longer part of the public API.

BREAKING CHANGE (image): The `toImageWidget()` helper is no longer part of the public API.

BREAKING CHANGE (image): The `captionElementCreator()` helper is no longer part of the public API.

BREAKING CHANGE (image): The `isCaption()` helper is no longer part of the public API.

BREAKING CHANGE (image): The `getCaptionFromImage()` helper is now available as [`getCaptionFromImageModelElement()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagecaption_utils.html#function-getCaptionFromImageModelElement).

BREAKING CHANGE (image): The `matchImageCaption()` helper is now available as [`matchImageCaptionViewElement()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagecaption_utils.html#function-matchImageCaptionViewElement).

BREAKING CHANGE (image): The `defaultIcons` are now available as [`DEFAULT_ICONS`](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagestyle_utils.html#constant-DEFAULT_ICONS).

BREAKING CHANGE (image): The `defaultStyles` are now available as [`DEFAULT_OPTIONS`](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagestyle_utils.html#constant-DEFAULT_OPTIONS).

BREAKING CHANGE (image): The linked image indicator (icon) rendered as a `<span>` with the `.ck-link-image_icon` CSS class has been removed. To alter the look of the indicator (including the icon), please use `figure.image > a::after` (for linked block images) and `a span.image-inline::after` (for linked inline images) CSS selectors instead.

BREAKING CHANGE (image): The `isImageWidget()` helper is no longer exposed by the [`Image`](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_image-Image.html) plugin.

BREAKING CHANGE (image): The API of common [image converters](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_image_converters.html) has changed. Please refer to the documentation to learn more.

BREAKING CHANGE (image): The API of various [image caption utils](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagecaption_utils.html) has changed. Please refer to the documentation to learn more.

BREAKING CHANGE (image): The conversion helpers [`srcsetAttributeConverter()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_image_converters.html#function-srcsetAttributeConverter) and [`modelToViewAttributeConverter()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_image_converters.html#function-modelToViewAttributeConverter) now require the `imageType` parameter.

BREAKING CHANGE (easy-image): The [`EasyImage`](https://ckeditor.com/docs/ckeditor5/latest/api/module_easy-image_easyimage-EasyImage.html) plugin is no longer automatically importing the [`Image`](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_image-Image.html) plugin as a dependency. [Learn more](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migration/migration-to-28.html#easyimage-plugin).

BREAKING CHANGE (ckfinder): The [`CKFinder`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ckfinder_ckfinder-CKFinder.html) plugin is no longer automatically importing the [`Image`](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_image-Image.html) plugin as a dependency. [Learn more](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migration/migration-to-28.html).

BREAKING CHANGE (link): The `isImageAllowed()` helper is now available as [`isLinkableElement()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_link_utils.html#function-isLinkableElement).

BREAKING CHANGE (media-embed): The API of the [`insertMedia()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_media-embed_utils.html#function-insertMedia) helper has changed. See the documentation to learn more.

BREAKING CHANGE (build-decoupled-document): The official [decoupled document](https://www.npmjs.com/package/@ckeditor/ckeditor5-build-decoupled-document) build now ships with the [`ImageResize`](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageresize-ImageResize.html) plugin enabled by default. [Learn more](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migration/migration-to-28.html).

BREAKING CHANGE (table): The in-cell pseudo-paragraph used for data tables is no longer styled using the inline `style` attribute but a `.ck-table-bogus-paragraph` CSS class instead.

BREAKING CHANGE (widget): The `findOptimalInsertionPosition()` helper is now `findOptimalInsertionRange()` and returns a [model range](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_range-Range.html). Also, instead of searching for a position next to the currently selected block, it will now attempt to replace that block (see #9102).

BREAKING CHANGE (widget): The `checkSelectionOnObject()` helper is no longer part of the public API.

---

### Additional information

### CODE REVIEW

**Comment by LukaszGudel** [comment]
### Steps:
1. Change block image size.
2. Drag resized image to the paragraph.

### Result:
Size value resets back to 'Original'.


https://user-images.githubusercontent.com/58658048/115712890-a6362700-a375-11eb-96cf-deab9cd85fdd.mp4


Notes:
- All browsers
- When draging resized inline image to empty paragraph size is kept

**Comment by LukaszGudel** [comment]
Caret has the same height as inline image:

https://user-images.githubusercontent.com/58658048/115714106-0d081000-a377-11eb-9bcf-da07cfd022ce.mp4

Notes:
- **Safari only**

**Comment by FilipTokarski** [comment]
Image toolbar being visible all the time can become a bit problematic with inline images, especially when you for example want to drag an image into the line above the current one. Screencast contains dragging a table as a comparison:

https://user-images.githubusercontent.com/34380544/115722931-c0750280-a37f-11eb-8c1a-20deaf43aa4f.mp4

**Comment by FilipTokarski** [comment]
## Steps to reproduce:
1. Add some text with inline image inside
2. Select everything
3. Click `Insert code block`

## Result:
A code block with image inside is created

## Expected:
Code block cannot contain images

## Screencast:

https://user-images.githubusercontent.com/34380544/115726501-113a2a80-a383-11eb-9e85-c56ec4ca5354.mp4

**Comment by FilipTokarski** [comment]
## Steps to reproduce:
1. Create an empty list item
2. Drag inline image into empty list item

## Result:
List item is removed, image becomes a block image

## Expected:
Image is dropped in list item as an inline image

## Screencast:

https://user-images.githubusercontent.com/34380544/115727749-2f545a80-a384-11eb-8979-458d74351b86.mp4

**Comment by FilipTokarski** [comment]
## Steps to reproduce:
1. Upload an image as inline
2. Add a link on the image
3. Try to resize it

## Result:
You cannot resize it, size value is `NaN%`, you also cannot drag it anywhere in Firefox. Sometimes it's hard to reproduce it, but with those steps I got it every time.

## Screencast:

https://user-images.githubusercontent.com/34380544/115735574-e0f68a00-a38a-11eb-9272-0695056f6956.mp4

**Comment by Mgsy** [comment]
## Steps to reproduce

1.  Insert an inline image to a list item in a table cell.
2.  Resize the image.

## Actual result

The "jumps" and the size value is `NaN%`.

## GIF



## Notes

`NaN%` is displayed only if the image is in the list item, in a paragraph it only "jumps".

**Comment by Mgsy** [comment]
## Steps to reproduce

1.  Resize an inline image in a table cell.

## Actual result

The image changes its size and it "jumps".

## GIF

**Comment by LukaszGudel** [comment]
### Steps

1. Set an Image to `Wrap text`.
2. Add todo list.

### Result:
List boxes overlap with the image
image

**Comment by LukaszGudel** [comment]
### Steps
1. Set image to `Wrap text`.
2. Add todo list.
3. Try to indent list items with `TAB`.

### Result:
List items do not indent unless image is removed or changed to block:

https://user-images.githubusercontent.com/58658048/115838223-bbfd2800-a419-11eb-8f5d-61824c9911fe.mp4

**Comment by FilipTokarski** [comment]
## Steps to reproduce ( only in CHROME ) :
1. Add inline image
2. Add html embed
3. Drag image into html embed
4. Undo

## Result:
```js
Uncaught TypeError: Cannot read property 'name' of undefined
    at Mapper.getModelLength (mapper.js:485)
    at Mapper._toModelOffset (mapper.js:456)
    at Mapper.on.priority (mapper.js:118)
    at Mapper.fire (emittermixin.js:199)
    at Mapper.toModelPosition (mapper.js:312)
    at Mapper.toModelRange (mapper.js:286)
    at Object.<anonymous> (upcasthelpers.js:511)
    at Object.fire (emittermixin.js:199)
    at fireListenerFor (bubblingemittermixin.js:162)
    at Document.fire (bubblingemittermixin.js:92)
```

## Screencast:

https://user-images.githubusercontent.com/34380544/115838540-15fded80-a41a-11eb-9a14-b6833b0f945c.mp4

**Comment by LukaszGudel** [comment]
### [SAFARI ONLY] Steps:
1. Select all content from https://ckeditor.com/ckeditor-5/demo/ and copy it.
2. Paste it to all-features manual test.

### Result:
Editor crashes with error:
```
TypeError: null is not an object (evaluating 'modelImageElement.name')
  fire - emittermixin.js:232
  domListener - emitermixin.js:247
```

Notes:
- this is related to relative image src (``) in demo content
- other browsers do not crash with those steps and are showing missing image icon
- same scenario in Safari with editor on `master` branch or in our demos/docs is not crashing

**Comment by LukaszGudel** [comment]
### Steps:
1. Focus empty image caption field.

### Result:
Placeholder 'Enter image caption' is still visible. 
image


- On demo pages with v27.1.0 editor this placeholder disappears on focus.

**Comment by LukaszGudel** [comment]
### Steps:
1. Add an image caption.
2. Hide caption with toolbar button.
3. Drag and drop image or cut and paste image.
4. Toggle caption for this image.

### Result:
Image caption field is empty.

---

Notes:
- If caption is not hidden during step 3 then caption content is preserved.

**Comment by LukaszGudel** [comment]
### Steps:
1. Open CF real-time-editing manual test and connect 2 clients.
2. Convert image to inline.
3. Refresh page on both clients to clear undo history (optional).
4. Convert image to block using 'Break text' toolbar icon on client A.
5. Drag and drop image into paragraph on client B.
6. Undo on client A.

### Result:
Image is duplicated, where one is inline and one is block. Recording from Client A perspective: 

https://user-images.githubusercontent.com/58658048/116053582-24970f80-a67b-11eb-9191-4684cbaf90ce.mp4

Notes:
- I've copied image toolbar config from all-featues into CF manual test to use new toolbar items
- It's not possible to go back to content from step 3 with undo on both clients - duplicated images will stay

**Comment by Mgsy** [comment]
## Steps to reproduce

1.  Add a comment to an inline image.
2.  Convert the image to the block image.

## Actual result

The comment is lost.

**Comment by LukaszGudel** [comment]
###Steps to reproduce

1. Add a comment to  the text in image caption.
2. Double toggle image caption.

###Actual result
The comment is lost.

**Comment by LukaszGudel** [comment]
### Steps:
1. Add linked inline image.
2. Toggle table caption.
3. Drag&drop or copy&paste image into table caption.
4. Convert image to block.

https://user-images.githubusercontent.com/58658048/119451091-25cc6280-bd35-11eb-8d70-653cbfea9224.mp4

### Result:
Editor crashes with error:
```
writer.js:1489 Uncaught TypeError: Cannot read property 'getAttribute' of null
    at setAttributeOnItem (writer.js:1489)
    at Writer.removeAttribute (writer.js:421)
    at Object.callback (imagestylecommand.js:117)
    at Model._runPendingChanges (model.js:839)
    at Model.change (model.js:184)
    at ImageStyleCommand.execute (imagestylecommand.js:101)
    at ImageStyleCommand.<anonymous> (observablemixin.js:258)
    at ImageStyleCommand.fire (emittermixin.js:199)
    at ImageStyleCommand.<computed> [as execute] (observablemixin.js:262)
    at CommandCollection.execute (commandcollection.js:69)
```

### Notes:
- this image needs to be linked as captions do not allow inserting nonlinked inline images 
- linked image can be also inserted into image captions, but converting it to block will remove an image

**Comment by LukaszGudel** [comment]
### Steps:

1. Add inline image.
2. Click on 'Edit source' button in HTML embed.
3. Drag inline image into HTML embed.
4. Undo.

[https://user-images.githubusercontent.com/58658048/119456596-1e0fbc80-bd3b-11eb-86e1-515d202605f3.mp4](https://user-images.githubusercontent.com/58658048/119456596-1e0fbc80-bd3b-11eb-86e1-515d202605f3.mp4)

### Result:

Editor throws error:

```
mapper.js:485 Uncaught TypeError: Cannot read property 'name' of undefined
    at Mapper.getModelLength (mapper.js:485)
    at Mapper._toModelOffset (mapper.js:456)
    at Mapper.on.priority (mapper.js:118)
    at Mapper.fire (emittermixin.js:199)
    at Mapper.toModelPosition (mapper.js:312)
    at Mapper.toModelRange (mapper.js:286)
    at Object.<anonymous> (upcasthelpers.js:511)
    at Object.fire (emittermixin.js:199)
    at fireListenerFor (bubblingemittermixin.js:162)
    at Document.fire (bubblingemittermixin.js:92)

```

### Notes:

- same scenario with block image is not crashing on undo
- it looks like a 'soft crash' and editor seems to be fully usable after the error
- pressing Command+Z once more will bring back the image

**Pull request merged**
