### PR TITLE
I/2762: Updating media embed support for google maps.

### LINKED ISSUE #2762: The media embed supports only one URL scheme for google maps
The media embed supports google maps but links obtained from application or google maps itself is not recognized:
- :+1:  [the URL from the bar](https://www.google.com/maps/place/CKSource/@52.2551735,20.986658,18z/data=!4m13!1m7!3m6!1s0x47009964a4640bbb:0x97573ca49cc55ea!2sPoland!3b1!8m2!3d51.919438!4d19.145136!3m4!1s0x0:0xd6a4f1da58e2ad25!8m2!3d52.2558306!4d20.9875902?hl=en)
- :-1: url from share (web): https://goo.gl/maps/f1TKzBWv1wx ([embed.ly](https://embed.ly/docs/explore/oembed?url=https%3A%2F%2Fgoo.gl%2Fmaps%2Ff1TKzBWv1wx))
- :-1: URL from android app: https://maps.google.com/?cid=15466752940393540901 (it does insert place description/address). ([embed.ly](https://embed.ly/docs/explore/oembed?url=https%3A%2F%2Fmaps.google.com%2F%3Fcid%3D15466752940393540901))
- :-1: URL from android app (generated on Android 11): https://maps.app.goo.gl/TbE48BEThGu4VeAu7

### PR DESCRIPTION
**Pull request by mateuszzagorski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (media-embed): Updated media embed support for google maps ( `goo.gl/maps`, `maps.google.com`, `maps.app.goo.gl` ) as described in the #2762 issue.  
Closes #2762.

---

### CODE REVIEW

**Comment by mlewand** [comment]
@ckeditor/qa-team can you guys check if it works well with  the new URLs?

**Comment by Mgsy** [comment]
Basically, it works fine :+1: . However, currently, the media embed feature doesn't support domains different from _google.com_. For example, the following URL won't be correctly embedded:

[https://www.google.pl/maps/dir//Henryka+Wieniawskiego+2-10,+01-572+Warszawa/@52.2599255,20.9806803,14z/data=!4m9!4m8!1m0!1m5!1m1!1s0x471ecb8d5662996f:0xa482e96875feb142!2m2!1d20.9830672!2d52.2646412!3e0](https://www.google.pl/maps/dir//Henryka+Wieniawskiego+2-10,+01-572+Warszawa/@52.2599255,20.9806803,14z/data=!4m9!4m8!1m0!1m5!1m1!1s0x471ecb8d5662996f:0xa482e96875feb142!2m2!1d20.9830672!2d52.2646412!3e0)

...while this one works fine:

[https://www.google.com/maps/dir//Henryka+Wieniawskiego+2-10,+01-572+Warszawa/@52.2599255,20.9806803,14z/data=!4m9!4m8!1m0!1m5!1m1!1s0x471ecb8d5662996f:0xa482e96875feb142!2m2!1d20.9830672!2d52.2646412!3e0](https://www.google.com/maps/dir//Henryka+Wieniawskiego+2-10,+01-572+Warszawa/@52.2599255,20.9806803,14z/data=!4m9!4m8!1m0!1m5!1m1!1s0x471ecb8d5662996f:0xa482e96875feb142!2m2!1d20.9830672!2d52.2646412!3e0) 

Maybe we should handle this case too? This is a URL copied directly from the bar.

**Comment by mlewand** [comment]
Thanks for testing @Mgsy I think we can extract this to a separate issue - so that we check how many 👍 it gets.

@mateuszzagorski can you make the issue for case reported by Kacper (remember not to limit it to google.pl but make it clear that were looking for other TLDs too :slightly\_smiling\_face:)?

**Comment by mateuszzagorski** [comment]
Created the #9723 issue for the case reported by Kacper.

**Review by mlewand — APPROVED** [review]
LGTM

**Pull request merged**
