### PR TITLE
Snippet adapter will be searching for proper packages' dependencies

### LINKED ISSUE #7916: Docs builder uses its dependency when building snippets
## 📝 Provide detailed reproduction steps (if any)

A problematic feature is `marked` plugin which is used by [ckeditor5-markdown-gfm](https://www.npmjs.com/package/@ckeditor/ckeditor5-markdown-gfm) plugin.

### ✔️ Expected result

The dependencies of the the docs builder should not shadow dependencies of editor plugins (if possible).

### ❌ Actual result

See #7906.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Internal: The snippet adapter will be searching for proper packages' dependencies. Closes #7916.

### CODE REVIEW

**Comment by pomek** [comment]
R-, still checking some solutions.

**Comment by pomek** [comment]
Ready for review.

**Comment by pomek** [comment]
I pushed a fix (https://github.com/ckeditor/ckeditor5/pull/8215/commits/f3582b678177c50ef35e65fd143f7bb6dc4f8655) that change the list of directories where webpack will be looking for.

Instead of looking for each package separately (the `node_modules` directory could not exist):

```
[
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor-cloud-services-core/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-adapter-ckfinder/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-alignment/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-autoformat/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-autosave/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-basic-styles/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-block-quote/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-build-balloon/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-build-balloon-block/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-build-classic/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-build-decoupled-document/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-build-inline/node_modules',
  ...
```

Webpack should look inside `node_modules` of packages that contain the directory:

```
[
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-build-balloon-block/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-build-balloon/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-build-classic/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-build-decoupled-document/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-build-inline/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-markdown-gfm/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-table/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-utils/node_modules',
  '/Users/pomek/Projects/ckeditor/ckeditor5/external/...'
]
```

**Comment by Reinmar** [comment]
It works locally for me. And the code looks reasonable. I didn't test it in doc builder, though as I don't have it set up.

If you tested it @pomek or can do that, feel free to merge this PR.

**Review by Reinmar — APPROVED** [review]

**Pull request merged**
