### PR TITLE
Refreshed the React integration guide

### LINKED ISSUE #8062: create-react-app@3 in React component docs
## 📝 Provide a description of requested docs changes

CRA@3 after ejecting creates single webpack config file. We could cover that case in our documentation – https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html.

We should point that webpack creates the single file and it requires the same list of changes that CRA@2 after ejecting.

### LINKED ISSUE #8105: Create react app 1 guide is outdated
## 📝 Provide a description of requested docs changes

Currently if you go to [create-react-app@1 integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#using-create-react-app1) and try to follow the steps, you don't get the described results. 
`package.json` does not include any scripts, so you cannot `npm run eject`. Even if you try to run it with `node_modules/.bin/react-scripts eject` it ends with an error and the project does not contain the files that are described in the guide.

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs: Refreshed the React integration guide. Removed unsupported version of `create-react-app` (`1.x` and `2.x`). Added a section about importing build produced by Online Builder. Closes #8062. Closes #8105.

---

Do not paste it to commit merge:

Closes https://github.com/cksource/ckeditor5-internal/issues/190.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Comment by pomek** [comment]
I also updated the guide ToC.

New:

image

Before:

image

**Review by godai78 — APPROVED** [review]
I have reviewed these here changes proposed and found them worthy of acceptance. I added a few minor fixes, standardized a few phrases and did some other minor changes, but the overall work done in this here guide is impressive.

**Comment by AnnaTomanek** [comment]
I corrected the guide text.

I have some doubts about the placement of the "Integrating a build from the online builder" part - why is it a subsection of the Quick start part if there is the Customizing the builds section below (and its mentioned there), but also, the "Integrating CKE5 built from source" section further below - at a higher level?

**Comment by pomek** [comment]
@AnnaTomanek, we can swap the order.

**Review by godai78 — APPROVED** [review]
I approve this change as well, as this is a good change, too.

**Comment by AnnaTomanek** [comment]
I rearranged the order a bit by putting online builder before building from source so they now go from the least complicated to the most complicated approach. Other than that, I'm happy with the article as it is now.

**Review by AnnaTomanek — APPROVED** [review]

**Pull request merged**
