### PR TITLE
Fix focus after showing captions

### LINKED ISSUE #12165: Image caption button doesn't place focus into editable after execution
## 📝 Provide detailed reproduction steps (if any)

1. Open sample in https://codepen.io/mlewand/pen/VwXMdrL (uses decoupled editor with image caption)
2. Focus the editable area.
3. Select image on the right hand side.
4. Press alt+f10 to move the focus to the toolbar.
5. Press space to execute image caption command.

### ✔️ Expected result

The selection should be moved to editable just like in bold, underline, blockquote or any other command that modifies the content.

### ❌ Actual result

Focus remains in the toolbar which is inconsistent with other UI.

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by Dumluregn**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (image,table): Fix focus after showing captions. Closes #12165.

### CODE REVIEW

**Review by mlewand — COMMENTED** [review]
Let's add unit test for this. It's enough to stub focus method on editing view.

**Comment by Dumluregn** [comment]
I'm not sure about the target branch, I guess it should be changed to `master`? That would mean that the type in commit message should be changed from `internal` to `fix` as the buggy behaviour will be released.

**Review by mlewand — APPROVED** [review]
LGTM 👍

**Comment by mlewand** [comment]
I changed merge msg type to fix, since it will land in next release.

Let's just change the target branch back to `master`.

**Comment by mlewand** [comment]
@Dumluregn there's some accidental artifact that slipped by:

https://github.com/ckeditor/ckeditor5/pull/12176/files#diff-6f4501e5e045c66e9dacc0c8c6ea711b4048faff715a5f61915f63db20e7ae40R59

**Comment by Dumluregn** [comment]
> [**@Dumluregn**](https://github.com/Dumluregn) there's some accidental artifact that slipped by (`<figure class="table">`):
> 
> [https://github.com/ckeditor/ckeditor5/pull/12176/files#diff-6f4501e5e045c66e9dacc0c8c6ea711b4048faff715a5f61915f63db20e7ae40R59](https://github.com/ckeditor/ckeditor5/pull/12176/files#diff-6f4501e5e045c66e9dacc0c8c6ea711b4048faff715a5f61915f63db20e7ae40R59)

Sorry for not mentioning it in the PR comment. This is an intentional typo fix. Someone copied this test from the `imageCaption` to `tableCaption` and forgot to change the class name.

**Review by oleq — APPROVED** [review]

**Pull request merged**
