### PR TITLE
Migration to 28.0.0

### LINKED ISSUE #9759: Create the migration guide to 28.0.0
## 📝 Provide a description of requested docs changes

It should cover changes with DLL (https://github.com/ckeditor/ckeditor5/pull/9681), and it may explain changes made in the following commits:

- https://github.com/ckeditor/ckeditor5/commit/37f1699760695c58b2da0a30fee1579a7a38236d
- https://github.com/ckeditor/ckeditor5/commit/efe5e5744c83b910c06b8b763ae177b617a33eb2
- https://github.com/ckeditor/ckeditor5/commit/5e1328b670badc9d0abb8a56882d4158294b1386

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Internal: Added the migration guide to v28.0.0. Closes #9759.

### CODE REVIEW

**Comment by pomek** [comment]
image

**Comment by Reinmar** [comment]
I pushed some improvements. Other than that it LGTM.

**Comment by Reinmar** [comment]
cc @godai78 ready for your review

**Comment by pomek** [comment]
I'll merge the PR. I need to verify whether links between the changelog and the migration guide are defined correctly.

**Comment by pomek** [comment]
LGTM.

**Pull request merged**
