### PR TITLE
code-blocks.md: Fix typos

### PR DESCRIPTION
**Pull request by cclauss**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Type: Message. Closes #000.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Comment by mlewand** [comment]
Thanks for the PR. @cclauss, please be sure to sign the CLA.

Regarding the change: although "indentation" seems much more natural to me as well, I was surprised to learn that "indention" is recognized as a valid word too.

Proposed "indentation" is also more widely used in the internet according to Google search (39M vs 1.6M matches).

I'll let @godai78 to verify this.

**Review by godai78 — APPROVED** [review]

**Comment by cclauss** [comment]
CLA: There is no intellectual property in fixing typos.  ;-)

**Comment by godai78** [comment]
Maybe there isn't, but as this is an Open Source project we have a strict policy to keep everything clear license-wise.

**Comment by Reinmar** [comment]
@cclauss is right :) We don't need CLA for such changes.

**Pull request merged**
