### PR TITLE
Add support for dai.ly urls in MediaEmbedEditing

### PR DESCRIPTION
**Pull request by Kocal**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Feature: Add support for short Dailymotion URLs (`dai.ly`) in media-embed. 

---

### Additional information

Short Dailymotion URLs can be found in you share the video through the dedicated sharing button:

Example: https://www.dailymotion.com/video/x8ks8y1 
image
image

### CODE REVIEW

**Comment by Kocal** [comment]
I can understand, but I didn't find anything in the [documentation](https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html), like extending an **existing** media provider to add more URLs

**Comment by Witoso** [comment]
There's [extending](https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html#extending-media-providers), [removing](https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html#removing-media-providers), [overriding](https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html#overriding-media-providers). I am not sure if I understand your case.

**Comment by Kocal** [comment]
It's more something like extending a given mediaProvider to add another supported URL. 

By doing something like:
```js
{ 
  mediaEmbed: {
    extraProviders: [
      { 
        name: 'dailymotion',
        url: [/^dai.ly\/(\w+)/],
      }
    ]
  }
}
```

I was expecting my `dailymotion` configuration to be merged with the one from the MediaEmbed plugin itself, so maintaining would be easier/safer in our end-user side: 

But it didn't work as I thought, I had to duplicate the `dailymotion` configuration from the MediaEmbed plugin, and add it like this:
```js
{ 
  mediaEmbed: {
    extraProviders: [
      { 
        name: 'dailymotion',
        url: [/^dai.ly\/(\w+)/],
        html: (match) => {
          const id = match[1];
          return (
            '<div style="position: relative; padding-bottom: 100%; height: 0; ">' +
            `<iframe src="https://www.dailymotion.com/embed/video/${id}" ` +
            'style="position: absolute; width: 100%; height: 100%; top: 0; left: 0;" ' +
            'frameborder="0" width="480" height="270" allowfullscreen allow="autoplay">' +
            '</iframe>' +
            '</div>'
          );
        },
      }
    ]
  }
}
```

**Comment by Witoso** [comment]
Ok, gotcha. I forgot we actually had `dailymotion` :facepalm:  @arkflpc could you take a look and merge it?

**Review by niegowski — APPROVED** [review]

**Pull request merged**
