### PR TITLE
Changed the color of the text (icon) of an active button to improve contrast

### LINKED ISSUE #1405: The state of toggle buttons is conveyed only via color with low contrast
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html

## 📋 Steps to reproduce

1. Press "Bold" button.

## ✅ Expected result

The contrast between the button's background and toolbar is at least 3:1.

## ❎ Actual result

The contrast between the button and toolbar is around 1.28:1

### LINKED ISSUE #11842: Button focus indication is barely visible
## 📝 Provide detailed reproduction steps (if any)

1.  Open [full-featured editor](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html).
2.  Navigate to Font size/Font family button using keyboard.
3.  Open the dropdown and navigate down/up using arrow keys.

### ✔️ Expected result

Selection is more visible.

### ❌ Actual result

Selection is barely visible.

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (theme-lark,ui): Changed the color of the pressed button text or an icons to improve contrast. Improved the border contrast of inputs and editing roots. Improved the look of the focused state of switch buttons. Closes #1405. Closes #11842.

---

### Additional information

image
image
image

### CODE REVIEW

**Review by Comandeer — COMMENTED** [review]
Contrasts look good:

*   contrast between button's icon and button's background in on state: [4.4](https://contrast-ratio.com/#%23166fd4-on-%23e7f4fe),
*   contrast between button's icon and toolbar background: [4.93](https://contrast-ratio.com/#%23166fd4-on-%23FFFFFF),
*   contrast between focus indicator and the button's background in focused on state: [3.25](https://contrast-ratio.com/#hsl%28208%2C%2079%25%2C%2051%25%29-on-%23e7f4fe).

However, I can think of two optional enhancements:

*   making the contrast between off and on state at least 3:1 – now the contrast between off icon and on icon is [2.56](https://contrast-ratio.com/#%23166fd4-on-%23333333),
*   making sure that the area which contrast is changed has proper size (at least 1px perimeter of the button). (WCAG 2.2.)

These requirements are part of WCAG 2.2 new [SC 2.4.11 Focus Appearance](https://w3c.github.io/wcag/guidelines/22/#focus-appearance) and, as the name suggests, are applied only to focus. Yet, they seem sensible as an enhancement also for other states, including the on/off one (especially the one with the contrast ratio between off and on state).

**Comment by oleq** [comment]
Lesson learned: color profile of the display affect lots of color measurement tools. And that includes Digital Colour Meter tool by Apple (and others). When using them, make sure to has sRGB profile set in your system for accurate measurement.

**Comment by oleq** [comment]
Let's have another round of review!

**Review by Comandeer — APPROVED** [review]
Tested on "Bold" button:

* contrast between button's icon and button's background in "on" state: [3.75](https://contrast-ratio.com/#%232977ff-on-%23f0f7ff),
* contrast between button's icon and toolbar's background in "on" state: [4.05](https://contrast-ratio.com/#%232977ff-on-%23FFFFFF),
* contrast between button's icon in "on" state and button's icon in "off" state: [3.11](https://contrast-ratio.com/#%232977ff-on-%23333333),
* contrast between button's background in "on" state and focus indicator: [3.81](https://contrast-ratio.com/#%233779eb-on-%23f0f7ff).

LGTM!

**Comment by oleq** [comment]
The comparison of recent changes

| Before | After | Notes |
| --- | --- | --- |
| 


 | 



 |   |
| 



 | 



 |   |
| 



 | 



 | New style of a focused switch |
| 



 | 



 |   |
| 



 | 



 | Softer borders around toolbars (and other boxes) |

**Comment by oleq** [comment]
<table><tbody><tr><td><figure class="image"></figure></td><td><figure class="image"></figure></td></tr></tbody></table>

**Review by Comandeer — COMMENTED** [review]
Made some more tests of contrast.

**Tested on "Bold" button:**

* contrast between button's icon and toolbar's background in "off" state: [12.63](https://contrast-ratio.com/#%23333333-on-%23FFFFFF),
* contrast between toolbar's background and focus indicator for button in "off" state (as button does not have its own background): [4.12](https://contrast-ratio.com/#%233779eb-on-%23FFFFFF).
* contrast between button's icon and button's background in "on" state: [3.75](https://contrast-ratio.com/#%232977ff-on-%23f0f7ff),
* contrast between button's icon and toolbar's background in "on" state: [4.05](https://contrast-ratio.com/#%232977ff-on-%23FFFFFF),
* contrast between button's icon in "on" state and button's icon in "off" state: [3.11](https://contrast-ratio.com/#%232977ff-on-%23333333),
* contrast between button's background in "on" state and focus indicator: [3.81](https://contrast-ratio.com/#%233779eb-on-%23f0f7ff).

**Tested on "Link URL" input in Link dialog:**

* contrast between focus indicator and background color: [4.12](https://contrast-ratio.com/#%233779eb-on-%23FFFFFF),
* contrast between input border and background in onfocused state: [**1.69**](https://contrast-ratio.com/#%23c7c7c7-on-%23ffffff),
* contrast between border in unfocused and focused state: [**2.43**](https://contrast-ratio.com/#%23c7c7c7-on-%233779eb).

**Tested on "Side image" button in image widget balloon toolbar:**

* contrasts and colors are the same as "Bold" button – everything's ok here.

**Tested on editable root border:**

* contrast between focus indicator and surrounding color (page's background in case of docs): [4.12](https://contrast-ratio.com/#%233779eb-on-%23FFFFFF),
* contrast between root editable border and page's background: [**1.37**](https://contrast-ratio.com/#%23dadce0-on-%23FFFFFF),
* contrast between border in unfocused and focused state: [**3**](https://contrast-ratio.com/#%23dadce0-on-%233779eb).

Values for editable borders depend on context! They will behave different if the page's background is not set to white.

**Tested on "Format" dropdown items:**

* contrast between background in unselected and selected item: [4.05](https://contrast-ratio.com/#%23ffffff-on-%232977ff),
* contrast between focus indicator and unselected item's background: [4.12](https://contrast-ratio.com/#%233779eb-on-%23ffffff),
* contrast between focus indicator and selected item's background: [4.05](https://contrast-ratio.com/#%23ffffff-on-%232977ff).

I have a doubt about the last case (focus indicator on selected item's background). White, indeed, has enough contrast ratio against the item's background. But at the same time – white is also the background color of the whole dropdown panel. The white border around the item is separated from panel's white background only by a box shadow which has a [contrast ratio of 1.33](https://contrast-ratio.com/#%23ffffff-on-%23cae1fc) against the white background. IMO it's a fail (Understanding WCAG 2.1 provides [some rationale](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html#:~:text=If%20the%20focus%20indicator%20changes%20the%20border%20of%20the%20component%20within%20the%20visible%20boundary%20it%20must%20contrast%20with%20the%20component.): the inner border must contrast with both component and background). 

**Conclusion**

There are some cases which can benefit from better contrast ratios:

* "Link URL" input:
  * contrast between input border and background in onfocused state: [**1.69**](https://contrast-ratio.com/#%23c7c7c7-on-%23ffffff),
  * contrast between border in unfocused and focused state: [**2.43**](https://contrast-ratio.com/#%23c7c7c7-on-%233779eb),
* editable root border:
  * contrast between root editable border and page's background: [**1.37**](https://contrast-ratio.com/#%23dadce0-on-%23FFFFFF),
  * contrast between border in unfocused and focused state: [**3**](https://contrast-ratio.com/#%23dadce0-on-%233779eb),
* "Format" dropdown contrast between focus indicator and selected item.

**Comment by Reinmar** [comment]
I went through many of our documentation pages to get a feeling of how the new theme looks and I must say it feels good. Interesting that an accessibility work turns out to also be a nice refresher of the UI.

As a followup, we need a migration guide covering:

* How to bring back toolbar's background color.
* How to decolorize the active state.

Also, let's discuss today the severity of the remaining issues.

**Comment by Reinmar** [comment]
We discussed f2f the remaining issues. @Comandeer will try to sum up that discussion in details later on. The tl;dr is that  the input and editable borders there are acceptable due to other aspects.

We're going to tune those colors a bit anyway.

After that, the PR is ready to merge ❤️

**Comment by Comandeer** [comment]
The focus indicator is governed by the [Success Criterion (SC) 2.4.7 Focus Visible](https://www.w3.org/TR/WCAG21/#focus-visible). It does not specify the exact shape or type of the provided indicator. What’s more, the sufficient technique is [G149: Using user interface components that are highlighted by the user agent when they receive focus](https://www.w3.org/WAI/WCAG21/Techniques/general/G149) which includes the following example:

> When html text input fields receive focus, browsers display a blinking vertical bar at the insertion point in the text field.

Due to that, in case of inputs and editables inside CKEditor 5 application, the caret should be treated as the primary focus indicator while the outline/border around editable fields is a complementary one. Therefore it does not need to adhere to the norms defined in [SC 1.4.11 Non-text Contrast](https://www.w3.org/TR/WCAG21/#non-text-contrast) as it’s defined for “visual information required to identify user interface components and states”. In the case of the focus the state is identified by the presence of the caret.

Additionally, the low contrast ratio of input’s and editable’s borders even in onfocused state does not need to adhere to SC 1.4.11 as borders are not necessary to identify the editable user components inside CKEditor 5 instances. According to the [Understanding note for SC 1.4.11](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html#user-interface-components):

> This success criterion does not require that controls have a visual boundary indicating the hit area, but if the visual indicator of the control is the only way to identify the control, then that indicator must have sufficient contrast. If text (or an icon) within a button or placeholder text inside a text input is visible and there is no visual indication of the hit area then the Success Criterion is passed. If a button with text also has a colored border, since the border does not provide the only indication there is no contrast requirement beyond the text contrast (1.4.3 Contrast (Minimum)).

As all inputs have their respective labels generated inside the input area and the whole editable is delimited by the boundaries of the text inside it and hinted by the editor’s toolbar, there is no need for the unfocused borders to adhere to SC 1.4.11.

**Pull request merged**
