### PR TITLE
Improve docs for Angular integration by adding sections about accessing the editor and implementing Upload Adapter

### PR DESCRIPTION
**Pull request by ma2ciek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Docs: Improve docs for Angular integration by adding sections about accessing the editor and implementing Upload Adapter. Closes ckeditor/ckeditor5-angular#61.

### Additional information

I hope @AlanObject that you don't mind that I moved your changes from the original PR here, do a cleanup and fix some issues. if you have some ideas or objections about the current state of PR, please share them.

### CODE REVIEW

**Comment by ma2ciek** [comment]
@pomek, could you check these changes and tell me whether you feel OK with them?

**Comment by pomek** [comment]
Sure.

**Comment by ma2ciek** [comment]
We agreed that the sample for the image upload will be more than welcome. So I'll prepare it.

**Comment by ma2ciek** [comment]
After getting back into this forgotten PR I find implementing Upload adapter unnecessary here. The angular integration at such level isn't needed, so I'll remove that part and narrow the PR so we can finally merge it.

**Comment by Reinmar** [comment]
Thanks. It LGTM.

**Pull request merged**
