### PR TITLE
Use binary search in `insertToPriorityArray`

### PR DESCRIPTION
**Pull request by filipsobol**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (utils): Use binary search in `insertToPriorityArray()` for better performance when handling big tables.

---

Reduces the time needed to render a table in the `tableHuge` test by ~67%.

### CODE REVIEW

**Review by scofalik — DISMISSED** [review]

**Review by scofalik — APPROVED** [review]

**Comment by scofalik** [comment]
I think this change is safe enough to merge it into upcoming release @Witoso

**Comment by Witoso** [comment]
Good for me :+1: another good reason to bump the version!

**Comment by niegowski** [comment]
Does it affect the order of event listeners on the same priority? Until now, if there were multiple listeners on the same priority, then the order of registration was used. Does this PR change this?

**Comment by filipsobol** [comment]
> Does it affect the order of event listeners on the same priority? Until now, if there were multiple listeners on the same priority, then the order of registration was used. Does this PR change this?

No. You can test the previous and current implementation on the following playground by running the `node index.js` command in the console: https://stackblitz.com/edit/stackblitz-starters-86xsef

**Pull request merged**
