### PR TITLE
Fixed the "Unknown option --dev" error when building DLLs

### LINKED ISSUE #11170: Build fails with --dev flag
## 📝 Provide detailed reproduction steps (if any)

Run: `yarn dll:build --dev`

### ✔️ Expected result

Should build DLL with dev configuration

### ❌ Actual result

```
$ yarn dll:build --dev
yarn run v1.22.17
$ node ./scripts/dll/build-dlls.js --dev
🛠️️  Development mode is active.

📍 Creating the base DLL build...

[webpack-cli] Error: Unknown option '--dev'
[webpack-cli] Did you mean '--env'?
[webpack-cli] Run 'webpack --help' to see available commands and options

```
## 📃 Other details

* OS: MacOS
* Node version: v16.10.0
* Yarn version: 1.22.17

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix: Fixed the "Unknown option --dev" error when building DLLs. Closes #11170.

### CODE REVIEW

**Comment by lauriii** [comment]
How should this work in relation with https://github.com/ckeditor/ckeditor5/blob/master/scripts/dll/webpack.config.dll.js#L16?

**Comment by pomek** [comment]
Nice catch. Except for the changed and mentioned files, I should also update all `webpack.config.js` files.

**Comment by pomek** [comment]
It should work properly now.

**Comment by lauriii** [comment]
It's working now 👍 Thank you @pomek!

**Review by psmyrek — APPROVED** [review]
LGTM 🎉

**Review by przemyslaw-zan — APPROVED** [review]
LGTM

**Pull request merged**
