### PR TITLE
Removed the confirmation of mention selection by using the space key

### LINKED ISSUE #6394: Mention: do not confirm selection on "space"
## 📝 Provide a description of the improvement

Currently, it is cumbersome to simply type text that uses the mention marker but is not in the mention list, in some cases.

For example, suppose this:

*   My app loads just the last 500 issue numbers of CKEditor 5 in the mention list.
*   Let's say we have 1200 issue is total -> therefore issues from 700 to 1200 are loaded.
*   My app uses hash (#) as the marker to mention issues.
*   I want to mention issue 1. I type `#1`.
    *   At this point, the mention list is shown. As the list is filtered by what I typed, I see issues 1000, 1001, 1002... with issue 1000 pre-selected.
*   I want to continuer typing after `#1`, so I hit `space`.
    *   **Issues**: my typed `#1` is replaced with `#1000`. That's because `space` was used to confirm my selection in the list, which is clearly not what I wanted.

This seems to be caused by this line, which tells me that even `tab` could be used to confirm my select :thinking:   
https://github.com/ckeditor/ckeditor5-mention/blob/9a514ccb0dc8b595100fd4459a82fa67cc329d1d/src/mentionui.js#L124

I propose to allow confirming the selected item by using the `enter` key, exclusively.

## 📃 Other details

*   CKEditor version: v17.0.0
*   Installed CKEditor plugins: mention

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by fredck**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Other (mention): The `space` keys is not anymore used to confirm a mention selection from the list. Closes #6394.

---

### Additional information

Original PR: ckeditor/ckeditor5-mention#92

### CODE REVIEW

**Comment by pammann-work** [comment]
@fredck 
Why not doing the same with keyCodes.space as with keyCodes.esc, calling `this._hideUIAndRemoveMarker();`? e.g. in github when using the @, if you enter space after the @, the menu goes away....

**Comment by fredck** [comment]
> Why not doing the same with keyCodes.space as with keyCodes.esc, calling `this._hideUIAndRemoveMarker();`? e.g. in github when using the @, if you enter space after the @, the menu goes away....

@pammann-work, I'm not sure I've understood this. With the provided patch, if you enter space after @ the menu goes away, exactly as you described. In fact, the final behavior will match exactly what you see in GitHub. Am I missing something?

**Comment by pammann-work** [comment]
@fredck, good to hear to it will work like in GitHub. I was just looking at the code changes and did not try it out. Thanks for your confirmation.

**Comment by robjbrain** [comment]
I came to this issue by following a path of closed issues 
https://github.com/ckeditor/ckeditor5/issues/4665#issuecomment-633198527
https://github.com/ckeditor/ckeditor5-mention/pull/92#issuecomment-634623779

The original request was that we be able to mention names that have a space in them e.g. "John Doe" rather than closing the mention dialog after typing the space in "John ".

I can see that this change was merged and I can see the updated code in my node_modules directory so i'm definitely up to date but the functionality is still the same, the menu is closed when a space is typed.

Is there a solution that prevents the menu from closing on a space?

**Comment by EricPaulson** [comment]
This PR does not solve the problem. As soon as I press the spacebar, the mention dropdown disappears. This is not how any user would expect this feature to work.

**Pull request merged**
