### PR TITLE
Fix for Show Blocks in Multi-Root editor.

### LINKED ISSUE #15969: Icons with Show Blocks element names missing when using the Multi-Root editor type
## 📝 Provide detailed reproduction steps (if any)

1. Create an editor build that utilizes the Multi-Root editor alongside Show Blocks
2. Toggle the plugin

### ✔️ Expected result

You should be able to see the element names (`H2`, `P`, etc.) in the upper left corner of the blocks:

image

### ❌ Actual result

Only the outline is visible, the names are missing:

image

### ❓ Possible solution

This issue was initially reported by one of our customers via Zendesk. You can find additional information about the issue in [the ticket](https://ckeditor.zendesk.com/agent/tickets/88641
).

## 📃 Other details

* Browser: cross-browser
* OS: cross-OS
* First affected CKEditor version: N/A
* Installed CKEditor plugins: Show Blocks

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by pszczesniak**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix(show-blocks): `Show Blocks` should now works as expected in the Multi-Root editor. Closes #15969.

---

### Additional information

_In Multi-Root `dir="ltr/rtl"` is on same level that CSS class `.ck-show-blocks`_.

### CODE REVIEW

**Review by gorzelinski — APPROVED** [review]
Icons work now. I've added a tiny spelling suggestion.

**Comment by charlttsie** [comment]
## Block names in multi-root don't display on mobile
### Steps
1. Open e.g. [showblocks-in-multirooteditor.html](http://fake.ckeditor.com:8125/ckeditor5-show-blocks/tests/manual/showblocks-in-multirooteditor.html) on a mobile device (iOS or Android)
2. Enable show blocks

### Result
Block names are not visible - as on desktop before the fix:

IMG_7991

**Comment by charlttsie** [comment]
We've finished testing together with @kubaklatt and @mabryl and have found one issue that is reported above, where block names don't show on specific devices. Outside of these cases, the initial issue doesn't reproduce and there are no regressions either 🎉

**Comment by pszczesniak** [comment]
@charlttsie Thank You!

Got one question - could you check browsers and versions of them and write it also here??

I've tested `Xiaomi Redmi Note 10S` on Lambda and there is Android11 and Chrome 87 - a bit outdated version. Maybe others have same or similar case?

**Comment by Witoso** [comment]
Let's go forward with this, if it works for latest browsers than LGTM.

**Pull request merged**
