### PR TITLE
NIM migration guide fixes

### PR DESCRIPTION
**Pull request by godai78**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: various small fixes in the NIM migration guides.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Review by filipsobol — APPROVED** [review]

**Comment by godai78** [comment]
> I propose to change the translations to `premiumFeaturesTranslations`.

Doesn't it, like, require code changes first?

**Comment by Witoso** [comment]
No, it's only snippets, change: https://stackblitz.com/edit/iqtclr-bh49xh?file=index.html,main.js

**Comment by godai78** [comment]
All snippets that use it and all demos globally i docs?

**Comment by Witoso** [comment]
I think we would need to swap `commercialTranslations` everywhere to be coherent.

**Comment by godai78** [comment]
Do we merge it?

**Pull request merged**
