### PR TITLE
Removed warning about CRA@2

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Docs: Removed warning about CRA@2. See https://github.com/ckeditor/ckeditor5-react/issues/40#issuecomment-456368847.

### CODE REVIEW

**Comment by ma2ciek** [comment]
Without ejecting the SVGs are broken with our beloved error:

```
TypeError: Cannot read property 'getAttribute' of null
at IconView._updateXMLContent (iconview.js:121)
    at IconView.render (iconview.js:94)
	...
```

**Comment by pomek** [comment]
> Is it possible to run react app without ejecting config now?

That's the goal of changing our sources…

> Without ejecting the SVGs are broken with our beloved error:

The later in the same documentation:

> **The configuration needs to be ejected in order to be able to customize webpack configuration.** To build CKEditor 5 from source you must load inline SVG images and handle CKEditor 5's CSS as well as correctly minify the ES6 source.

You can use ready-to-use builds without ejecting.

**Comment by pomek** [comment]
But if you would use CKEditor 5 Framework, you must eject the configuration.

**Comment by pomek** [comment]
Or create a new build and attach it to the React Component. Both ways are described in the documentation.

**Pull request merged**
