### PR TITLE
Adopt Github conventions in HTML -> MD conversion

### PR DESCRIPTION
**Pull request by zm-cttae**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Closes ckeditor/github-writer#438.
Adopt Github conventions in HTML -> MD conversion.

---

### Additional information

[CommonMark](https://commonmark.org/help/) is so popular compared to [Josh Gruber's original Markdown spec](https://daringfireball.net/projects/markdown/syntax) that we should favor it.

### CODE REVIEW

**Comment by arkflpc** [comment]
As it currently stands, the plugin emits `*` for unordered lists, which is a valid way to denote unordered lists ([CommonMark](https://commonmark.org/help/) lists both as valid too). The change to use `-` instead of `*` seems to be more of a preference than a requirement or an improvement in functionality.
Could you please clarify what advantages this change would bring?

**Comment by zm-cttae** [comment]
The output of the editor would look the same as the Github help pages, the CommonMark reference's sample code blocks & the vast majority of Markdown files on GitHub.

**Comment by arkflpc** [comment]
Thank you for your response and providing the rationale behind the proposed change.

1. It would be great if you could create an issue on the repository and describe the change and its rationale there. This will allow for a more comprehensive discussion and provide a central place for tracking the proposed enhancement.
2. Currently, the pull request lacks test coverage. To contribute to the project, it would be helpful to follow [the contributing guidelines](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/contributing.html), which typically include adding tests to ensure the stability and correctness of the code changes.
3. While your contribution is appreciated, the suggested change is considered a breaking change (BC) since it alters the default behavior. To address this, it would be beneficial if you could add this change as a configuration option that can be modified, rather than altering the default behavior outright. This approach allows users to choose the rendering style they prefer.

**Comment by zm-cttae** [comment]
All good feedback. I will put a formal writeup in the existing issue.

**Comment by zm-cttae** [comment]
Writeup is done.

**Pull request closed without merging**
