### PR TITLE
Update of an icon for Image text alternative.

### PR DESCRIPTION
**Pull request by pszczesniak**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Other (core): New icon for Image text alternative button. 
Closes https://github.com/cksource/ckeditor5-commercial/issues/5640.
Closes https://github.com/ckeditor/ckeditor5/issues/12410

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Review by niegowski — COMMENTED** [review]
Is the new icon optimized? I can see `width` and `height` attributes. Is it correct or should be removed?

**Comment by pszczesniak** [comment]
> Is the new icon optimized? I can see `width` and `height` attributes. Is it correct or should be removed?

Noted in same time as You @niegowski :smile: Fixed.

**Review by mmotyczynska — APPROVED** [review]

**Review by godai78 — APPROVED** [review]
Works fine.

**Comment by Witoso** [comment]
Please make sure to land information about this in the migration guide, cc @godai78.

**Comment by godai78** [comment]
Noted down on the list.

**Pull request merged**
