### PR TITLE
Make three Enter clicks necessary at the end of a code block to escape it

### PR DESCRIPTION
**Pull request by marcellofuschi**
Improvement of the `CodeBlock` feature, described in https://github.com/ckeditor/ckeditor5/issues/6682.

Closes https://github.com/ckeditor/ckeditor5/issues/6682.

### CODE REVIEW

**Comment by marcellofuschi** [comment]
Just noticed that this change also needs the GIFs in the docs to be changed.

**Comment by Reinmar** [comment]
Wow, thanks for such a complete PR :) I'll pass it to the team for a review.

**Comment by arkflpc** [comment]
The code looks great and seems to work as intended. I don't know if it should behave the same way at the beginning of the block, though. It doesn't solve the main issue (code snippets rarely start with a blank line) and makes the feature less intuitive (despite being well documented).

@oleq, @Reinmar - what are your opinions?

**Comment by Reinmar** [comment]
I agree. The change of behavior at the beginning of a code block will make it less intuitive. Most likely – too unintuitive.

As for the change at the end of a code block – I think it's a good direction. It should be more intuitive than Shift+Enter that we require currently.

I'm curious about @oleq's opinion still.

**Comment by oleq** [comment]
> I agree. The change of behavior at the beginning of a code block will make it less intuitive. Most likely – too unintuitive.

> I don't know if it should behave the same way at the beginning of the block, though. It doesn't solve the main issue (code snippets rarely start with a blank line) and makes the feature less intuitive (despite being well documented).

I agree with you, this would degrade the UX and should be excluded. 

> As for the change at the end of a code block – I think it's a good direction. It should be more intuitive than Shift+Enter that we require currently.

It makes sense at the end of the code block 👍

**Pull request merged**
