### PR TITLE
Table caption feature

### LINKED ISSUE #3204: Implement table captions
Tables need to be captioned. Most likely, we can implement this just like in the image feature. It'd be also good to extract pieces of shared logic so #1065 is resolved.

Related comments:

*   https://github.com/ckeditor/ckeditor5/issues/610#issuecomment-339661146
*   https://github.com/ckeditor/ckeditor5-table/issues/51#issuecomment-397245583

---

If you'd like this feature implemented, please react with :+1: to this post.

### LINKED ISSUE #9084: [Table Caption] Handle all caption conversions

### PR DESCRIPTION
**Pull request by niegowski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Feature (table): Added support for captions (`figure > figcaption + table` and `table > caption`). Closes #3204.

...

---

### Additional information

This is a feature branch for aggregating partial PRs.

### CODE REVIEW

**Comment by FilipTokarski** [comment]
Not sure if bug, but seems to me like a bit incoherent UX.
  
## Steps to reproduce:
1. Add table
2. Toggle caption on
3. Blur the table

## Expected:
Caption placeholder disappears - just like in image.

## Actual:
Caption placeholder is visible

## Screencast:

https://user-images.githubusercontent.com/34380544/112611168-c7aafe00-8e1d-11eb-9176-7e1ed99457c9.mp4

**Comment by FilipTokarski** [comment]
## Steps to reproduce:
1. Add table
2. Toggle caption on
3. Add some text
4. Toggle caption off

## Expected:
All icons in the table balloon toolbar are visible.

## Actual:
Only caption icon is visible, you need to click again on the table to see the rest of them.

## Screencast:

https://user-images.githubusercontent.com/34380544/112611723-7c451f80-8e1e-11eb-87d3-57c62ea43264.mp4

**Comment by LukaszGudel** [comment]
### Steps:
1. Add table caption and focus table caption field
2. Try to add row or column

### Result:

https://user-images.githubusercontent.com/58658048/112617097-d0530280-8e24-11eb-97e7-5d0467af660d.mp4

### Errors:
```
insertrowcommand.js:78 Uncaught TypeError: Cannot read property 'findAncestor' of undefined
    at InsertRowCommand.execute (insertrowcommand.js:78)
    at InsertRowCommand.<anonymous> (observablemixin.js:258)
    at InsertRowCommand.fire (emittermixin.js:194)
    at InsertRowCommand.<computed> [as execute] (observablemixin.js:262)
    at CommandCollection.execute (commandcollection.js:69)
    at ClassicEditor.execute (editor.js:292)
    at DropdownView.<anonymous> (tableui.js:258)
    at DropdownView.fire (emittermixin.js:194)
    at fireDelegatedEvents (emittermixin.js:684)
    at ListItemView.fire (emittermixin.js:217)


selection.js:112 Uncaught TypeError: Cannot read property 'findAncestor' of undefined
    at getColumnIndexes (selection.js:112)
    at InsertColumnCommand.execute (insertcolumncommand.js:76)
    at InsertColumnCommand.<anonymous> (observablemixin.js:258)
    at InsertColumnCommand.fire (emittermixin.js:194)
    at InsertColumnCommand.<computed> [as execute] (observablemixin.js:262)
    at CommandCollection.execute (commandcollection.js:69)
    at ClassicEditor.execute (editor.js:292)
    at DropdownView.<anonymous> (tableui.js:258)
    at DropdownView.fire (emittermixin.js:194)
    at fireDelegatedEvents (emittermixin.js:684)
```

**Comment by FilipTokarski** [comment]
## Steps to reproduce
1. Add some caption text
2. Hide caption
3. Drag & drop table to different position OR cut/paste it somewhere

## Question:
If you just toggle caption on/off, the text is retained. If you D&D or cut/paste the text is lost. What is the expected behaviour here?  
As an end user, if I see that the text is retained regardless of caption being on or off, I would assume that if I move it to new position with caption off, the text would be retained as well.

## Screencast:

https://user-images.githubusercontent.com/34380544/112623463-adc4e780-8e2c-11eb-8b82-e23cb65976b9.mp4

**Comment by FilipTokarski** [comment]
Isn't the placeholder text too close to the left border?

https://user-images.githubusercontent.com/34380544/112627002-4eb5a180-8e31-11eb-870a-dc353ffecccd.mp4

**Comment by FilipTokarski** [comment]
You can align caption text by toggling the caption off and then applying alignment ( but works only for left and center ):

https://user-images.githubusercontent.com/34380544/112628959-f46a1000-8e33-11eb-8f9e-6f24406170a4.mp4

Not sure how to treat this. Should the caption text alignment be completely disabled, or should the user have a possibility to do this normally?

**Comment by maxbarnas** [comment]
> You can align caption text by toggling the caption off and then applying alignment ( but works only for left and center ):

Nice catch!

> Not sure how to treat this. Should the caption text alignment be completely disabled, or should the user have a possibility to do this normally?

@Mgsy do you know how it works in the new image caption? I guess it should behave the same way.

**Comment by FilipTokarski** [comment]
Should navigating with keyboard into fake caret trigger caption toolbar icon visibility?

https://user-images.githubusercontent.com/34380544/112637410-6c3d3800-8e3e-11eb-8d68-ea0628170514.mp4

**Comment by Mgsy** [comment]
> [**@Mgsy**](https://github.com/Mgsy) do you know how it works in the new image caption? I guess it should behave the same way.

As I can see, the alignment is completely disabled for block images with and without the caption.

**Comment by maxbarnas** [comment]
@FilipTokarski
> Only caption icon is visible, you need to click again on the table to see the rest of them.

It's because you are seeing the table toolbar instead of a content toolbar. Not a bug, just a weird configuration.

> Drag & drop table to different position OR cut/paste it somewhere

Created a bug for that, as it is a more general problem: https://github.com/ckeditor/ckeditor5/issues/9368

> Isn't the placeholder text too close to the left border?

Fixed! 🎉 

> You can align caption text by toggling the caption off and then applying alignment ( but works only for left and center ):

Another issue filed for that: https://github.com/ckeditor/ckeditor5/issues/9369

> Should navigating with keyboard into fake caret trigger caption toolbar icon visibility?

Again, if the table toolbar is configured, it will show buttons once the table is selected. It's a case of weird configuration. Everything as expected.

@LukaszGudel 
> insertrowcommand.js:78 Uncaught TypeError: Cannot read property 'findAncestor' of undefined
>     at InsertRowCommand.execute (insertrowcommand.js:78)
> ...

Fixed! :tada:

**Comment by FilipTokarski** [comment]
I did some testing today and it looks ok, works also with CF 👍

**Pull request merged**
