### PR TITLE
[Docs] Do not center math equations and chemical formulas

### LINKED ISSUE #2080: Docs styling breaks Mathtype equation display
## Is this a bug report or feature request?

🐞 Bug report

## 💻 Version of CKEditor

CKEditor v5 @ 12.4.0

## 📋 Steps to reproduce

Our [Mathtype feature guide](https://ckeditor.com/docs/ckeditor5/latest/features/mathtype.html) has CSS that applies `display:block` (and other goodies) to all images in the content.

Images produced by the Mathtype plugin are **inline**, but with this CSS they're displaying as blocks.

Somehow we missed it before 🙈

## ✅ Expected result

image

## ❎ Actual result

image

image

---

If you'd like to see this fixed sooner, add 👍 to this post.

### PR DESCRIPTION
**Pull request by dkonopka**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Docs: Do not center math equations and chemical formulas. Closes #2080.

---

### Additional information

http://127.0.0.1:8080/build/docs/ckeditor5/12.4.0/features/math-equations.html

Screenshot 2019-10-02 at 16 48 06

### CODE REVIEW

**Comment by dkonopka** [comment]
Good catch! Fixed already 🔥

**Comment by mlewand** [comment]
@Mgsy Can I ask you to verify whether it doesn't break images in any other samples? What basically happened here is that images in `.live-snippet` elements are no longer treated as blocks (but instead area inline-block, as in HTML standard).

The reason for adding display block was probably to get a nice full width images in our articles content.

**Comment by Reinmar** [comment]
R- for now due to https://github.com/ckeditor/ckeditor5/issues/2080#issuecomment-537905875

**Comment by mlewand** [comment]
Rebased the branch onto latest `master`

**Comment by mlewand** [comment]
Rebased once again onto latest `master` branch. Looks fine and the #1874 is no longer bugging us 👍

**Comment by mlewand** [comment]
@ckeditor/qa-team Gents can I ask you to do some post-merge verification to ensure that images in samples are displayed correctly? I gave it some testing, but would like to have QA see it too.

What this PR affects is all the image elements ( `` ) within `.live-snippet` (so basically editors in our samples).

Some scenarios that I can see worth testing include:

*   mathtype equation
*   pasting an image
*   pasting embedded content that incorporates an image

**Comment by FilipTokarski** [comment]
I checked it and didn't find any new bugs, it seems to work fine 👍

**Pull request merged**
