### PR TITLE
Paste from Office should not break the list on the following blocks in the same list item or deduce a start attribute for a split list

### LINKED ISSUE #11210: Paste from Office should deduce start attribute value based on HTML passed from MS Word document / List start attribute / List break when content between them (table, image, etc.)
## 📝 Provide detailed reproduction steps (if any)

1.  Open attached MS Word file ([cke paste example.zip](https://github.com/ckeditor/ckeditor5/files/8001632/cke.paste.example.zip)) and paste it into CKEditor 4 sample - https://ckeditor.com/docs/ckeditor4/latest/examples/pastefromword.html
2.  Next paste the same content into https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html

### ✔️ Expected result

HTML lists despite being separated by other tags (in MS Word this is one list but in HTML these will be multiple lists) should keep the numbering just like in MS Word document.

### ❌ Actual result

CKEditor 4 does its job  
 

obraz

but CKEditor 5 does not  
 

obraz

It seems that CKEditor 4 is capable of deduicng start attribute value based on below HTML:

```
<p class=MsoNormal style='margin-left:36.0pt;text-align:justify;text-indent:
-36.0pt;mso-list:l2 level1 lfo2'><![if !supportLists]><span lang=EN-CA
style='font-size:10.0pt;font-family:"Arial","sans-serif";mso-fareast-font-family:
Arial'><span style='mso-list:Ignore'>3.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]><span dir=LTR></span><u><span lang=EN-CA
style='font-size:10.0pt;font-family:"Arial","sans-serif";mso-fareast-font-family:
Arial'>Test3</span></u><span lang=EN-CA style='font-size:10.0pt;font-family:
"Arial","sans-serif";mso-fareast-font-family:Arial'><o:p></o:p></span></p>
```

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: Any
*   OS: Any
*   First affected CKEditor version: from the very start
*   Installed CKEditor plugins: paste-from-office

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #15964: Nested lists sometimes broken when pasting from Word
## 📝 Provide detailed reproduction steps (if any)

1. Download the sample files: [broken-list.docx](https://github.com/ckeditor/ckeditor5/files/14479654/broken-list.docx), [working-list.docx](https://github.com/ckeditor/ckeditor5/files/14479655/working-list.docx)
2. Paste the contents into the [Paste from Office Enhanced demo](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-office-enhanced.html#demo)
3. Compare the results

### ✔️ Expected result

The subitems should be retained when pasting the contents of the first file, as is the case in CKE4, for example:

image

### ❌ Actual result

The first two subitems change into regular list items and move to the bottom of the document:

image

### ❓ Possible solution

I wasn't able to reproduce this behavior with a fresh Word file (working-list.docx). Not sure what the difference is between these two lists.

## 📃 Other details

* Browser: cross-browser
* OS: cross-OS
* First affected CKEditor version: N/A
* Installed CKEditor plugins: N/A

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by niegowski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (paste-from-office): Paste from Office should not break the list on the following blocks in the same list item or deduce a start attribute for a split list. Closes #11210, closes #15964.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Comment by Witoso** [comment]
Self-reminder to put it into the comparison [table](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-office-enhanced.html#microsoft-word). cc: @gorzelinski @godai78

**Review by pszczesniak — COMMENTED** [review]
This solution covers most of mention cases, but i have found one case when it does not.

Here is the file: [broken-list.docx](https://github.com/ckeditor/ckeditor5/files/14740349/broken-list.docx)

Screenshot 2024-03-25 at 08 41 48

Please take a look at the indentation level, first one is "flattened" (as a proper list should look like - without omit the levels of lists).

Screenshot 2024-03-25 at 08 43 46

CKE4 covers that case.

Screenshot 2024-03-25 at 08 44 03

**Comment by Witoso** [comment]
@pszczesniak  we don't have support in CKE5 for so called "skip-level" lists, so the behavior is correct :)

**Comment by pszczesniak** [comment]
@Witoso thank you for clearing that up.

**Review by pszczesniak — APPROVED** [review]

**Review by mmotyczynska — APPROVED** [review]

**Review by arkflpc — APPROVED** [review]

**Pull request merged**
