### PR TITLE
Added Localization section to the React Integration guide

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Docs: Added "Localization" section to the React Integration guide. Closes ckeditor/ckeditor5-react#58.

### CODE REVIEW

**Comment by nzaridze** [comment]
Guys check [this link ](nah)

**Comment by ma2ciek** [comment]
I'm OK with these changes.

**Comment by AnnaTomanek** [comment]
test test test

**Comment by gok9ok** [comment]
I also found [this](link).

**Comment by AnnaTomanek** [comment]
Does it work on the currently released code? If so, it should land in `stable`. Thanks to this it would be published soon without waiting for the next release...

**Comment by pomek** [comment]
Yes, it does.

**Pull request merged**
