### PR TITLE
Fixing html embed covering image inserted above with align.

### LINKED ISSUE #8324: Inserting image above html embed and changing its align will result in increasing html embed height
## 📝 Provide detailed reproduction steps (if any)

1.  insert html embed
2.  insert image above html embed
3.  change image align to left or right

### ✔️ Expected result

Image change align, but html embed will stay unchanged.

### ❌ Actual result

HTML embed increase its height covering image.

## 📃 Other details

*   Browser: Chrome, Firefox
*   OS: Windows
*   CKEditor version: 23.0.0
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by pkwasnik**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (html-embed): Fixing html embed covering image inserted above with align. Closes #8324.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Review by pomek — APPROVED** [review]
LGTM.

**Comment by pomek** [comment]
Merged as internal because the plugin is introduced in the current iteration so, in fact, we don't fix bugs between versions but the initial implementation.

**Comment by Reinmar** [comment]
I'm not sure this is the right solution. It makes the float to just not work. While using `overflow:hidden` or the new smart `display:sth` would avoid the overlap. cc @oleq

**Comment by Reinmar** [comment]
PS. I think that this is a good hotfix, but in the next iteration we could work on a better solution.

**Comment by oleq** [comment]
There are 2 parts to this story:

1.  The image style feature is wrongly configured in this sample. Presentational styles require image width to be set to something sane as per https://ckeditor.com/docs/ckeditor5/latest/features/image.html#presentational-styles. So when the image gets some realistic `width` (e.g. 30%), it looks like this:



1.  Then the only missing piece is `display: flow-root` on the raw HTML widget:

**Comment by oleq** [comment]
I created a follow-up issue for this #8332.

**Pull request merged**
