### PR TITLE
Performance improvements in CKE5

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Other (utils): Dropped using lodash `isElement()` to achieve better performance in `Rect` class.
Other (engine): Reimplemented `Position#isTouching()` to achieve better performance.

---

@oleq could you check changes in `Rect`?

@arkflpc could you check this PR from TS point of view?

### CODE REVIEW

**Comment by scofalik** [comment]
For the `Rect` changes - another option was to change constructor so that all types other than DOM are directly checked and DOM Element path is in `else`. However, DOM Element is the most common path, so we would have a few unnecessary checks before. OTOH, new `isDomElement` makes a few checks itself anyway, so, IDK. I can change this implementation if you have doubts.

**Review by arkflpc — APPROVED** [review]

**Review by oleq — COMMENTED** [review]
I'm OK with changes to the `Rect` module. I didn't run tests but I assume you did :P. 

What I don't like though is that we still use lodash `isElement` in many places. What you did here should probably land in `ckeditor5-utils/dom` as `isElement` and replace lodash imports across the project. Less code, less confusion.

**Comment by scofalik** [comment]
I wasn't sure why we are using complicated lodash method instead of something simpler. This is why I wanted to limit the scope of changes. If you are sure that this will not ruin something, I could make a change in `utils/dom`. But we can also do this in a separate ticket.

**Comment by oleq** [comment]
> I wasn't sure why we are using complicated lodash method instead of something simpler. This is why I wanted to limit the scope of changes. If you are sure that this will not ruin something, I could make a change in `utils/dom`. But we can also do this in a separate ticket.

Let's have a new issue for that then.

BTW, why `nodeType === 1` but not `nodeType === Node.ELEMENT_NODE`?

**Comment by scofalik** [comment]
Honestly, I must have taken it from [loadash `isElement()`](https://github.com/lodash/lodash/blob/master/isElement.js#L20).

**Review by oleq — APPROVED** [review]

**Pull request merged**
