### PR TITLE
Added dhivehi to RTL languages list. resolves #15976

### LINKED ISSUE #15976: Add Dhivehi language to RTL langs list
[Dhivehi language](https://en.wikipedia.org/wiki/Dhivehi_language) (codes: dv/div) is written in Thaana script which is a RTL script and thus needs to be registered as a RTL lang in ckeditor for proper directionality support.

### PR DESCRIPTION
**Pull request by Glaisher**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Other: Added dhivehi to the RTL languages list. Closes #15976.

Thanks to @Glaisher!

---

### Additional information

https://en.wikipedia.org/wiki/Dhivehi_language

### CODE REVIEW

**Comment by Witoso** [comment]
@vokiel could you check the CLA?

**Comment by vokiel** [comment]
The CLA was not signed as it was impossible to send it because of masked email. @[Glaisher](https://github.com/Glaisher) please leave us your email address on cla \[at\] cksource.com or support \[at\] cksource.com. We'll send you the CLA agreement to e-sign.

**Comment by Glaisher** [comment]
> The CLA was not signed as it was impossible to send it because of masked email. @[Glaisher](https://github.com/Glaisher) please leave us your email address on cla [at] cksource.com or support [at] cksource.com. We'll send you the CLA agreement to e-sign.

Thanks for this. I was actually a bit confused on how to sign it. :) Now shared it via email.

**Comment by vokiel** [comment]
Thank you for signing the CLA and your contribution. All checks have passed :heavy\_check\_mark:

**Pull request merged**
