### PR TITLE
Expose the source code from ckeditor5-demos and the builder

### PR DESCRIPTION
**Pull request by Reinmar**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: Expose the source code from ckeditor5-demos and the builder.

---

### Additional information

This is to address the traffic to [https://github.com/ckeditor/ckeditor5/blob/master/docs/examples/builds/classic-editor.md](https://github.com/ckeditor/ckeditor5/blob/master/docs/examples/builds/classic-editor.md)

14% of the visitors of the [https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html) page end up there.

### Work needed

If this change makes sense, it needs to be applied to the other 4 examples in that section (inline, balloon, balloon block, document). The other examples have their source code inline which is fine for now.

In the long-term, once we'll have more presets in the builder and ability to open a specific setup there, we'll be linking to the builder only

### CODE REVIEW

**Comment by godai78** [comment]
We mentioned this today on planning, there's a suggestion to put it over the demo, as it's not on the immediate screen upon entering the example page.

**Comment by gorzelinski** [comment]
> We mentioned this today on planning, there's a suggestion to put it over the demo, as it's not on the immediate screen upon entering the example page.

Exactly, I can make the changes.

**Comment by Witoso** [comment]
AFAICS, it's already above the snippet.

**Comment by Reinmar** [comment]
> AFAICS, it's already above the snippet.

Yes. The diff is unclear, but I moved it above indeed :)

**Comment by godai78** [comment]
By the way, don't we want it on `stable` so that goes on production immediately?

**Comment by godai78** [comment]
We can also turn off the GitHub top-right icon link in these guides, by the way.

**Review by gorzelinski — COMMENTED** [review]
Everything is ok. But I wonder, were some editor demos always narrower than the content? Affected demos are:

* Inline editor
* Balloon editor
* Balloon block editor

Screenshot 2024-07-17 at 12 30 55

**Comment by godai78** [comment]
> *   Balloon editor
> *   Balloon block editor  
>      

These two need to be narrower to accommodate the toolbar handle. Not sure about the inline, tho. Also, I believe they were that way already, not a recent change.

**Comment by gorzelinski** [comment]
> > * Balloon editor
> > * Balloon block editor
> 
> These two need to be narrower to accommodate the toolbar handle. Not sure about the inline, tho. Also, I believe they were that way already, not a recent change.

I thought so. So, LGTM. I would also remove this top GitHub link if it confuses users.

**Pull request merged**
