### PR TITLE
Set correct value (false) for CKFinderCommand#affectsData

### LINKED ISSUE #13213: Make CKFinder work with track changes.
Since CKFinder uses commands that are already integrated with track changes, the only change that should be done is to mark ckfinder `affectsData` as false.

More information here: https://github.com/cksource/collaboration-features/issues/4267

### PR DESCRIPTION
**Pull request by kbinieda**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Feature (track-changes): Add track changes integration for CKFinder feature.

Other (ckfinder): Set correct value (false) for `CKFinderCommand#affectsData`. Now the command's state depends only on related commands (`insertImage` and `link`). Closes #13213.

### CODE REVIEW

**Comment by scofalik** [comment]
I am missing any test checking this value. I wanted to propose to check if the command is enabled in read only mode but it would be disabled anyway as link and image are disabled in this mode. So, I guess, we need to check directly `affectsData`.

**Review by scofalik — CHANGES_REQUESTED** [review]
I am missing any test checking this value. I wanted to propose to check if the command is enabled in read only mode but it would be disabled anyway as link and image are disabled in this mode. So, I guess, we need to check directly `affectsData`.

**Comment by kbinieda** [comment]
> I am missing any test checking this value. I wanted to propose to check if the command is enabled in read only mode but it would be disabled anyway as link and image are disabled in this mode. So, I guess, we need to check directly `affectsData`.

I've added the test although, since the change does not introduce any behaviour (it's just a configuration preset) IMHO I don't think it needs testing.

**Comment by scofalik** [comment]
I know this test is weak. We could come up with some artificial tests that checks it though -- after all, we are adding this property with some purpose in mind. This change fixes situation in track changes after all, so there's a scenario for it. But I am not a fan of such test as well. We should add a test in track changes checking whether CKF is properly enabled.

**Pull request merged**
