### PR TITLE
Fix (ckeditor-paste-from-office): Support paste from WPS Office. Closes #2488.

### LINKED ISSUE #2488: Support for pasting content from WPS
I hope to copy and paste pictures and text in WPS software

### PR DESCRIPTION
**Pull request by flairyu**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (ckeditor-paste-from-office): Support paste from WPS Office. Closes #2488.

---

### Additional information

Please confirm and merge, lot's of people need this to be fixed. thanks.

### CODE REVIEW

**Comment by Reinmar** [comment]
Thanks, @flairyu! 

In order to merge this PR, we need automated tests. While the code coverage may still be 100%, we want to be sure that the patch really works and that we won't break it in the future.

You can find information about CKE5's dev and testing env here: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/development-environment.html

**Comment by Reinmar** [comment]
cc @ckeditor/qa-team Could you check this change?

**Comment by yoyo837** [comment]
Great fix.

**Comment by Mgsy** [comment]
I've tested the proposed solution and the fix works like a charm!

The example Word document without the fix:



...and after applying the fix:



Also, it seems to not break pasting from Word, so it looks good :clap: .

**Comment by yoyo837** [comment]
When can we merge it, can't wait. 🚀

**Comment by Reinmar** [comment]
@yoyo837 The PR lacks a test. If someone could add at least one test for it, we can speed up the merge. If not, we need to schedule for it and it may take some so it would probably slip to the next month's release.

**Comment by yoyo837** [comment]
> @yoyo837 The PR lacks a test. If someone could add at least one test for it, we can speed up the merge. If not, we need to schedule for it and it may take some so it would probably slip to the next month's release.

I will be happy to try to add one.

**Comment by yoyo837** [comment]
A more complete PR is here https://github.com/ckeditor/ckeditor5/pull/14039

**Pull request closed without merging**
