### PR TITLE
Source-editing: bootstrap the package

### LINKED ISSUE #9803: Add source editing package to the README.md and package.json files
## Provide a description of the task

Add source editing package to the `README.md` and `package.json` files after it has been published in npm.

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Internal (source-editing): Bootstrap the package. Closes #9803.

### CODE REVIEW

**Comment by pomek** [comment]
Let's wait for the CI.

**Comment by pomek** [comment]
I looked on https://unpkg.com/browse/@ckeditor/ckeditor5-watchdog@0.0.1/ when preparing the initial content of the new package.

**Review by psmyrek — APPROVED** [review]
LGTM 🎉

**Comment by pomek** [comment]
But CI will not fail when installing deps :D 

image

**Comment by pomek** [comment]
Published https://unpkg.com/browse/@ckeditor/ckeditor5-source-editing@0.0.1/.

**Pull request merged**
