### PR TITLE
Increase specificity of code styles to enforce 2SCM highlight in the …

### LINKED ISSUE #7671: Active <code> element styles do not work in docs
### ✔️ Expected result

The code element should be highlighted.

### ❌ Actual result

Nothing happens.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs (code): Increase the specificity of code styles to enforce 2SCM highlight in the docs. Closes #7671.

---

### Additional information

Just to double check if it is a proper solution:

Screenshot from 2020-07-23 11-57-05

### CODE REVIEW

**Comment by Reinmar** [comment]
> IMO what we need is (this is regardless of this PR, it is simply wrong):

This is not a content style. This is part of the editing-layer styles. So it should not use `.ck-content`.

**Comment by oleq** [comment]
> This is not a content style. This is part of the editing-layer styles. So it should not use `.ck-content`.

A good catch. `.ck-editor__editable` then.

**Comment by oleq** [comment]
As for this selector in Umberto, it goes back to cksource/umberto@6bc3441.

Probably the commit author wanted to filter all codes that are rendered in HLJS snippets out. So he changed `code` to `code:not( .hljs )`. Then I added `:not( pre ) >` to filter out `<code>` inside editor content (when the \`CodeBlock\` plugin first came out). And since all `code.hljs` are inside `pre` anyway, it could be that we don't need the original `code:not( .hljs )` fix.

**Comment by Reinmar** [comment]
I changed the base of this PR to `release`.

**Comment by Reinmar** [comment]
@oleq, so what you're proposing:

*   Let's check why this style was written in that way first (git blame may help).
*   Let's try to write it differently (how?).
*   Finally, let's verify that we didn't break anything.

**Comment by oleq** [comment]
I just checked it again and it looks like 

```diff
diff --git a/packages/ckeditor5-basic-styles/theme/code.css b/packages/ckeditor5-basic-styles/theme/code.css
index 824be69b55..f689d3f574 100644
--- a/packages/ckeditor5-basic-styles/theme/code.css
+++ b/packages/ckeditor5-basic-styles/theme/code.css
@@ -9,6 +9,6 @@
          border-radius: 2px;
 }
 
-.ck .ck-code_selected {
+.ck.ck-editor__editable .ck-code_selected {
          background-color: hsla(0, 0%, 78%, 0.5);
 }
```

is the only change we need.

**Pull request merged**
