### PR TITLE
I/8871 inline images link integratation

### LINKED ISSUE #8871: Integrate inline images with the link feature

### PR DESCRIPTION
**Pull request by pkwasnik**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Internal (link): Integrate inline images with the link feature. Closes #8871.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Comment by niegowski** [comment]
Since we merged #8998 yesterday, I'm not sure if this PR shouldn't be updated to use AttributeElement wrapping the ContainerElement? WDYT @Reinmar ?

**Comment by oleq** [comment]
If that would simplify the solution and make the feature better, I'm for it.

**Comment by niegowski** [comment]
> If that would simplify the solution and make the feature better, I'm for it.

I think it would simplify conversion, this are the changes that are needed to enable links over inline widgets: https://github.com/ckeditor/ckeditor5/compare/v25.0.0...master#diff-439efd180fbb2493acdc56d584f8b2af2ecc5b49c1ca587d876f6a8045b6c511

**Comment by niegowski** [comment]
I updated previous comment with better link

**Comment by Reinmar** [comment]
> Since we merged #8998 yesterday, I'm not sure if this PR shouldn't be updated to use AttributeElement wrapping the ContainerElement? WDYT @Reinmar ?

What will be the outcome for the user? Or is the goal simplifying the implementation? To be able to asses a change we need to understand the "return" from it.

**Comment by niegowski** [comment]
> What will be the outcome for the user? Or is the goal simplifying the implementation? To be able to asses a change we need to understand the "return" from it.

It would be simpler implementation and links would not break on the inline image.

**Comment by oleq** [comment]
> It would be simpler implementation and links would not break on the inline image.

I think we should not increase the technical debt if we can especially that we have the right tool for the job now. @pkwasnik can you please update your PR using the technique linked by Kuba in https://github.com/ckeditor/ckeditor5/pull/9028#issuecomment-784071079?

**Comment by pkwasnik** [comment]
> I think we should not increase the technical debt if we can especially that we have the right tool for the job now. @pkwasnik can you please update your PR using the technique linked by Kuba in #9028 (comment)?

yes, I will do that

**Comment by oleq** [comment]
Closing this one in favor of #9438.

**Pull request closed without merging**
