### PR TITLE
Docs: adding interim TOC section for plugins-related guides.

### PR DESCRIPTION
**Pull request by godai78**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs: adding interim TOC section for plugins-related guides. Closes: cksource/ckeditor5-internal#1186

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Comment by godai78** [comment]
We may reconsider the location of the section to be moved just over Contributing.

**Comment by FilipTokarski** [comment]
Do we have redirects for old links?
- https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html
- https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/creating-simple-plugin.html
- https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/package-generator.html

**Comment by FilipTokarski** [comment]
> We may reconsider the location of the section to be moved just over Contributing.

I'd leave it somewhere in the top (probably as is now), so it's easy to spot.

**Comment by godai78** [comment]
> Do we have redirects for old links?

I'll look into it and add.

**Review by FilipTokarski — APPROVED** [review]

**Pull request merged**
