### PR TITLE
Fixed adjacent whole words being missed by find and replace

### LINKED ISSUE #10719: Find and replace does not find whole words that are next to each other
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor5/latest/features/find-and-replace.html
2. Remove all content from the editor
3. Type `foo foo`
4. Try to find `foo` with `Whole words only` turned on

### ✔️ Expected result:

There are two search results, because there are two whole words `foo` in the content.

### ❌ Actual result:

Only the first `foo` is found, the second is ignored. If you insert another space or some character between the two `foo`, it will work as expected and find two results.

### Screencast:

https://user-images.githubusercontent.com/34380544/137890705-ae21ae60-2d3e-4cfb-8ad9-1eae8e084070.mp4

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by przemyslaw-zan**
Fix (find-and-replace): Fixed adjacent whole words being missed by find and replace. Closes #10719.

### CODE REVIEW

**Comment by przemyslaw-zan** [comment]
[https://github.com/ckeditor/ckeditor5/issues/10719#issuecomment-948564503](https://github.com/ckeditor/ckeditor5/issues/10719#issuecomment-948564503)

☝️ please check Safari before accepting

**Comment by pomek** [comment]
> ☝️ please check Safari before accepting

I used Safari 15.0 on Mac and mobile. Automated tests pass.

image

image

Let me verify it also manually.

**Comment by pomek** [comment]
@FilipTokarski helped me with checking the older Safari (14).

> 04 11 2021 10:00:07.258:INFO [Safari 14.1.2 (Mac OS 10.14.6)]: Connected on socket B1Pzd-6yjGeX5qA7AAAD with id manual-3127
> ✔ 280 tests completed

**Comment by pomek** [comment]
Works as expected.

image

**Review by pomek — APPROVED** [review]
LGTM.

**Pull request merged**
