### PR TITLE
T/444: Verify API docs on CI

### LINKED ISSUE #444: Verify API docs on CI
We have API docs validation thanks to our `@ckeditor/jsdoc-plugins` package. Now, it'd be a time to enable this on CI. Realistically, we can only do this in this repo, as a post-integration check.

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Added validation JSDoc on CI. Closes #444.

---

### Additional information

Requires: https://github.com/ckeditor/ckeditor5-dev/pull/222.

### CODE REVIEW

**Comment by pomek** [comment]
I guess in order to check the changes on CI, we need to merge required changes.

**Comment by Reinmar** [comment]
```The exit code of after_success, after_failure, after_script and subsequent stages do not affect the build result. However, if one of these stages times out, the build is marked as a failure.``` ekhm...

**Comment by Reinmar** [comment]
It should be in the `script` section (see https://blog.travis-ci.com/after_script_behavior_changes/).

**Comment by pomek** [comment]
and one more thing - I forgot to install `@ckeditor/ckeditor5-dev-docs`:

image

**Comment by Reinmar** [comment]
I'll fix both issues.

**Pull request merged**
