### PR TITLE
DLL build proposal

### LINKED ISSUE #8517: Implement DLLs for CKEditor 5 features
## 📝 Provide a description of the new feature

As the DLL spike research proved the approach, we will implement the DLLs for the CKEditor 5 as multiple DLLs.

During F2F talks with @Reinmar & @pomek, we've identified that implementing DLLs might be created on multiple levels to provide reuse of core CKEditor packages and to minimize, if possible, the number of `<script>` tags needed to insert into the document. To do that, we would choose among below 3 options:

1st option:

*   base DLL (core + utils + engine + ui + widget? + essentials? + paragraph?): `ckeditor5`
*   creator DLL (classic, balloon, ...): `@ckeditor/ckeditor5-editor-*`
*   other package DLLs (image, basic-styles, ...): `@ckeditor/ckeditor5-*`

2nd option:

*   base DLL (core + utils + engine + UI): `ckeditor5`
*   creator DLL (classic, balloon, ... + + widget + essentials + paragraph + basic-styles + image, etc.): `@ckeditor/ckeditor5-editor-*`
*   other package DLLs (image, basic-styles, ...): `@ckeditor/ckeditor5-*`

3rd option:

*   base DLL
*   build DLL
*   other package DLLs, not included in build DLL

Potential issues:

*   Angular, React, Vue: integrations must not import anything.
*   Collaboration features.
*   How to import from base DLL as sane imports (ideally the same as we use today). We should not alter current imports to not break current builds (tests, manual tests, etc.).

Additionally, I see option 0: every package is a DLL.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Feature: Introduce the CKEditor 5 DLL build. Closes #8517.

---

### Additional information

WIP for now.

### CODE REVIEW

**Comment by jodator** [comment]
Things to open this PR to review:

*   [ ] add image plugin to sample
*   [ ] fix errors (or check if those will get fixed by @pomek's work in #8521.

**Comment by pomek** [comment]
I don't want to be the person who will update 50 different `webpack.config.js` files if something should be changed :D

Let's extract the common part to a factory function (https://github.com/ckeditor/ckeditor5-dev/blob/i/8521/packages/ckeditor5-dev-utils/lib/builds/getpluginwebpackconfig.js) and modify the output via options (https://github.com/ckeditor/ckeditor5/blob/i/8521/packages/ckeditor5-html-embed/webpack.config.js).

**Comment by jodator** [comment]
@pomek that's a sound idea :) Let's have done during review. For now I'm trying to get green CI to have a starting point.

**Comment by jodator** [comment]
I'm waiting for the CI to validate that everything runs smoothly. The last piece is to add a build script for all the DLLs. I would push it now, but Travis still builds... :man\_shrugging:

**Comment by jodator** [comment]
:green\_circle: :tada:

**Pull request merged**
