### PR TITLE
Add border to menu bar

### PR DESCRIPTION
**Pull request by mremiszewski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Other (editor-classic): Add a separator between the menu bar and the toolbar.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Comment by scofalik** [comment]
We should also try to make the separators look better.

Right now it is like this:



Separators + border makes it crowdy, it looks like a grid.

Proposal:



Separators are a bit smaller, there is a bit more breathing room.

I added `height` equal to `--ck-icon-size` and removed `align-self`:



@oleq -- WDYT?

**Comment by oleq** [comment]
The change to separators looks fine but we need before/after screenshots for the following integrations to be sure it doesn't break anything:
* block toolbar, 
* balloon toolbar, 
* inline editor toolbar, 
* grouped items (`shouldGroupWhenFull`),
* widget toolbars

I think all of them can be easily obtained by building docs with all samples.

**Comment by scofalik** [comment]
Adding screenshots of various builds, with various elements highlighted / focused to see how they look next to each other.

I also zipped them: [separators.zip](https://github.com/user-attachments/files/15537103/separators.zip).

AFAICS, image is the only widget with a toolbar that has separators. Let me know in case I missed something.

**Comment by oleq** [comment]
> Adding screenshots of various builds, with various elements highlighted / focused to see how they look next to each other.

LGTM.

> AFAICS, image is the only widget with a toolbar that has separators. Let me know in case I missed something.

[Table toolbar](https://ckeditor.com/docs/ckeditor5/latest/api/module_table_tableconfig-TableConfig.html#member-tableToolbar) is also declarative. Any using `WidgetToolbarRepository` can also be like this.

BTW: Have you noticed the code snippet in `tableToolbar` API? 🙃

image

**Comment by scofalik** [comment]
I guess they would look fine, if image toolbars look fine?

**Comment by Reinmar** [comment]
Did you test a solution with those separators shorter only by 2px (1px top, 1px bottom)?

How much shorter are there in this PR? Because my initial feeling is "quite a bit" and I wonder if smaller change would not work better.

Though, nothing critically bad about the screenshots that you posted. I just wonder what other optionss do we have.

**Comment by scofalik** [comment]
They are 6 pixels smaller, they are the height of the icon. I want to keep these separators scalable, so I based them on icon size, which is based on font size normal.

I can add some pixels using `calc()` though. But I think that smaller is better.

\-6px (screens above):



\-4px:



\-2px:



\-0px (current):

**Pull request merged**
