### PR TITLE
Docs: Add warning about lists migration.

### LINKED ISSUE #14733: Inform about the replacement of Lists implementation
As we plan to switch the `Lists` implementation to `Document lists`. We need to:

*   [x] Pinned issue on Github.
*   [x] Create a section in the docs that informs about the replacement.
    *   https://ckeditor.com/docs/ckeditor5/latest/features/lists/lists.html

### PR DESCRIPTION
**Pull request by gorzelinski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: Add warning about lists migration. Fixes cksource/ckeditor5-internal#3535, closes #14733.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Comment by gorzelinski** [comment]
There were too many info boxes with similar content on this page, so I modified the article flow. IMO we should highlight about 10 - 20% of the content. The percent is arbitrary, but you know what I mean - highlighting only important or additional content.

**Comment by Witoso** [comment]
Please add a link to the #14767 in the info box as a source of the details. Thanks!

I think it would be good to add a similar one in the Document lists, as at the end this plugin will be removed.

**Review by godai78 — APPROVED** [review]
LGTM

**Comment by godai78** [comment]
> be good to add a similar one in the Document lists, as at the end this plugin will be removed.

Well, not really removed, it will actually replace the current one?

**Comment by Witoso** [comment]
For some time, there will be two, later only one, and Document list will be removed. See the plan in #14767

**Comment by godai78** [comment]
I know, but communication like "this feature will replace the old one and will then be removed" is not exactly logical ;)

**Comment by gorzelinski** [comment]
> I know, but communication like "this feature will replace the old one and will then be removed" is not exactly logical ;)

Tbh, I wasn't a fan of this either.

**Review by Witoso — APPROVED** [review]
LGTM

**Pull request merged**
