### PR TITLE
Color picker input does not retain its value

### PR DESCRIPTION
**Pull request by illia-stv**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix: Color picker input does not retain its value. Closes [#3236](https://github.com/cksource/ckeditor5-internal/issues/3236).

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Comment by illia-stv** [comment]
To resolve this issue I suggest reset color when input value is empty, it's seems for logical, because it reflects state of input in the view.

**Comment by Dumluregn** [comment]
As we discussed, this PR doesn't fix the original issue as it can still be reproducible by removing _part_ of the input instead of removing all of it (e.g. leaving only the first character of the hex format). It has an unimpeachable value though regarding the empty input handling. So please report a separate issue for it.

**Comment by Dumluregn** [comment]
Closing in favor of #14153.

**Comment by Dumluregn** [comment]
> As we discussed, this PR doesn't fix the original issue as it can still be reproducible by removing _part_ of the input instead of removing all of it (e.g. leaving only the first character of the hex format). It has an unimpeachable value though regarding the empty input handling. So please report a separate issue for it.

Reported in #14154.

**Pull request closed without merging**
