### PR TITLE
Docs: Highlight legacy docs more.

### PR DESCRIPTION
**Pull request by gorzelinski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: Highlight legacy docs more.

---

### Additional information

I also fixed some minor (formatting) issues.

### CODE REVIEW

**Comment by gorzelinski** [comment]
I tested different structures, but "legacy" in brackets looked best for me.

**Comment by godai78** [comment]
Not sure it makes sense to add (Legacy) to menu titles, when it resides in the Legacy folder. Guides titles are OK.

**Review by godai78 — APPROVED** [review]

**Comment by Witoso** [comment]
> Not sure it makes sense to add (Legacy) to menu titles, when it resides in the Legacy folder. Guides titles are OK.

We agreed it's not best aesthetically but we need to catch the attention better.

**Review by Witoso — CHANGES_REQUESTED** [review]
TBH I'm used to `[` and `]` in those scenarios. What was the reason to use parens?

**Comment by gorzelinski** [comment]
I was saying the same thing, but as we discussed today, the folder name can be missable. It's a good point, I think.

**Comment by gorzelinski** [comment]
Ok, there is a technical problem, actually. Square brackets in frontmatter (YAML) denote a sequence - they break our YAML. So, we have two options:

- Leave the menu titles as they are
- Put all those titles in apostrophes `'[Legacy] Blah, blah'` (they would differ from the rest of the docs)

cc @Witoso

**Comment by Witoso** [comment]
Use the break `\[Legacy\]` I think it should work.

**Comment by gorzelinski** [comment]
> Use the break \[Legacy\] I think it should work.

Oh, yeah, escaping the character is also a way.

**Comment by gorzelinski** [comment]
> Oh, yeah, escaping the character is also a way.

...or not. It renders the backslash, unfortunately.

Screenshot 2024-06-27 at 14 34 30

**Comment by Witoso** [comment]
Ok, let's go back to the parens, sorry!

**Comment by gorzelinski** [comment]
No problem, I also thought there was a chance that it would work. I didn't push my local changes, so everything is as it was :)

**Review by Witoso — APPROVED** [review]

**Pull request merged**
