### PR TITLE
I/7920: Fix image alignment in multi-root example.

### LINKED ISSUE #7920: The image in the "Multi-root editor" example is misaligned

### PR DESCRIPTION
**Pull request by panr**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs (ckeditor5): Fixed image alignment in Multi-root example (by adding the `ImageResize` plugin). Closes #7920.

### CODE REVIEW

**Comment by oleq** [comment]
Do you think we could enable the image resize dropdown or buttons in this sample? The PR does address the original lissue but when a user uploads the new image, image styles are next to useless.



Alternatively, we could switch to semantic image styles in this sample (a.k.a. side style). Which option sounds better to you?

**Review by oleq — COMMENTED** [review]
Do you think we could enable the image resize dropdown or buttons in this sample? The PR does address the original issue but when a user uploads the new image, image styles are next to useless.



Alternatively, we could switch to semantic image styles in this sample (a.k.a. side style). Which option sounds better to you?

**Comment by oleq** [comment]
> Do you think we could enable the image resize dropdown or buttons in this sample? The PR does address the original issue but when a user uploads the new image, image styles are next to useless.

See https://github.com/ckeditor/ckeditor5/issues/7920#issuecomment-683645309.

**Comment by panr** [comment]
> Alternatively, we could switch to semantic image styles in this sample (a.k.a. side style). Which option sounds better to you?

@oleq as we decided on Friday, we will switch to semantic styles here ;-) Changes on the way 🏃

**Pull request merged**
