### PR TITLE
Rewrite ckeditor5 package to TypeScript

### LINKED ISSUE #12616: [TS MVP] Rewrite ckeditor5 (package, not the whole editor)

### PR DESCRIPTION
**Pull request by niegowski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Internal: Rewrites ckeditor5 package to TypeScript. Closes #12616.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Review by arkflpc — COMMENTED** [review]
What about .gitignore and release:clean in package.json?

**Comment by niegowski** [comment]
Unfortunately, the generated DLL is broken, there are no errors in the console while building it but the generated `ckeditor5-dll.js` is broken:

```
ckeditor5-dll.js:5 Uncaught TypeError: e[o] is not a function
    at Object.s [as dll] (ckeditor5-dll.js:5:1)
    at ckeditor5-dll.js:5:1
    at Array.__webpack_modules__ (ckeditor5-dll.js:5:1)
    at __webpack_require__ (bootstrap:19:1)
    at node module decorator:5:1
    at all-features-dll.js:339:1
    at all-features-dll.js:339:1
```

**Comment by niegowski** [comment]
The above problem is now resolved but after running the DLL manual test I get:`CKEditorError: ckeditor-duplicated-modules`.

**Comment by niegowski** [comment]
Problems should be fixed by the referenced PR to `ckeditor5-dev`.

**Comment by pomek** [comment]
PR in CKE 5 dev is merged and released: https://github.com/ckeditor/ckeditor5-dev/releases/tag/v31.1.4.

**Comment by pomek** [comment]
I pushed a commit that provides integration with the release tools. I hope, you will accept it :D

**Review by arkflpc — APPROVED** [review]

**Review by pomek — APPROVED** [review]

**Pull request merged**
