### PR TITLE
Support text selection when editor is in a shadow root

### PR DESCRIPTION
**Pull request by ywsang**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Other (engine): Use the source element root (document vs. shadow root) to determine which "root" to perform `getSelection` on.
Other (core): Pass the sourceElementRoot to the Editing Controller.

---

### Additional information

Related to #3891 (and more generally, #1483). 

In order to know whether the editor is in shadow DOM or not, and maintain a reference to the shadow root in the former case, this PR uses a `sourceElementRoot` option set in editor's config upon creation. If the editor is created in a shadow root, the shadow root should be passed in this option. If not provided, this option defaults to the document.

### CODE REVIEW

**Comment by Comandeer** [comment]
@ywsang, is such a solution compatible with browsers other than Blink-based ones? AFAIR the `shadowRoot.getSelection()` method is Chrome-only and [there is no clear consensus](https://github.com/w3c/webcomponents/issues/79) how to handle selection in shadow roots.

**Comment by Reinmar** [comment]
That'd be good to know, indeed. Also, in order to actually test the PR a [manual test](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/testing-environment.html#running-manual-tests) would be helpful.

**Review by Reinmar — CHANGES_REQUESTED** [review]
As commented – there are concerns about browser compatibility. Also, we need to be able to test it on a manual test.

**Comment by mfreed7** [comment]
Hello, I just wanted to check in on this issue, and point out [a new proposal for a Shadow DOM compatible Selection API](https://github.com/mfreed7/shadow-dom-selection#proposal). This proposal has been being discussed on https://github.com/WICG/webcomponents/issues/79. In particular, [this comment](https://github.com/WICG/webcomponents/issues/79#issuecomment-965900820) gives a quick TL;DR summary of the proposal.

In particular, I'd be curious to hear the opinions of the CKEditor maintainers as to whether this proposal will suit your needs:

 1. Is the [proposal](https://github.com/mfreed7/shadow-dom-selection#proposal) understandable to you?

 2. Does the proposed `getComposedRange()` API work for your use case?

 3. In particular, do the two parameters, `selectionRoot` and `shadowRoots` make sense? And would they allow you to easily make use of cross-scope selection information?

 4. Do the changes to the "setter" APIs like `setBaseAndExtent()` seem like they'll work for your use case?

 5. Do you have any need to get selection information "anywhere on the page", i.e. within any shadow root? This would likely require another parameter to make this easy, if so.

 6. Do you have any other concerns or feedback?

I'd love to hear your feedback either here in this issue, or (better) on the [Selection API thread](https://github.com/WICG/webcomponents/issues/79). These changes are still very much in development, so your feedback can have an impact. Thanks!

**Comment by wimleers** [comment]
FYI: Drupal would also like to see this happen.

**Comment by pomek** [comment]
The PR is a little outdated as the last update was made over a year ago, but I wanted to verify whether it resolves my case. After merging the latest `#master`, the selection in Shadow DOM and the editor's selection are not synchronized. 

Perhaps I failed when merging changes…

**Comment by Inviz** [comment]
I was a bit disappointed to learn that CKEditor does not handle running in the web component. thanks to this PR though i shimmed it like this:

```
var orig = document.defaultView.getSelection;
document.defaultView.getSelection = function() {
  if (document.activeElement.shadowRoot) return document.activeElement.shadowRoot.getSelection(); 
  return orig.apply(this, arguments);
}
```

Obviously it's not great, but at least i didnt have to hack the source code.

**Pull request closed without merging**
