### PR TITLE
Fix for pasting plain text inside of a link breaking a link

### LINKED ISSUE #8158: Pasting plain text on link breaks link
## 📝 Provide detailed reproduction steps (if any)

1.  Use an example in docs (ie Classic editor).
2.  Create a link (ie on `"example"`)
3.  Copy text without formatting (ie `"foo"`).
4.  Put the cursor inside the link (ie `"exam|ple"`).
5.  Use paste or plain-text paste.

### ✔️ Expected result

The link is set on whole text (ie on `"examfoople"`)

### ❌ Actual result

The Pasted text breaks the link apart:

## 📃 Other details

cc @cksource/ckeditor-5-triage

*   Browser: any (Firefox/Chrome tested)
*   CKEditor version: master @ iteration36

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by mlewand**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (clipboard): Pasting plain text inside of a link or restricted editing editable region will no longer break them. Closes #8158.

Tests (link): Added tests for pasting plain text over the link.

---

### Additional information

### CODE REVIEW

**Comment by mlewand** [comment]
@ckeditor/qa-team can I ask you to test the thing?

---

Some hints regarding things to test: 

*   pasting _over a link_ (where you have whole link selected and replace it with different text, should remove the link and paste the text) - should be tested in depth as the logic was rewritten
*   pasting plain text in mentions
*   pasting plain text in restricted editing zones

**Comment by Mgsy** [comment]
## Steps to reproduce

1.  Copy some plain text.
2.  Put the caret at the end of a link (the selection should be inside the link).
3.  Activate bold.
4.  Paste.
5.  Undo.

## Current result

After step 4, the text is pasted outside of the link. After step 5, the text merges to the link.

## GIF

**Comment by Mgsy** [comment]
## Steps to reproduce

1.  Select the whole link.
2.  Paste the plain text.
3.  Undo.

## Current result

The pasted text becomes a link.

**Comment by niegowski** [comment]
@ckeditor/qa-team could you test it one more time? The logic for this PR was once more time rewritten.

**Comment by niegowski** [comment]
I just noticed that some tests in the table package started failing. I'm checking it.

**Comment by niegowski** [comment]
> I just noticed that some tests in the table package started failing. I'm checking it.

It's fixed now.

**Comment by Mgsy** [comment]
Things look good :+1: The previous issues have been fixed and I haven't found anything new.

**Pull request merged**
