### PR TITLE
Docs: Cleaned up the toolbar code clutter. 

### LINKED ISSUE #10779: Cleanup the restricted editing demo toolbar
Clean up the demo toolbar clutter - the image feature code is there, even though it is now displayed in the UI.

### PR DESCRIPTION
**Pull request by godai78**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs: Cleaned up the toolbar code clutter. Closes #10779.

### CODE REVIEW

**Comment by godai78** [comment]
Caught in console:

```
assets.js:86 Uncaught (in promise) TypeError: window.umberto.createTooltip is not a function
    at window.attachTourBalloon (assets.js:86)
    at reloadEditor (restricted-editing.js:79)
    at async startStandardEditingMode (restricted-editing.js:45)
    at async startMode (restricted-editing.js:38)
window.attachTourBalloon	@	assets.js:86
reloadEditor	@	restricted-editing.js:79
async function (async)		
startMode	@	restricted-editing.js:38
eval	@	restricted-editing.js:30
./node_modules/umberto/source/ckeditor5/31.0.0/_snippets/features/restricted-editing.js	@	snippet.js:7781
__webpack_require__	@	snippet.js:24
(anonymous)	@	snippet.js:88
(anonymous)
```

**Comment by FilipTokarski** [comment]
Not sure why, but when testing locally I get tour balloon error:

```
Uncaught (in promise) TypeError: window.umberto.createTooltip is not a function
   at window.attachTourBalloon (assets.js:86)
   at reloadEditor (restricted-editing.js:76)
   at async startStandardEditingMode (restricted-editing.js:45)
   at async startMode (restricted-editing.js:38)
```

Even though nothing in its configuration has changed and it's the same as in production.

**Comment by godai78** [comment]
There is something wrong with the whole lot, this is the very same error from `stable`:

```
assets.js:86 Uncaught (in promise) TypeError: window.umberto.createTooltip is not a function  
   at window.attachTourBalloon (assets.js:86)  
   at reloadEditor (restricted-editing.js:79)  
   at async startStandardEditingMode (restricted-editing.js:45)  
   at async startMode (restricted-editing.js:38)
```

We are also having some issues of unknown origin with the generation of the docs, so this may be the same thing.

**Comment by FilipTokarski** [comment]
Looks like it's fine after reinstalling the dependencies.

**Pull request merged**
