### PR TITLE
Migration guide for 26.0.0 + plugincollection-soft-required docs improved

### LINKED ISSUE #8092: Markers in empty elements can cause unexpected errors
The problem occurred for the first time in #7907.

---

We agreed that the bug can be hooked deeper, in the engine. However, the PR fixes the bug and the editor does not crash anymore.

As for now, we're fine with that. But in the future, the bug can occur once again and if we will be fixing that, we should revert changes introduced in the PR.

https://github.com/ckeditor/ckeditor5/blob/eb92cfb7377fa066a4cb08163ade33a73639aab1/packages/ckeditor5-link/src/linkui.js#L664-L687

_Originally posted by @pomek in https://github.com/ckeditor/ckeditor5/pull/8074#issuecomment-693331315_

### LINKED ISSUE #8902: Review the plugincollection-soft-required error documentation
Make it super clear and actionable.

### PR DESCRIPTION
**Pull request by Reinmar**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs: Introduced "Migration" section and the guide regarding migration to 26.0.0. Reviewed `plugincollection-soft-required`. Closes #8902.

### CODE REVIEW

**Review by pomek — APPROVED** [review]
LGTM.

**Review by godai78 — APPROVED** [review]
I reviewed this proposed document and made certain minor amendments to it, but I find it approvable otherwise and therefore I approve it now with the immediate effect.

**Comment by Reinmar** [comment]
This shouldn't pass :thinking:

**Comment by Reinmar** [comment]
LOL, the tests do fail. How didn't we spot this, @pomek? :P

**Comment by godai78** [comment]
> This shouldn't pass

Wasn't something I was personally able to spot, sorry :D

**Review by AnnaTomanek — APPROVED** [review]
Pushed some final fixes, looks fine to me 👍

**Pull request merged**
