### PR TITLE
Replace relative paths to absolute in the live demos

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Internal: Added a script for replacing all relative paths to absolute in the documentation executed on each page where live demos are available.

---

Closes cksource/ckeditor5-internal#852.

### CODE REVIEW

**Review by psmyrek — APPROVED** [review]
LGTM 🎉 

One thing to consider: instead of using `window.location.href` to produce the base URL for an image, maybe it would be better to get the base URL from the `baseURI` property from the image? In some rare cases these two things can be different.

> The `baseURI` read-only property returns the absolute base URL of a `Node`.
> 
> The base URL is used to resolve relative URLs when the browser needs to obtain an absolute URL, for example when processing the HTML `` element's `src` attribute or XML `xlink:href` attribute.
> 
> In most cases the base URL is the location of the document, but it can be affected by many factors, including the `<base>` element in HTML and the `xml:base` attribute in XML.

**Comment by psmyrek** [comment]
Another thing to consider: what about other elements in the editable that may also have relative paths in their attributes, i.e. the `<picture>` with multiple `<source>` elements, or the `<video>` that we could host locally? After a brief look at the documentation, I did not find such elements so far, but the question is whether this solution should be ready for it?

**Comment by pomek** [comment]
@psmyrek, I pushed a commit that fixes mentioned issues: 

- Usage of `img.baseURI` instead of `window.location`
- Update children of the `<picture>` element

**Review by psmyrek — APPROVED** [review]
Thanks for adding these changes.

LGTM 🎉

**Pull request merged**
