### PR TITLE
Added a global warning banner about local/nightly documentation

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs (ckeditor5): Added a global warning banner about local/nightly documentation.

---

### Additional information

Requires changes in the documentation builder (in a separate PR).

### CODE REVIEW

**Comment by pomek** [comment]
In the proposed solution, I wouldn't say I like displaying the warning banner on localhost.

**Comment by pomek** [comment]
Our documentation builder allows previewing the documentation before deploying it live. In the current solution, the banner will say that we're on a local build of the documentation on the staging server, which is wrong.

I'd change the solution to display the banner only on nightly docs.

**Comment by oleq** [comment]
Alright, let's keep things simple.

**Review by pomek — APPROVED** [review]
LGTM.

**Pull request merged**
