### PR TITLE
Jest testing not possible with CommentsRepository premium plugin 

### LINKED ISSUE #17421: Jest testing not possible with CommentsRepository premium plugin
## 📝 Provide a description of requested docs changes

The jest related docs for angular, react and vue are not working when the premium  plugin CommentsRepository is used

## Error message
```
FrontEnd\node_modules\@ckeditor\ckeditor5-collaboration-core\dist\index.js:392
    const _0x27ffc6 = _0x20b54e['getClientRects']()['item'](0x0);
                                                           ^

TypeError: _0x20b54e.getClientRects(...).item is not a function
    at R (FrontEnd\node_modules\@ckeditor\ckeditor5-collaboration-core\dist\index.js:392:60)
    at r._getTargetForId (FrontEnd\node_modules\@ckeditor\ckeditor5-comments\dist\index.js:22:176593)     
    at d._target (FrontEnd\node_modules\@ckeditor\ckeditor5-comments\dist\index.js:22:178362)
    at d._getNormalizedTarget (FrontEnd\node_modules\@ckeditor\ckeditor5-comments\dist\index.js:22:54176) 
    at new d (FrontEnd\node_modules\@ckeditor\ckeditor5-comments\dist\index.js:22:52317)
    at o._attachCommentThread (FrontEnd\node_modules\@ckeditor\ckeditor5-comments\dist\index.js:22:137698)
    at ie.attachTo (FrontEnd\node_modules\@ckeditor\ckeditor5-comments\dist\index.js:22:154306)
    at FrontEnd\node_modules\@ckeditor\ckeditor5-comments\dist\index.js:22:178334
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Fix
Additional mocking for Element.prototype.getClientRects is needed

### PR DESCRIPTION
**Pull request by stefanseeger**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: Enhance jest testing section to work with CommentsRepository. Closes #17421.

---

#### 📝 Provide a description of requested docs changes

The jest related docs for angular, react and vue are not working when the premium  plugin CommentsRepository is used

#### Error message
```
FrontEnd\node_modules\@ckeditor\ckeditor5-collaboration-core\dist\index.js:392
    const _0x27ffc6 = _0x20b54e['getClientRects']()['item'](0x0);
                                                           ^

TypeError: _0x20b54e.getClientRects(...).item is not a function
    at R (FrontEnd\node_modules\@ckeditor\ckeditor5-collaboration-core\dist\index.js:392:60)
    at r._getTargetForId (FrontEnd\node_modules\@ckeditor\ckeditor5-comments\dist\index.js:22:176593)     
    at d._target (FrontEnd\node_modules\@ckeditor\ckeditor5-comments\dist\index.js:22:178362)
    at d._getNormalizedTarget (FrontEnd\node_modules\@ckeditor\ckeditor5-comments\dist\index.js:22:54176) 
    at new d (FrontEnd\node_modules\@ckeditor\ckeditor5-comments\dist\index.js:22:52317)
    at o._attachCommentThread (FrontEnd\node_modules\@ckeditor\ckeditor5-comments\dist\index.js:22:137698)
    at ie.attachTo (FrontEnd\node_modules\@ckeditor\ckeditor5-comments\dist\index.js:22:154306)
    at FrontEnd\node_modules\@ckeditor\ckeditor5-comments\dist\index.js:22:178334
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

#### Fix
Additional mocking for Element.prototype.getClientRects is needed

### CODE REVIEW

**Comment by Mati365** [comment]
@stefanseeger Looks cool, however we have to remove that `as any` TS expression, as we use JavaScript in our docs samples.

**Comment by stefanseeger** [comment]
Hi @Mati365,
I had it in mind but than somehow forgot to remove it.
Also I yesterday spotted that https://developer.mozilla.org/en-US/docs/Web/API/Document/createElementNS is also missing, but I did not have time yet to update the CR.
Thank you!

**Comment by Mati365** [comment]
@stefanseeger Do you have an example of `createElementNS` that was working in your case?

**Comment by stefanseeger** [comment]
I am not having access to my code today. Will check on Monday and let you know

**Comment by Mati365** [comment]
@stefanseeger Ok, I have merged my changes. If something is not working correctly, I would appreciate it if you could report the issue. Thank you!

**Pull request closed without merging**
