### PR TITLE
Fix (html-support): Preserve HTML attributes when list is split or its item is removed

### LINKED ISSUE #14346: Style deletion issue in Second List when Deleting First List
## 📝 Provide detailed reproduction steps (if any)

1.  Create a list.
2.  Press Enter twice to create a new line.
3.  Create a second list.
4.  Apply a style to the second list.
5.  Delete the first list.

https://github.com/ckeditor/ckeditor5/assets/50703222/240eeaef-1d33-487c-bc5d-5346b82bbedb

### ✔️ Expected result

The second list should retain its style.

### ❌ Actual result

The second list's style is deleted.

### ❓ Possible solution

Regression issues. Second list retains its style for v38.0.1.

https://github.com/ckeditor/ckeditor5/assets/50703222/05c908cc-566e-4be8-918e-39185a6fd743

## 📃 Other details

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by filipsobol**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (html-support): Preserve HTML attributes when list is split or its item is removed. Closes #14346 and #14349.

Fix (engine): Fix shallow view and model TreeWalkers returning elements outside of specified boundaries.

### CODE REVIEW

**Review by niegowski — CHANGES_REQUESTED** [review]
As discussed F2F this is not a proper solution. Most probably a bug in the TreeWalker.

**Review by arkflpc — APPROVED** [review]
LGTM

**Comment by filipsobol** [comment]
Since the performance of this part of the code is critical to the rest of the editor, I run the following benchmarks.

### Model TreeWalker:

```js
const items = Array.from( { length: 10000 }, () => new Element( 'img1' ) );
root._insertChild( 0, items );

const walker = new TreeWalker( {
  boundaries: new Range(
    new Position( root, [ 0 ] ),
    new Position( root, [ 9999 ] )
  ),
  shallow: true
} );

const start = performance.now();

let i = 0;

for ( const item of walker ) {
  i++;
}

const end = performance.now();

console.log( `${ i } iterations took ${ end - start }ms` );
```

Results:

|       | Before (ms) | After (ms) |
|-------|-------------|------------|
| Run 1 | 336.7       | 335.2      |
| Run 2 | 332.8       | 334.3      |
| Run 3 | 344.5       | 328.6      |
| Run 4 | 339.1       | 351.1      |
| Run 5 | 328.2       | 341.3      |

### View TreeWalker:

```js
const items = Array.from( { length: 10000 }, () => new ContainerElement( doc, 'img1' ) );
root._insertChild( 0, items );

const walker = new TreeWalker( {
  boundaries: new Range(
    new Position( root, 0 ),
    new Position( root, 9999 )
  ),
  shallow: true
} );

const start = performance.now();

let i = 0;

for ( const item of walker ) {
  i++;
}

const end = performance.now();

console.log( `${ i } iterations took ${ end - start }ms` );
```

Results:

|       | Before (ms) | After (ms) |
|-------|-------------|------------|
| Run 1 | 4.6         | 7.1        |
| Run 2 | 5.4         | 6.5        |
| Run 3 | 4.7         | 7.0        |
| Run 4 | 3.3         | 7.0        |
| Run 5 | 4.6         | 6.4        |

**Comment by filipsobol** [comment]
Benchmark results after the update.

### Model TreeWalker

|       | Before (ms) | After (ms) |
|-------|-------------|------------|
| Run 1 | 344.0       | 345.7      |
| Run 2 | 337.6       | 343.1      |
| Run 3 | 358.1       | 363.6      |
| Run 4 | 344.4       | 342.3      |
| Run 5 | 356.1       | 380.8      |

### View TreeWalker

|       | Before (ms) | After (ms) |
|-------|-------------|------------|
| Run 1 | 4.6         | 3.7        |
| Run 2 | 4.3         | 4.6        |
| Run 3 | 4.6         | 4.9        |
| Run 4 | 5.1         | 4.8        |
| Run 5 | 4.9         | 3.7        |

**Review by niegowski — APPROVED** [review]

**Pull request merged**
