### PR TITLE
Two tildes for strikethrough (as per specs)

### PR DESCRIPTION
**Pull request by benfiratkaya**
Fixes: #10261

### CODE REVIEW

**Comment by Reinmar** [comment]
Hi @benfiratkaya! This pull request is missing tests: please tests that cover your change. See our [Contributing Code](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/contributing.html#tests) guide for more details.

**Comment by benfiratkaya** [comment]
> Hi @benfiratkaya! This pull request is missing tests: please tests that cover your change. See our [Contributing Code](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/contributing.html#tests) guide for more details.

Updated, please check again.

**Comment by Reinmar** [comment]
I saw that you updated tests, @benfiratkaya. Unfortunately, that's not enough. Since you changed existing tests, now we don't have coverage for what `~foo~` does.

Also, I don't understand how's this related to #10261, which mentions that the tilde character is not escaped properly. If the PR is meant to fix this issue, we'd need tests for that too.

Finally, this package's tests don't pass after your change.

Sorry to be that picky, but we need to be sure the change is correct before merging this.

**Comment by mlewand** [comment]
Hi, It's been a while since we last heard from you. We're closing this PR for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Pull request closed without merging**
