### PR TITLE
Docs: Fix typo

### PR DESCRIPTION
**Pull request by s123121**
Docs: Fix typo

### CODE REVIEW

**Comment by wwalc** [comment]
@s123121 could you sign the CLA? You should have it in your mailbox.

**Comment by s123121** [comment]
That is weird! I did sign the CLA 
screen shot 2018-04-17 at 17 27 31

**Comment by Reinmar** [comment]
Thanks for letting us know! We'll look into this. cc @vokiel

**Comment by Reinmar** [comment]
And, of course, thanks for the PR :)

**Comment by Reinmar** [comment]
It's all green now so maybe the CLA service had some delay.

**Pull request merged**
