### PR TITLE
Updated the guide that was using outdated API.

### LINKED ISSUE #11160: Docs: CKEditor 5 integration with React using source guide ends up with error
### CKEditor 5 integration with React using source guide ends up with the error
While following React integration with CKEditor 5 from source guide(https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-the-editor-from-source)
the following error occurs after the last step `yarn start`:
image
It looks like the issue is related to this part of webpack.config.js:
image
Probably some changes happened in one of the new versions of the webpack. 
We should update docs to make the example working again.

### PR DESCRIPTION
**Pull request by przemyslaw-zan**
Docs: Updated the React component guide. Closes #11160.

### CODE REVIEW

**Comment by pomek** [comment]
Please, prepare a PR for the `#stable` branch. Perhaps you need to rebase your solution over the base branch.

**Comment by pomek** [comment]
@dufipl, could you verify whether the fix works?

**Comment by dufipl** [comment]
Hello @pomek, I've tested it, and it is working fine now 👌

**Review by pomek — APPROVED** [review]
LGTM.

**Pull request merged**
