### PR TITLE
Add information about supported Angular versions in the Angular guide

### PR DESCRIPTION
**Pull request by ma2ciek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs: Added information about supported Angular versions in the Angular guide. Closes ckeditor/ckeditor5-angular#227.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Review by godai78 — APPROVED** [review]
godai's seal of approval.

**Comment by ma2ciek** [comment]
Thanks, @godai78! I added a link to NPM, could you recheck it?

**Comment by godai78** [comment]
Done.

**Review by AnnaTomanek — COMMENTED** [review]
There is a difference between what's in the readme and what's in the documentation compatibility section (Angular 9 vs Angular 9.1).

Also if this has already been released, the docs change should target the `stable` branch.

**Comment by ma2ciek** [comment]
> There is a difference between what's in the readme and what's in the documentation compatibility section (Angular 9 vs Angular 9.1).

Yeah, there's a small difference.

There's an error that was fixed in Angular 9.1, so we can change these occurrences to 9.1. But actually, all users are mostly using the latest minor versions for the given major using the most common range -  `^X.Y.Z` - that matches the latest `X` version, so most of the Angular 9 users will use packages from the 9.1 release (or higher) anyway.

**Comment by ma2ciek** [comment]
> Also if this has already been released, the docs change should target the `stable` branch.

Yep, my bad!

**Pull request merged**
