### PR TITLE
Docs: Update the Using a React component in a block widget guide.

### PR DESCRIPTION
**Pull request by gorzelinski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: Update the Using a React component in a block widget guide. Closes https://github.com/ckeditor/ckeditor5/issues/14749.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Comment by gorzelinski** [comment]
@Acrophost spotted a tricky problem. This strange line (`{% raw %}}}{% endraw %}`) was probably due to the technical limitations of our static site generator. The snippet wasn't rendering correctly even though the JSX syntax was correct. I rewrote problematic snippets and solved other issues. The guide should work now but needs modernization like FP and hooks.

**Review by apadol-cksource — CHANGES_REQUESTED** [review]
LGTM but we need to reflect those changes in https://ckeditor.com/docs/ckeditor5/latest/examples/framework/using-react-in-a-widget.html

**Review by apadol-cksource — APPROVED** [review]

**Review by godai78 — APPROVED** [review]
LGTM

**Comment by gorzelinski** [comment]
The CI build failure was affected by a manual test. Changes in this PR weren't affecting manual tests - we can merge.

**Pull request closed without merging**
