### PR TITLE
fix: autosave plugin not ignoring `transparent` type events

### LINKED ISSUE #9233: Autosave plugin not ignoring `transparent` type events.
The current autosave calls the Promise for almost all `change:data` events. This is not needed as some changes may be from the Collaboration Mode, (ie, changes from other users). This will cause in collaboration mode:

- Unwanted API calls for every connected user.
- Unwanted API calls for other ignorable events.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@ckeditor/ckeditor5-autosave/src/autosave.js b/node_modules/@ckeditor/ckeditor5-autosave/src/autosave.js
index 004c0a7..20720ef 100644
--- a/node_modules/@ckeditor/ckeditor5-autosave/src/autosave.js
+++ b/node_modules/@ckeditor/ckeditor5-autosave/src/autosave.js
@@ -153,11 +153,17 @@ export default class Autosave extends Plugin {
 
 		this._pendingActions = editor.plugins.get( PendingActions );
 
-		this.listenTo( doc, 'change:data', () => {
+		this.listenTo( doc, 'change:data', (_e, batch) => {
 			if ( !this._saveCallbacks.length ) {
 				return;
 			}
 
+      // If the change is from another collaborative session from another user
+      // don't autosave.
+      if ( batch.type === 'transparent') {
+        return;
+      }
+
 			if ( this.state == 'synchronized' ) {
 				this._action = this._pendingActions.add( t( 'Saving changes' ) );
 				this.state = 'waiting';
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

### PR DESCRIPTION
**Pull request by asimkt**
Fix: autosave plugin not ignoring `transparent` type events. Closes #9233.

---

### Additional information

Considering all transparent events can be safely ignored by autosave feature as mentioned in  https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_batch-Batch.html#member-type

### CODE REVIEW

**Comment by ma2ciek** [comment]
Hi @asimkt,

Thanks for the PR and I'm really sorry for the late response. I'll review it soon.

**Comment by asimkt** [comment]
Thanks @ma2ciek

**Comment by Mgsy** [comment]
Hi @asimkt! Our team would like to discuss with you the proposed solution, so it would be appreciated if you could contact us through [our support channel](https://support.ckeditor.com/hc/en-us/requests/new). Thanks!

**Comment by mlewand** [comment]
Some further discussion can be found in [the referenced issue comments](https://github.com/ckeditor/ckeditor5/issues/9233#issuecomment-822465543).

**Review by mlewand — CHANGES_REQUESTED** [review]
Thanks for trying out, unfortunately as described in https://github.com/ckeditor/ckeditor5/issues/9233#issuecomment-822465543 this is not the proper way to fix it as it will have multiple undesired side effects.

That being said there are other ideas to solve it https://github.com/ckeditor/ckeditor5/issues/9233#issuecomment-827403191 maybe this will be helpful.

**Comment by asimkt** [comment]
I can see we already have a fix. Do you want to close this PR @AnnaTomanek ? IDK why we re-opened this one.

**Comment by asimkt** [comment]
https://github.com/ckeditor/ckeditor5/pull/11016

**Pull request closed without merging**
