### PR TITLE
Docs: changelog 27.1.0

### PR DESCRIPTION
**Pull request by godai78**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs: changelog review.

### CODE REVIEW

**Comment by godai78** [comment]
We may reconsider linking to migration guide and link to docs section directly instead.

**Comment by pomek** [comment]
Will we have the migration guide to` 27.1.0`?

**Comment by godai78** [comment]
Yes, it is already in the docs. It mentions disallowing back the nesting of tables and block quotes.

**Review by pomek — APPROVED** [review]
LGTM.

**Comment by AnnaTomanek** [comment]
As for migration guides, I've been thinking we could actually change their structure a bit and have them as "Migration to v27.X" or something to save the space because normally, there will be no migration guide for any minor version or if we have it, it's gonna be very short (because if minor, there shouldn't be that many things to describe). WDYT?

**Comment by godai78** [comment]
Like, putting all those (two) guides together? Sure.

**Review by AnnaTomanek — APPROVED** [review]

**Review by pomek — APPROVED** [review]
LGTM.

**Pull request merged**
