### PR TITLE
T/1636: IndentBlock feature

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Implement IndentBlock feature. Closes ckeditor/ckeditor5#1636.

---

### Additional information

This is a multi-repo PR - before merging remove `mgit.json` entries to master branch.

The changes in other repositories:
- core: [PR](https://github.com/ckeditor/ckeditor5-core/pull/179).
- indent-block: [PR](https://github.com/ckeditor/ckeditor5-indent-block/pull/1).
- list: [PR](https://github.com/ckeditor/ckeditor5-list/pull/127).
- theme-lark [PR](https://github.com/ckeditor/ckeditor5/pull/1816)

This PR introduces the block indentation feature as well as `'indent'` and `'outdent'` buttons that acts with both lists and blocks.

The internals of how the buttons are defined and linked in commands is described in core PR.

I have still some doubts about whole PR:
1. Where should be the definitions for which blocks can be indented? ATM only `paragraphs` and `headingN` are enabled.
2. Icons for new buttons are missing - but this should be done in a follow-up as I'm uncertain where those buttons be defined (core vs indent feature).
3. The Indent/IndentBlock feature guide needs expanding (follow-up).
4. Commends overriding/gathering for buttons - more info in core PR.
5. `IndentBlock` or `BlockIndentation` ? Dunno I've described this as block indentation but the plugin is `IndentBlock` and commands are `indentBlock` and `outdentBlock`.

### CODE REVIEW

**Comment by Reinmar** [comment]
image

That's right after I executed `mgit sync && yarn clean && yarn install`.

**Comment by Reinmar** [comment]
Yup, because those paths are outdated (you moved the file).

**Comment by Reinmar** [comment]
> * Where should be the definitions for which blocks can be indented? ATM only `paragraphs` and `headingN` are enabled.

I think it's fine to hardcode the current list because it's still extensible via schema. Let's just have this documented in the feature guide.



> * Icons for new buttons are missing - but this should be done in a follow-up as I'm uncertain where those buttons be defined (core vs indent feature).

cc @oleq 

> 5\. `IndentBlock` or `BlockIndentation` ? Dunno I've described this as block indentation but the plugin is `IndentBlock` and commands are `indentBlock` and `outdentBlock`.

The same pattern which we used in the list package.

**Comment by Reinmar** [comment]
Also, this:

image

**Comment by Reinmar** [comment]
Followup for the docs: let's try to generalise them so they are about indenting things in general. At first, it'd be good to pretend like they are all one thing. Then, in the second part of this article we can go into details explaining that you can use `Indent` together with `IndentBlock` and/or `Lists`.

**Comment by jodator** [comment]
I've added the follow ups for docs & icons: https://github.com/ckeditor/ckeditor5-indent/issues/2, https://github.com/ckeditor/ckeditor5-indent/issues/3

**Comment by jodator** [comment]
@Reinmar - I think that I've addressed all the issues. The code is moved to the `indent` feature. Tests are passing and the docs are also building.

**Pull request closed without merging**
