### PR TITLE
Configured branches for tests purposes of ckeditor5-ui-default/issues…

### PR DESCRIPTION
**Pull request by oleq**
…/148.

A follow–up of https://github.com/ckeditor/ckeditor5-ui-default/issues/148.

This PR is for CI/testing purposes only.

### CODE REVIEW

**Comment by Reinmar** [comment]
DO NOT MAKE PRs to this repo any more. It's going to be removed very soon. Actually – we already merged it to ckeditor5-ui in our test branches.

**Comment by Reinmar** [comment]
Oops. Sorry, I thought that this is a PR to ckeditor5-ui-default. Still, masters are locked and ckeditor5-ui-default will disappear in a couple of days.

**Comment by oleq** [comment]
Yep. This PR enables CI for the "constellation" of future PRs only. To be updated.

**Comment by oleq** [comment]
Moved to https://github.com/ckeditor/ckeditor5/pull/385.

**Pull request closed without merging**
