### PR TITLE
Updated docs for package generator with --use-yarn flag

### PR DESCRIPTION
**Pull request by martnpaneq**
Docs:: Added the `--use-yarn` flag in the package generator guide.

### CODE REVIEW

**Comment by psmyrek** [comment]
Please change the base branch to `stable`, as the package generator release process is independent of the CKEditor 5 release process. After a new version of the package generator is released, we want to have up-to-date documentation on production.

**Comment by martnpaneq** [comment]
Changed base to stable

**Review by psmyrek — APPROVED** [review]
LGTM 🎉 

This PR should be merged when the package generator is released with changes from ckeditor/ckeditor5-package-generator#126.

**Comment by pomek** [comment]
I close this PR in favor of https://github.com/ckeditor/ckeditor5/pull/12780.

**Pull request closed without merging**
