### PR TITLE
Replaced icons with ones with improved alignment.

### LINKED ISSUE #15549: The image upload icon is too high
Since 41.2.0 it looks like this:

In 40.0.0 it looked like this:

The top of the image was aligned to the top of the table.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by pszczesniak**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (core, ckbox, media-embed): Replaced some toolbar icons with ones with improved alignment. Closes #15549.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Review by godai78 — APPROVED** [review]
LGTM

**Comment by godai78** [comment]
No new case change icon?

**Comment by pszczesniak** [comment]
> No new case change icon?

Probably it will be in other PR (just CC icon change in commercial repo).

**Comment by Witoso** [comment]
In #5874.

**Pull request merged**
