### PR TITLE
Docs: fixed code block in Markdown output demo.

### LINKED ISSUE #9487: Code block broken in Markdown guide demo
It can be reproduced in the docs on production: https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html

Output:

### PR DESCRIPTION
**Pull request by godai78**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs (markdown-gfm): Fixed demo display error. Closes #9487.

### CODE REVIEW

**Comment by godai78** [comment]
We do, in the code blocks demo here: [https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html](https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html)

The answer to "why" is "because it works this way" as opposed to `<div>`, which does not.

**Comment by AnnaTomanek** [comment]
Makes sense, thanks!

**Review by AnnaTomanek — APPROVED** [review]

**Comment by Mgsy** [comment]
Indeed, the snippet doesn't work if a source element is `<div>`. However, changing the snippet to markdown, instead of HTML, fixes the problem and `<div>` could be used:

````markdown
```css
p {
	text-align: center;
	color: red;
}
```
````

I guess that's a bug in the Markdown data processor.

**Comment by Mgsy** [comment]
IMO that's fine to leave it with `<textarea>`, as there is a bug in the Markdown processor that can't parse this `<pre><code></code></pre>` structure properly. I'll report a follow-up.

**Pull request merged**
