### PR TITLE
Discovery: Export to PDF: text goes beyond its cell when columns are resized by resize handler

### PR DESCRIPTION
**Pull request by illia-stv**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (table): Text will no longer go beyond its cell when columns are resized by resize handler in Firefox. Closes [#14386](https://github.com/ckeditor/ckeditor5/issues/14386).
Fix (export-pdf): Text will no longer go beyond its cell when columns are resized by resize handler in exported PDFs. Closes [#3355](https://github.com/cksource/ckeditor5-internal/issues/3355).

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Comment by illia-stv** [comment]
Let's have a look how Chrome display table with `contenteditable` and without:

Screenshot 2023-06-13 at 16 34 22

And compare it with how Firefox handle it:

Screenshot 2023-06-13 at 16 32 18

So as you see, chrome UA adds property` overflow-wrap: break-word ` in case when its `contenteditable`.

Then it also explains why in firefox this is broken too:

image
 
So we just need to define this property directly in `table` package

**Comment by Dumluregn** [comment]
Let's merge it once QA team approves it and it gets R+ from our side.

**Comment by mlewand** [comment]
Thanks for the writeup @illia-stv - it surfaced one more thing that we didn't noted: **currently** (master branch) table content is rendered differently in Chrome & Firefox - that's also a bug.

This PR addresses this bug, so @illia-stv please search our issues list whether such bug has been already listed or not. If it wasn't reported, please report it.

Finally add this bug to list of closed issues by this PR.

**Review by Dumluregn — APPROVED** [review]
LGTM :+1: Let's wait for QA team confirmation.

**Comment by Dumluregn** [comment]
There's a green light from QAs :green\_circle:

**Pull request merged**
