### PR TITLE
The `supportAllValues` for `font-size` and  `font-family` doesn't work with nested elements(tables)

### LINKED ISSUE #7965: Font family and size with supportAllValues does not load
## 📝 Provide detailed reproduction steps (if any)

1. Go to online document demo;
2. From console paste
```
editors[0].setData('<figure class="table"><table><tbody><tr><td><span style="font-family:Arial, Helvetica, sans-serif;font-size:11px;">Font Arial 11</span></td></tr></tbody></table></figure>')
```
3. Check the applied font.

### ✔️ Expected result

Should show a table with content Font Arial 11 in Arial font and size 11px

### ❌ Actual result

Shows a table with content Font Arial 11 with no font styles applied

## 📃 Other details

Apparently changing the `upcast` conversion to `elementToAttribute` instead of `attributeToAttribute` in the `_prepareAnyValueConverters` resolves the problem.
But I am not sure if this is the correct way to solve it.

* Browser: Chrome
* OS: Windows
* CKEditor version: 21.0.0
* Installed CKEditor plugins: Default

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by dkrahn**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (font): Fixed the `supportAllValues` configuration for the `FontSize` and `FontFamily` features to work with nested elements (tables). Closes #7965.

### CODE REVIEW

**Comment by pomek** [comment]
Hi @dkrahn. Thanks for the PR. On the first look, the change looks good. However, it's a good practice to cover a bug with tests. Thanks to that, we're safe in the future. Those tests prevent making changes that could be regressions.
Could I ask about writing some that will cover the reported bug?

**Comment by dkrahn** [comment]
Hi @pomek I'll do that as soon as I have can. Thanks for the feedback.

**Comment by dkrahn** [comment]
Hi @pomek , I finally got some time to create the tests. But I'm not sure they're correct or even if the naming is ok. Hope they are as expected. Thanks for all the great work you and all the team have done!

**Comment by pomek** [comment]
Thanks, @dkrahn. I'll review the PR and if I miss anything, I add it.

**Comment by dkrahn** [comment]
Hi @pomek. I didn't understand was I did wrong. Could you assist me?

**Comment by pomek** [comment]
@dkrahn, I added a few integration tests that pass with your changes and fail without it.

Your tests were passing in both scenarios: using the current `#master` code, and also on your branch. So, in fact, those tests didn't cover the bug.

Let's wait for CI, and if it will be green, merge.

**Comment by pomek** [comment]
I thought we can write tests without the table package. However, they also pass on both versions of the code. So I decided to re-write the tests by wrapping the paragraph with the table. Now it looks good.

**Comment by dkrahn** [comment]
Thanks so much!!! Was nice to have the experience of sharing with this great project!

**Pull request merged**
