### PR TITLE
Enable two-step caret movement for `code` attribute.

### LINKED ISSUE #6722: Allow distinguishing between "cursor inside/outside inline code" (same as for links)
## 📝 Provide a description of the improvement

Currently, if you are at the end of a link, you can press <kbd>Right Arrow</kbd> once to "escape" it and type outside of the link. The link is highlighted when I'm inside it, but not when I'm outside. This is very convenient.

It would be great to have the same behavior for inline code. The only other editor I know that does this is the one used by Bitbucket. In this demo, note how I can escape the `<code>` merely by pressing <kbd>Right Arrow</kbd>.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by tomalec**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Other (basic-styles): Enable typing around for `code` element. Closes #6722.

---

### Additional information

The change is mostly copy-pasted from `LinkEditing`

I'm not sure whether such a tiny detail is worth mentioning in high-level docs at https://ckeditor.com/docs/ckeditor5/latest/features/basic-styles.html#available-text-styles.

Also, I wasn't sure whether highlighting should go into the scope of this issue. I made a draft at [`i/6722-code-caret-highlight`](https://github.com/ckeditor/ckeditor5/compare/i/6722-code-caret-highlight?expand=1). I think If it should be implemented here, I'd make a shared util/mixin so the code could be shared between `Link` and `Code`.

### CODE REVIEW

**Comment by tomalec** [comment]
We (@oleq, @niegowski and me) agreed today on F2F meeting, that visual feedback is necessary. 

I'll continue as started on [`i/6722-code-caret-highlight`](https://github.com/ckeditor/ckeditor5/compare/i/6722-code-caret-highlight?expand=1) branch, move highlighting code to [`..engine/src/utils/bindtwostepcarettoattribute.js`](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-engine/src/utils/bindtwostepcarettoattribute.js), make `Link` use it as well, and mention it in the docs.

**Comment by tomalec** [comment]
I've made link's highlight code slightly more re-usable,
used it for `code` as well, mentioned two-step movement in code feature docs.

The highlight effect is not visible in docs, due to a selector with higher specificity at https://github.com/cksource/umberto/blob/b8c9196cd2e653f2cf820be3291279a53bf83d9c/themes/umberto/src/css/_formatted.scss#L100

If the changes in this PR get approved, I'll create a followup PR there.

**Comment by tomalec** [comment]
Thanks, I'll cover those cases and add tests. I was not able to reproduce the first case, but maybe I'll get to it when investigating and solving others. Otherwise, I'll bother you a little, to help me with that.

**Comment by oleq** [comment]
The last one looks like #1108.

**Comment by tomalec** [comment]
I was not able to reproduce the highlight issue - I have [added a test](https://github.com/ckeditor/ckeditor5/pull/7356/commits/cd33448bb9723a0ccfbfd763abba5052e3f16134) to check against that.

I was trying to address "the same character" issue, but with no luck. I've [added the test to make sure it's not the result of 2SCM](https://github.com/ckeditor/ckeditor5/pull/7356/commits/32f18eaa0a7ea68b55d3622a4bf31ca605b71e08). Also, the issue is reproducible after commenting out the 2SCM and highlight code. 

I'll spend a few hours more trying to find a solution. In case I would not find any by Monday, I think this PR could be reviewed again, and follow it up at #1108.

**Comment by oleq** [comment]
> I was not able to reproduce the highlight issue - I have [added a test](https://github.com/ckeditor/ckeditor5/pull/7356/commits/cd33448bb9723a0ccfbfd763abba5052e3f16134) to check against that.

Take a look at this screencast, the left arrow is pressed thrice. 

## Actual

1.  The first key press moves the selection and overrides the gravity. If you start typing, a plain text is entered (✅ OK)
2.  The second one does nothing, it does not change the selection/selection attributes/gravity. If you start typing, a plain text is entered again (❌ NOK)
3.  The third one restores the gravity which gives the selection both `code` and `linkHref` attributes. If you start typing, a linked code is extended (✅ OK)



## Expected

1.  The first key press moves the selection and overrides the gravity.
2.  The second key press allows you to continue typing in a link (but not a code)
3.  The third key press allows you to type a linked code.

**Comment by tomalec** [comment]
Ok, I'll get into this, looks similar to https://github.com/ckeditor/ckeditor5/issues/946

**Comment by tomalec** [comment]
Closing in favor of https://github.com/ckeditor/ckeditor5/pull/7577

**Pull request closed without merging**
