### PR TITLE
Headings toolbar buttons

### PR DESCRIPTION
**Pull request by godai78**
Expanding the heading feature documentation with toolbar buttons feature info.

Close: #982

@Reinmar: please have a look at the code.  
@AnnaTomanek: review, please.

Thanks to @Mgsy for the helping hand with the snippets.

### CODE REVIEW

**Comment by AnnaTomanek** [comment]
I updated the guide and snippet a bit.

I have slightly mixed feelings with two demos with heading buttons shown in the article as they are basically the same. Not a blocker, though, it's better than not having this feature shown at all.

The Common API section is missing information about `HeadingButtonsUI`, `ParagraphButtonUI` and the individual toolbar buttons. @Reinmar it would be cool if you could have a look.

**Comment by Reinmar** [comment]
I'm not sure what you meant, but I see a problem in Heading 1 being equal Heading 2. 



That can be improved by changing it here:



So it's `h1`, `h2` and so on as in the previous example and then changing "Heading1" to `<h1>`.

**Comment by godai78** [comment]
I was inspired by this:  
  
By default this feature is configured to support `<h2>`, `<h3>` and `<h4>` elements which are named: “Heading 1”, “Heading 2” and “Heading 3”, respectively. The rationale behind starting from `<h2>` is that `<h1>` should be reserved for the [page’s main title](https://ckeditor.com/docs/ckeditor5/latest/features/title.html) and the page content will usually start from `<h2>`.  
  
From here: https://ckeditor.com/docs/ckeditor5/latest/features/headings.html  
  
It can be changed easily.

**Comment by AnnaTomanek** [comment]
I fixed this to make it consistent with the existing example. However, it makes me wonder whether all the examples do not really conflict (logically) with the "Heading levels" section that we have at the beginning. Because we first explain why by default we start from `<h2>` and then all the examples actually change that and start from `<h1>`.

Anyway, this was pre-existing so we can fix it later if we want.

Still, the "Common API" section is missing information about `HeadingButtonsUI`, `ParagraphButtonUI` and the individual toolbar buttons. [**@Reinmar**](https://github.com/Reinmar) it would be cool if you could help with this part :wink:

**Review by AnnaTomanek — APPROVED** [review]
Looks fine now, the h1 vs h2 stuff can be reconsidered later.

**Pull request merged**
