### PR TITLE
PBC should consider all scrollable ancestors

### LINKED ISSUE #14536: Powered by logo considers only the first scrollable ancestor while managing visibility
### ✔️ Expected result

It should hide when the outer ancestor is scrolled.

### ❌ Actual result

It stays visible but attached to the void.

### ❓ Possible solution

The problem is the logic considers the first scrollable ancestor only while it should consider all of them.

https://github.com/ckeditor/ckeditor5/blob/f72fdf4f406c2f5a9164f3f224002793944dd2e2/packages/ckeditor5-ui/src/editorui/poweredby.ts#L350-L361

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by illia-stv**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (ui): PowerBy considers all scrollable ancestor. Closes #14536.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Review by pszczesniak — COMMENTED** [review]
I've updated the manual test (added `Ancestors with overflow`). It's also not working as expected BUT... lets fix first this #14597 , after merge we will look at it one more time.

**Comment by Dumluregn** [comment]
Sth tells me the commit history for this PR is not right :slightly\_smiling\_face:

**Review by pszczesniak — APPROVED** [review]
:+1: 

I did small code refactor based on BallonPanelView updates.

**Comment by pszczesniak** [comment]
Solved by #14755

**Pull request closed without merging**
